// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabExamExamInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabExamExamInfo {
	
		// Fields
	
		private String FExamId;
		private String FExamName;
		private String FExamNo;
		private String FExamYear;
		private String FExamDesc;
		private Int32 FExamAttri;
		private String FPlanId;
		private String FPlanName;
		private String FExamRange;
		private String FExamKnowledge;
		private Int32 FExamType;
		private DateTime FExamBegintime;
		private DateTime FExamEndtime;
		private Int32 FExamDuration;
		private Double FTotalScore;
		private Double FPassScore;
		private Int32 FShowType;
		private Int32 FRetestTimes;
		private Int32 FIfNotice;
		private String FNoticeWay;
		private Int32 FNoticeDays;
		private Int32 FIfSubjective;
		private Int32 FExamLimit;
		private String FSysuserId;
		private String FServplatId;
		private DateTime FCreateTime;
		private Int32 FStatus;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabExamExamInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabExamExamInfo(String FExamId_0) {
			this.FExamId = FExamId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabExamExamInfo(String FExamId_0, String FExamName_1, String FExamNo_2,
				String FExamYear_3, String FExamDesc_4, Int32 FExamAttri_5,
				String FPlanId_6, String FPlanName_7, String FExamRange_8,
				String FExamKnowledge_9, Int32 FExamType_10, DateTime FExamBegintime_11,
				DateTime FExamEndtime_12, Int32 FExamDuration_13, Double FTotalScore_14,
				Double FPassScore_15, Int32 FShowType_16, Int32 FRetestTimes_17,
				Int32 FIfNotice_18, String FNoticeWay_19, Int32 FNoticeDays_20,
				Int32 FIfSubjective_21, Int32 FExamLimit_22, String FSysuserId_23,
				String FServplatId_24, DateTime FCreateTime_25, Int32 FStatus_26) {
			this.FExamId = FExamId_0;
			this.FExamName = FExamName_1;
			this.FExamNo = FExamNo_2;
			this.FExamYear = FExamYear_3;
			this.FExamDesc = FExamDesc_4;
			this.FExamAttri = FExamAttri_5;
			this.FPlanId = FPlanId_6;
			this.FPlanName = FPlanName_7;
			this.FExamRange = FExamRange_8;
			this.FExamKnowledge = FExamKnowledge_9;
			this.FExamType = FExamType_10;
			this.FExamBegintime = FExamBegintime_11;
			this.FExamEndtime = FExamEndtime_12;
			this.FExamDuration = FExamDuration_13;
			this.FTotalScore = FTotalScore_14;
			this.FPassScore = FPassScore_15;
			this.FShowType = FShowType_16;
			this.FRetestTimes = FRetestTimes_17;
			this.FIfNotice = FIfNotice_18;
			this.FNoticeWay = FNoticeWay_19;
			this.FNoticeDays = FNoticeDays_20;
			this.FIfSubjective = FIfSubjective_21;
			this.FExamLimit = FExamLimit_22;
			this.FSysuserId = FSysuserId_23;
			this.FServplatId = FServplatId_24;
			this.FCreateTime = FCreateTime_25;
			this.FStatus = FStatus_26;
		}
	
		// Property accessors
	
		public String GetFExamId() {
			return this.FExamId;
		}
	
		public void SetFExamId(String FExamId_0) {
			this.FExamId = FExamId_0;
		}
	
		public String GetFExamName() {
			return this.FExamName;
		}
	
		public void SetFExamName(String FExamName_0) {
			this.FExamName = FExamName_0;
		}
	
		public String GetFExamNo() {
			return this.FExamNo;
		}
	
		public void SetFExamNo(String FExamNo_0) {
			this.FExamNo = FExamNo_0;
		}
	
		public String GetFExamYear() {
			return this.FExamYear;
		}
	
		public void SetFExamYear(String FExamYear_0) {
			this.FExamYear = FExamYear_0;
		}
	
		public String GetFExamDesc() {
			return this.FExamDesc;
		}
	
		public void SetFExamDesc(String FExamDesc_0) {
			this.FExamDesc = FExamDesc_0;
		}
	
		public Int32 GetFExamAttri() {
			return this.FExamAttri;
		}
	
		public void SetFExamAttri(Int32 FExamAttri_0) {
			this.FExamAttri = FExamAttri_0;
		}
	
		public String GetFPlanId() {
			return FPlanId;
		}
	
		public void SetFPlanId(String fPlanId) {
			FPlanId = fPlanId;
		}
	
		public String GetFPlanName() {
			return FPlanName;
		}
	
		public void SetFPlanName(String fPlanName) {
			FPlanName = fPlanName;
		}
	
		public String GetFExamRange() {
			return this.FExamRange;
		}
	
		public void SetFExamRange(String FExamRange_0) {
			this.FExamRange = FExamRange_0;
		}
	
		public String GetFExamKnowledge() {
			return this.FExamKnowledge;
		}
	
		public void SetFExamKnowledge(String FExamKnowledge_0) {
			this.FExamKnowledge = FExamKnowledge_0;
		}
	
		public Int32 GetFExamType() {
			return this.FExamType;
		}
	
		public void SetFExamType(Int32 FExamType_0) {
			this.FExamType = FExamType_0;
		}
	
		public DateTime GetFExamBegintime() {
			return this.FExamBegintime;
		}
	
		public void SetFExamBegintime(DateTime FExamBegintime_0) {
			this.FExamBegintime = FExamBegintime_0;
		}
	
		public DateTime GetFExamEndtime() {
			return this.FExamEndtime;
		}
	
		public void SetFExamEndtime(DateTime FExamEndtime_0) {
			this.FExamEndtime = FExamEndtime_0;
		}
	
		public Int32 GetFExamDuration() {
			return this.FExamDuration;
		}
	
		public void SetFExamDuration(Int32 FExamDuration_0) {
			this.FExamDuration = FExamDuration_0;
		}
	
		public Double GetFTotalScore() {
			return this.FTotalScore;
		}
	
		public void SetFTotalScore(Double FTotalScore_0) {
			this.FTotalScore = FTotalScore_0;
		}
	
		public Double GetFPassScore() {
			return this.FPassScore;
		}
	
		public void SetFPassScore(Double FPassScore_0) {
			this.FPassScore = FPassScore_0;
		}
	
		public Int32 GetFShowType() {
			return this.FShowType;
		}
	
		public void SetFShowType(Int32 FShowType_0) {
			this.FShowType = FShowType_0;
		}
	
		public Int32 GetFRetestTimes() {
			return this.FRetestTimes;
		}
	
		public void SetFRetestTimes(Int32 FRetestTimes_0) {
			this.FRetestTimes = FRetestTimes_0;
		}
	
		public Int32 GetFIfNotice() {
			return this.FIfNotice;
		}
	
		public void SetFIfNotice(Int32 FIfNotice_0) {
			this.FIfNotice = FIfNotice_0;
		}
	
		public String GetFNoticeWay() {
			return this.FNoticeWay;
		}
	
		public void SetFNoticeWay(String FNoticeWay_0) {
			this.FNoticeWay = FNoticeWay_0;
		}
	
		public Int32 GetFNoticeDays() {
			return this.FNoticeDays;
		}
	
		public void SetFNoticeDays(Int32 FNoticeDays_0) {
			this.FNoticeDays = FNoticeDays_0;
		}
	
		public Int32 GetFIfSubjective() {
			return this.FIfSubjective;
		}
	
		public void SetFIfSubjective(Int32 FIfSubjective_0) {
			this.FIfSubjective = FIfSubjective_0;
		}
	
		public Int32 GetFExamLimit() {
			return this.FExamLimit;
		}
	
		public void SetFExamLimit(Int32 FExamLimit_0) {
			this.FExamLimit = FExamLimit_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public DateTime GetFCreateTime() {
			return this.FCreateTime;
		}
	
		public void SetFCreateTime(DateTime FCreateTime_0) {
			this.FCreateTime = FCreateTime_0;
		}
	
		public Int32 GetFStatus() {
			return this.FStatus;
		}
	
		public void SetFStatus(Int32 FStatus_0) {
			this.FStatus = FStatus_0;
		}
	
	}}
