// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabExamExampaperInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabExamExampaperInfo {
	
		// Fields
	
		private String FExampaperId;
		private String FQuestionId;
		private String FPapersId;
		private Double FQuestionScore;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabExamExampaperInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabExamExampaperInfo(String FExampaperId_0) {
			this.FExampaperId = FExampaperId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabExamExampaperInfo(String FExampaperId_0, String FQuestionId_1,
				String FPapersId_2, Double FQuestionScore_3) {
			this.FExampaperId = FExampaperId_0;
			this.FQuestionId = FQuestionId_1;
			this.FPapersId = FPapersId_2;
			this.FQuestionScore = FQuestionScore_3;
		}
	
		// Property accessors
	
		public String GetFExampaperId() {
			return this.FExampaperId;
		}
	
		public void SetFExampaperId(String FExampaperId_0) {
			this.FExampaperId = FExampaperId_0;
		}
	
		public String GetFQuestionId() {
			return this.FQuestionId;
		}
	
		public void SetFQuestionId(String FQuestionId_0) {
			this.FQuestionId = FQuestionId_0;
		}
	
		public String GetFPapersId() {
			return this.FPapersId;
		}
	
		public void SetFPapersId(String FPapersId_0) {
			this.FPapersId = FPapersId_0;
		}
	
		public Double GetFQuestionScore() {
			return this.FQuestionScore;
		}
	
		public void SetFQuestionScore(Double FQuestionScore_0) {
			this.FQuestionScore = FQuestionScore_0;
		}
	
	}}
