// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabExamQuestionKnowledge entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabExamQuestionKnowledge {
	
		// Fields
	
		private String FUnionId;
		private String FKnowledgeId;
		private String FQuestionId;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabExamQuestionKnowledge() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabExamQuestionKnowledge(String FUnionId_0) {
			this.FUnionId = FUnionId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabExamQuestionKnowledge(String FUnionId_0, String FKnowledgeId_1,
				String FQuestionId_2) {
			this.FUnionId = FUnionId_0;
			this.FKnowledgeId = FKnowledgeId_1;
			this.FQuestionId = FQuestionId_2;
		}
	
		// Property accessors
	
		public String GetFUnionId() {
			return this.FUnionId;
		}
	
		public void SetFUnionId(String FUnionId_0) {
			this.FUnionId = FUnionId_0;
		}
	
		public String GetFKnowledgeId() {
			return this.FKnowledgeId;
		}
	
		public void SetFKnowledgeId(String FKnowledgeId_0) {
			this.FKnowledgeId = FKnowledgeId_0;
		}
	
		public String GetFQuestionId() {
			return this.FQuestionId;
		}
	
		public void SetFQuestionId(String FQuestionId_0) {
			this.FQuestionId = FQuestionId_0;
		}
	
	}}
