// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabExamCheckdistInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	/* @SuppressWarnings("serial")*/
	public class TabExamCheckdistInfo {
	
		// Fields
	
		private String FCheckdistId;
		private String FSysuserId;
		private String FSysuserName;
		private String FUserId;
		private String FUserName;
		private String FOrgPath;
		private String FRecordId;
		private DateTime FDistTime;
		private Int32 FCheckStatus;
		private String FServplatId;
		private String FServplatName;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabExamCheckdistInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabExamCheckdistInfo(String FCheckdistId_0) {
			this.FCheckdistId = FCheckdistId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabExamCheckdistInfo(String FCheckdistId_0, String FSysuserId_1,
				String FSysuserName_2, String FUserId_3, String FUserName_4,
				String FOrgPath_5, String FRecordId_6, DateTime FDistTime_7,
				Int32 FCheckStatus_8, String FServplatId_9, String FServplatName_10) {
			this.FCheckdistId = FCheckdistId_0;
			this.FSysuserId = FSysuserId_1;
			this.FSysuserName = FSysuserName_2;
			this.FUserId = FUserId_3;
			this.FUserName = FUserName_4;
			this.FOrgPath = FOrgPath_5;
			this.FRecordId = FRecordId_6;
			this.FDistTime = FDistTime_7;
			this.FCheckStatus = FCheckStatus_8;
			this.FServplatId = FServplatId_9;
			this.FServplatName = FServplatName_10;
		}
	
		// Property accessors
	
		public String GetFCheckdistId() {
			return this.FCheckdistId;
		}
	
		public void SetFCheckdistId(String FCheckdistId_0) {
			this.FCheckdistId = FCheckdistId_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public String GetFSysuserName() {
			return this.FSysuserName;
		}
	
		public void SetFSysuserName(String FSysuserName_0) {
			this.FSysuserName = FSysuserName_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFOrgPath() {
			return this.FOrgPath;
		}
	
		public void SetFOrgPath(String FOrgPath_0) {
			this.FOrgPath = FOrgPath_0;
		}
	
		public String GetFRecordId() {
			return this.FRecordId;
		}
	
		public void SetFRecordId(String FRecordId_0) {
			this.FRecordId = FRecordId_0;
		}
	
		public DateTime GetFDistTime() {
			return this.FDistTime;
		}
	
		public void SetFDistTime(DateTime FDistTime_0) {
			this.FDistTime = FDistTime_0;
		}
	
		public Int32 GetFCheckStatus() {
			return this.FCheckStatus;
		}
	
		public void SetFCheckStatus(Int32 FCheckStatus_0) {
			this.FCheckStatus = FCheckStatus_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public String GetFServplatName() {
			return this.FServplatName;
		}
	
		public void SetFServplatName(String FServplatName_0) {
			this.FServplatName = FServplatName_0;
		}
	
	}}
