// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabExamPapersInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabExamPapersInfo {
	
		// Fields
	
		private String FPapersId;
		private String FExamId;
		private String FPapersName;
		private Int32 FTotalScore;
		private Int32 FTotalNums;
		private Int32 FPageNums;
		private Int32 FIfSubjectorder;
		private Int32 FIfAnswerorder;
		private Int32 FIfRandom;
		private Int32 FSingleNums;
		private Int32 FSingleScore;
		private Int32 FMultipleNums;
		private Int32 FMultipleScore;
		private Int32 FFillsNums;
		private Int32 FFillsScore;
		private Int32 FJudgeNums;
		private Int32 FJudgeScore;
		private Int32 FQaNums;
		private Int32 FQaScore;
		private Int32 FLineNums;
		private Int32 FLineScore;
		private Int32 FPapersStatus;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabExamPapersInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabExamPapersInfo(String FPapersId_0) {
			this.FPapersId = FPapersId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabExamPapersInfo(String FPapersId_0, String FExamId_1,
				String FPapersName_2, Int32 FTotalScore_3, Int32 FTotalNums_4,
				Int32 FPageNums_5, Int32 FIfSubjectorder_6, Int32 FIfAnswerorder_7,
				Int32 FIfRandom_8, Int32 FSingleNums_9, Int32 FSingleScore_10,
				Int32 FMultipleNums_11, Int32 FMultipleScore_12, Int32 FFillsNums_13,
				Int32 FFillsScore_14, Int32 FJudgeNums_15, Int32 FJudgeScore_16,
				Int32 FQaNums_17, Int32 FQaScore_18, Int32 FPapersStatus_19) {
			this.FPapersId = FPapersId_0;
			this.FExamId = FExamId_1;
			this.FPapersName = FPapersName_2;
			this.FTotalScore = FTotalScore_3;
			this.FTotalNums = FTotalNums_4;
			this.FPageNums = FPageNums_5;
			this.FIfSubjectorder = FIfSubjectorder_6;
			this.FIfAnswerorder = FIfAnswerorder_7;
			this.FIfRandom = FIfRandom_8;
			this.FSingleNums = FSingleNums_9;
			this.FSingleScore = FSingleScore_10;
			this.FMultipleNums = FMultipleNums_11;
			this.FMultipleScore = FMultipleScore_12;
			this.FFillsNums = FFillsNums_13;
			this.FFillsScore = FFillsScore_14;
			this.FJudgeNums = FJudgeNums_15;
			this.FJudgeScore = FJudgeScore_16;
			this.FQaNums = FQaNums_17;
			this.FQaScore = FQaScore_18;
			this.FPapersStatus = FPapersStatus_19;
		}
	
		// Property accessors
	
		public String GetFPapersId() {
			return this.FPapersId;
		}
	
		public void SetFPapersId(String FPapersId_0) {
			this.FPapersId = FPapersId_0;
		}
	
		public String GetFExamId() {
			return this.FExamId;
		}
	
		public void SetFExamId(String FExamId_0) {
			this.FExamId = FExamId_0;
		}
	
		public String GetFPapersName() {
			return this.FPapersName;
		}
	
		public void SetFPapersName(String FPapersName_0) {
			this.FPapersName = FPapersName_0;
		}
	
		public Int32 GetFTotalScore() {
			return this.FTotalScore;
		}
	
		public void SetFTotalScore(Int32 FTotalScore_0) {
			this.FTotalScore = FTotalScore_0;
		}
	
		public Int32 GetFTotalNums() {
			return this.FTotalNums;
		}
	
		public void SetFTotalNums(Int32 FTotalNums_0) {
			this.FTotalNums = FTotalNums_0;
		}
	
		public Int32 GetFPageNums() {
			return this.FPageNums;
		}
	
		public void SetFPageNums(Int32 FPageNums_0) {
			this.FPageNums = FPageNums_0;
		}
	
		public Int32 GetFIfSubjectorder() {
			return this.FIfSubjectorder;
		}
	
		public void SetFIfSubjectorder(Int32 FIfSubjectorder_0) {
			this.FIfSubjectorder = FIfSubjectorder_0;
		}
	
		public Int32 GetFIfAnswerorder() {
			return this.FIfAnswerorder;
		}
	
		public void SetFIfAnswerorder(Int32 FIfAnswerorder_0) {
			this.FIfAnswerorder = FIfAnswerorder_0;
		}
	
		public Int32 GetFIfRandom() {
			return this.FIfRandom;
		}
	
		public void SetFIfRandom(Int32 FIfRandom_0) {
			this.FIfRandom = FIfRandom_0;
		}
	
		public Int32 GetFSingleNums() {
			return this.FSingleNums;
		}
	
		public void SetFSingleNums(Int32 FSingleNums_0) {
			this.FSingleNums = FSingleNums_0;
		}
	
		public Int32 GetFSingleScore() {
			return this.FSingleScore;
		}
	
		public void SetFSingleScore(Int32 FSingleScore_0) {
			this.FSingleScore = FSingleScore_0;
		}
	
		public Int32 GetFMultipleNums() {
			return this.FMultipleNums;
		}
	
		public void SetFMultipleNums(Int32 FMultipleNums_0) {
			this.FMultipleNums = FMultipleNums_0;
		}
	
		public Int32 GetFMultipleScore() {
			return this.FMultipleScore;
		}
	
		public void SetFMultipleScore(Int32 FMultipleScore_0) {
			this.FMultipleScore = FMultipleScore_0;
		}
	
		public Int32 GetFFillsNums() {
			return this.FFillsNums;
		}
	
		public void SetFFillsNums(Int32 FFillsNums_0) {
			this.FFillsNums = FFillsNums_0;
		}
	
		public Int32 GetFFillsScore() {
			return this.FFillsScore;
		}
	
		public void SetFFillsScore(Int32 FFillsScore_0) {
			this.FFillsScore = FFillsScore_0;
		}
	
		public Int32 GetFJudgeNums() {
			return this.FJudgeNums;
		}
	
		public void SetFJudgeNums(Int32 FJudgeNums_0) {
			this.FJudgeNums = FJudgeNums_0;
		}
	
		public Int32 GetFJudgeScore() {
			return this.FJudgeScore;
		}
	
		public void SetFJudgeScore(Int32 FJudgeScore_0) {
			this.FJudgeScore = FJudgeScore_0;
		}
	
		public Int32 GetFQaNums() {
			return this.FQaNums;
		}
	
		public void SetFQaNums(Int32 FQaNums_0) {
			this.FQaNums = FQaNums_0;
		}
	
		public Int32 GetFQaScore() {
			return this.FQaScore;
		}
	
		public void SetFQaScore(Int32 FQaScore_0) {
			this.FQaScore = FQaScore_0;
		}
	
		public Int32 GetFPapersStatus() {
			return FPapersStatus;
		}
	
		public void SetFPapersStatus(Int32 fPapersStatus) {
			FPapersStatus = fPapersStatus;
		}
	
		public Int32 GetFLineNums() {
			return FLineNums;
		}
	
		public void SetFLineNums(Int32 fLineNums) {
			FLineNums = fLineNums;
		}
	
		public Int32 GetFLineScore() {
			return FLineScore;
		}
	
		public void SetFLineScore(Int32 fLineScore) {
			FLineScore = fLineScore;
		}
	
	}}
