// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabExamExamCourse entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabExamExamCourse {
	
		// Fields
	
		private String FUnionId;
		private String FCourseId;
		private String FEntityId;
		private String FExamId;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabExamExamCourse() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabExamExamCourse(String FUnionId_0) {
			this.FUnionId = FUnionId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabExamExamCourse(String FUnionId_0, String FCourseId_1,
				String FEntityId_2, String FExamId_3) {
			this.FUnionId = FUnionId_0;
			this.FCourseId = FCourseId_1;
			this.FEntityId = FEntityId_2;
			this.FExamId = FExamId_3;
		}
	
		// Property accessors
	
		public String GetFUnionId() {
			return this.FUnionId;
		}
	
		public void SetFUnionId(String FUnionId_0) {
			this.FUnionId = FUnionId_0;
		}
	
		public String GetFCourseId() {
			return this.FCourseId;
		}
	
		public void SetFCourseId(String FCourseId_0) {
			this.FCourseId = FCourseId_0;
		}
	
		public String GetFEntityId() {
			return this.FEntityId;
		}
	
		public void SetFEntityId(String FEntityId_0) {
			this.FEntityId = FEntityId_0;
		}
	
		public String GetFExamId() {
			return this.FExamId;
		}
	
		public void SetFExamId(String FExamId_0) {
			this.FExamId = FExamId_0;
		}
	
	}}
