// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabExamQuestionInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabExamQuestionInfo {
	
		// Fields
	
		private String FQuestionId;
		private String FQtypeId;
		private String FDlevelId;
		private String FSysuserId;
		private String FSupplierId;
		private String FSupplierName;
		private DateTime FCreateTime;
		private String FQuestionInfo;
		private String FQuestionAnswer;
		private Int32 FQuestionScore;
		private Int32 FAnswerTime;
		private Int32 FFromType;
		private Int32 FVerifyStatus;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabExamQuestionInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabExamQuestionInfo(String FQuestionId_0) {
			this.FQuestionId = FQuestionId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabExamQuestionInfo(String FQuestionId_0, String FQtypeId_1,
				String FDlevelId_2, String FSysuserId_3, String FSupplierId_4,
				String FSupplierName_5, DateTime FCreateTime_6, String FQuestionInfo_7,
				String FQuestionAnswer_8, Int32 FQuestionScore_9,
				Int32 FAnswerTime_10, Int32 FFromType_11, Int32 FVerifyStatus_12) {
			this.FQuestionId = FQuestionId_0;
			this.FQtypeId = FQtypeId_1;
			this.FDlevelId = FDlevelId_2;
			this.FSysuserId = FSysuserId_3;
			this.FSupplierId = FSupplierId_4;
			this.FSupplierName = FSupplierName_5;
			this.FCreateTime = FCreateTime_6;
			this.FQuestionInfo = FQuestionInfo_7;
			this.FQuestionAnswer = FQuestionAnswer_8;
			this.FQuestionScore = FQuestionScore_9;
			this.FAnswerTime = FAnswerTime_10;
			this.FFromType = FFromType_11;
			this.FVerifyStatus = FVerifyStatus_12;
		}
	
		// Property accessors
	
		public String GetFQuestionId() {
			return this.FQuestionId;
		}
	
		public void SetFQuestionId(String FQuestionId_0) {
			this.FQuestionId = FQuestionId_0;
		}
	
		public String GetFQtypeId() {
			return this.FQtypeId;
		}
	
		public void SetFQtypeId(String FQtypeId_0) {
			this.FQtypeId = FQtypeId_0;
		}
	
		public String GetFDlevelId() {
			return this.FDlevelId;
		}
	
		public void SetFDlevelId(String FDlevelId_0) {
			this.FDlevelId = FDlevelId_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public String GetFSupplierId() {
			return this.FSupplierId;
		}
	
		public void SetFSupplierId(String FSupplierId_0) {
			this.FSupplierId = FSupplierId_0;
		}
	
		public String GetFSupplierName() {
			return this.FSupplierName;
		}
	
		public void SetFSupplierName(String FSupplierName_0) {
			this.FSupplierName = FSupplierName_0;
		}
	
		public DateTime GetFCreateTime() {
			return FCreateTime;
		}
	
		public void SetFCreateTime(DateTime fCreateTime) {
			FCreateTime = fCreateTime;
		}
	
		public String GetFQuestionInfo() {
			return this.FQuestionInfo;
		}
	
		public void SetFQuestionInfo(String FQuestionInfo_0) {
			this.FQuestionInfo = FQuestionInfo_0;
		}
	
		public String GetFQuestionAnswer() {
			return this.FQuestionAnswer;
		}
	
		public void SetFQuestionAnswer(String FQuestionAnswer_0) {
			this.FQuestionAnswer = FQuestionAnswer_0;
		}
	
		public Int32 GetFQuestionScore() {
			return this.FQuestionScore;
		}
	
		public void SetFQuestionScore(Int32 FQuestionScore_0) {
			this.FQuestionScore = FQuestionScore_0;
		}
	
		public Int32 GetFAnswerTime() {
			return this.FAnswerTime;
		}
	
		public void SetFAnswerTime(Int32 FAnswerTime_0) {
			this.FAnswerTime = FAnswerTime_0;
		}
	
		public Int32 GetFFromType() {
			return this.FFromType;
		}
	
		public void SetFFromType(Int32 FFromType_0) {
			this.FFromType = FFromType_0;
		}
	
		public Int32 GetFVerifyStatus() {
			return this.FVerifyStatus;
		}
	
		public void SetFVerifyStatus(Int32 FVerifyStatus_0) {
			this.FVerifyStatus = FVerifyStatus_0;
		}
	
	}}
