// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabExamQuestionChoice entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabExamQuestionChoice {
	
		// Fields
	
		private String FChoiceId;
		private String FQuestionId;
		private String FSortCode;
		private String FChoiceInfo;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabExamQuestionChoice() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabExamQuestionChoice(String FChoiceId_0) {
			this.FChoiceId = FChoiceId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabExamQuestionChoice(String FChoiceId_0, String FQuestionId_1,
				String FSortCode_2, String FChoiceInfo_3) {
			this.FChoiceId = FChoiceId_0;
			this.FQuestionId = FQuestionId_1;
			this.FSortCode = FSortCode_2;
			this.FChoiceInfo = FChoiceInfo_3;
		}
	
		// Property accessors
	
		public String GetFChoiceId() {
			return this.FChoiceId;
		}
	
		public void SetFChoiceId(String FChoiceId_0) {
			this.FChoiceId = FChoiceId_0;
		}
	
		public String GetFQuestionId() {
			return this.FQuestionId;
		}
	
		public void SetFQuestionId(String FQuestionId_0) {
			this.FQuestionId = FQuestionId_0;
		}
	
		public String GetFSortCode() {
			return this.FSortCode;
		}
	
		public void SetFSortCode(String FSortCode_0) {
			this.FSortCode = FSortCode_0;
		}
	
		public String GetFChoiceInfo() {
			return this.FChoiceInfo;
		}
	
		public void SetFChoiceInfo(String FChoiceInfo_0) {
			this.FChoiceInfo = FChoiceInfo_0;
		}
	
	}}
