// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/* @SuppressWarnings("serial")*/
	[Serializable]
	public class TabNaireQuestionInfo {
	
		private String FQuestionId; //问题ID
		private String FQuestionInfo; //问题内容
		private String FQuestionAnswer; //问题答案(保留,也许用得着)
		private String FNaireId; //问卷ID
		private String FEditorId; //编辑人ID
		private String FEditorName; //编辑人姓名
		private DateTime FCreateTime; //上传时间
		private Int32 FFromType; //问题来源(1、xx;2、xx)
		private Int32 FType; //问题类型(1、单选;5、问答)
		private Int32 FSort; //排序号
	
		public TabNaireQuestionInfo() : base() {
		}
	
		public TabNaireQuestionInfo(String fQuestionId, String fQuestionInfo,
				String fQuestionAnswer, String fNaireId, String fEditorId,
				String fEditorName, DateTime fCreateTime, Int32 fFromType,
				Int32 fType, Int32 fSort) : base() {
			FQuestionId = fQuestionId;
			FQuestionInfo = fQuestionInfo;
			FQuestionAnswer = fQuestionAnswer;
			FNaireId = fNaireId;
			FEditorId = fEditorId;
			FEditorName = fEditorName;
			FCreateTime = fCreateTime;
			FFromType = fFromType;
			FType = fType;
			FSort = fSort;
		}
	
		public String GetFQuestionId() {
			return FQuestionId;
		}
	
		public void SetFQuestionId(String fQuestionId) {
			FQuestionId = fQuestionId;
		}
	
		public String GetFQuestionInfo() {
			return FQuestionInfo;
		}
	
		public void SetFQuestionInfo(String fQuestionInfo) {
			FQuestionInfo = fQuestionInfo;
		}
	
		public String GetFQuestionAnswer() {
			return FQuestionAnswer;
		}
	
		public void SetFQuestionAnswer(String fQuestionAnswer) {
			FQuestionAnswer = fQuestionAnswer;
		}
	
		public String GetFNaireId() {
			return FNaireId;
		}
	
		public void SetFNaireId(String fNaireId) {
			FNaireId = fNaireId;
		}
	
		public String GetFEditorId() {
			return FEditorId;
		}
	
		public void SetFEditorId(String fEditorId) {
			FEditorId = fEditorId;
		}
	
		public String GetFEditorName() {
			return FEditorName;
		}
	
		public void SetFEditorName(String fEditorName) {
			FEditorName = fEditorName;
		}
	
		public DateTime GetFCreateTime() {
			return FCreateTime;
		}
	
		public void SetFCreateTime(DateTime fCreateTime) {
			FCreateTime = fCreateTime;
		}
	
		public Int32 GetFFromType() {
			return FFromType;
		}
	
		public void SetFFromType(Int32 fFromType) {
			FFromType = fFromType;
		}
	
		public Int32 GetFType() {
			return FType;
		}
	
		public void SetFType(Int32 fType) {
			FType = fType;
		}
	
		public Int32 GetFSort() {
			return FSort;
		}
	
		public void SetFSort(Int32 fSort) {
			FSort = fSort;
		}
	
	}
}
