// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/* @SuppressWarnings("serial")*/
	[Serializable]
	public class TabNaireUsernaireRecord {
	
		private String FRecordId; //学员问卷-记录编号
		private String FUserId; //学员ID
		private String FUserName; //学员姓名
		private String FServplatId; //平台ID
		private String FServplatName; //平台名称
		private String FOrgId; //组织机构ID
		private String FOrgName; //机构名称
		private String FNaireId; //问卷ID
		private String FNaireName; //问卷名称
		private Int32 FNaireType; //问卷类型(1,xxx  2,xxx)
		private String FQuestionId; //问题ID
		private String FQuestionInfo; //问题描述
		private String FUserAnswer; //学员的答案
		private Int32 FType; //题目类型
		private DateTime FBeginTime; //答卷-开始时间
		private DateTime FEndTime; //答卷-结束时间
		private Int32 FDuration; //答卷时长
	
		public TabNaireUsernaireRecord() : base() {
		}
	
		public TabNaireUsernaireRecord(String fRecordId, String fUserId,
				String fUserName, String fServplatId, String fServplatName,
				String fOrgId, String fOrgName, String fNaireId, String fNaireName,
				Int32 fNaireType, String fQuestionId, String fQuestionInfo,
				String fUserAnswer, Int32 fType, DateTime fBeginTime, DateTime fEndTime,
				Int32 fDuration) : base() {
			FRecordId = fRecordId;
			FUserId = fUserId;
			FUserName = fUserName;
			FServplatId = fServplatId;
			FServplatName = fServplatName;
			FOrgId = fOrgId;
			FOrgName = fOrgName;
			FNaireId = fNaireId;
			FNaireName = fNaireName;
			FNaireType = fNaireType;
			FQuestionId = fQuestionId;
			FQuestionInfo = fQuestionInfo;
			FUserAnswer = fUserAnswer;
			FType = fType;
			FBeginTime = fBeginTime;
			FEndTime = fEndTime;
			FDuration = fDuration;
		}
	
		public String GetFRecordId() {
			return FRecordId;
		}
	
		public void SetFRecordId(String fRecordId) {
			FRecordId = fRecordId;
		}
	
		public String GetFUserId() {
			return FUserId;
		}
	
		public void SetFUserId(String fUserId) {
			FUserId = fUserId;
		}
	
		public String GetFUserName() {
			return FUserName;
		}
	
		public void SetFUserName(String fUserName) {
			FUserName = fUserName;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
		public String GetFOrgId() {
			return FOrgId;
		}
	
		public void SetFOrgId(String fOrgId) {
			FOrgId = fOrgId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFNaireId() {
			return FNaireId;
		}
	
		public void SetFNaireId(String fNaireId) {
			FNaireId = fNaireId;
		}
	
		public String GetFNaireName() {
			return FNaireName;
		}
	
		public void SetFNaireName(String fNaireName) {
			FNaireName = fNaireName;
		}
	
		public Int32 GetFNaireType() {
			return FNaireType;
		}
	
		public void SetFNaireType(Int32 fNaireType) {
			FNaireType = fNaireType;
		}
	
		public String GetFQuestionId() {
			return FQuestionId;
		}
	
		public void SetFQuestionId(String fQuestionId) {
			FQuestionId = fQuestionId;
		}
	
		public String GetFUserAnswer() {
			return FUserAnswer;
		}
	
		public void SetFUserAnswer(String fUserAnswer) {
			FUserAnswer = fUserAnswer;
		}
	
		public DateTime GetFBeginTime() {
			return FBeginTime;
		}
	
		public void SetFBeginTime(DateTime fBeginTime) {
			FBeginTime = fBeginTime;
		}
	
		public DateTime GetFEndTime() {
			return FEndTime;
		}
	
		public void SetFEndTime(DateTime fEndTime) {
			FEndTime = fEndTime;
		}
	
		public Int32 GetFDuration() {
			return FDuration;
		}
	
		public void SetFDuration(Int32 fDuration) {
			FDuration = fDuration;
		}
	
		public Int32 GetFType() {
			return FType;
		}
	
		public void SetFType(Int32 fType) {
			FType = fType;
		}
	
		public String GetFQuestionInfo() {
			return FQuestionInfo;
		}
	
		public void SetFQuestionInfo(String fQuestionInfo) {
			FQuestionInfo = fQuestionInfo;
		}
	
	}
}
