// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/* @SuppressWarnings("serial")*/
	[Serializable]
	public class TabNaireNaireplatInfo {
	
		private String FUnionId; //问卷-平台表,主键
		private String FNaireId; //问卷ID
		private String FNaireName; //卷问名称
		private String FToporgId; //顶级机构ID
		private String FServplatId; //平台编号
		private String FServplatName; //平台名称
		private String FOrgId; //机构编号
		private String FOrgName; //机构名称
		private String FOrgPath; //机构路径
		private String FParentorgId; //上级机构ID
		private Int32 FNoticeStatus; //通知状态(0:未通知;1:已通知)
		private String FPublishName; //发布人
		private DateTime FPublishTime; //发布时间
	
		public TabNaireNaireplatInfo() : base() {
		}
	
		public TabNaireNaireplatInfo(String fUnionId, String fNaireId,
				String fNaireName, String fToporgId, String fServplatId,
				String fServplatName, String fOrgId, String fOrgName,
				String fOrgPath, String fParentorgId, Int32 fNoticeStatus,
				String fPublishName, DateTime fPublishTime) : base() {
			FUnionId = fUnionId;
			FNaireId = fNaireId;
			FNaireName = fNaireName;
			FToporgId = fToporgId;
			FServplatId = fServplatId;
			FServplatName = fServplatName;
			FOrgId = fOrgId;
			FOrgName = fOrgName;
			FOrgPath = fOrgPath;
			FParentorgId = fParentorgId;
			FNoticeStatus = fNoticeStatus;
			FPublishName = fPublishName;
			FPublishTime = fPublishTime;
		}
	
		public String GetFUnionId() {
			return FUnionId;
		}
	
		public void SetFUnionId(String fUnionId) {
			FUnionId = fUnionId;
		}
	
		public String GetFNaireId() {
			return FNaireId;
		}
	
		public void SetFNaireId(String fNaireId) {
			FNaireId = fNaireId;
		}
	
		public String GetFNaireName() {
			return FNaireName;
		}
	
		public void SetFNaireName(String fNaireName) {
			FNaireName = fNaireName;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
		public String GetFOrgId() {
			return FOrgId;
		}
	
		public void SetFOrgId(String fOrgId) {
			FOrgId = fOrgId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFParentorgId() {
			return FParentorgId;
		}
	
		public void SetFParentorgId(String fParentorgId) {
			FParentorgId = fParentorgId;
		}
	
		public Int32 GetFNoticeStatus() {
			return FNoticeStatus;
		}
	
		public void SetFNoticeStatus(Int32 fNoticeStatus) {
			FNoticeStatus = fNoticeStatus;
		}
	
		public String GetFToporgId() {
			return FToporgId;
		}
	
		public void SetFToporgId(String fToporgId) {
			FToporgId = fToporgId;
		}
	
		public String GetFPublishName() {
			return FPublishName;
		}
	
		public void SetFPublishName(String fPublishName) {
			FPublishName = fPublishName;
		}
	
		public DateTime GetFPublishTime() {
			return FPublishTime;
		}
	
		public void SetFPublishTime(DateTime fPublishTime) {
			FPublishTime = fPublishTime;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
	}
}
