// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabRescenKnowledgeInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabRescenKnowledgeInfo {
	
		// Fields
	
		private String FKnowledgeId;
		private String FKnowledgeName;
		private String FKnowledgeDesc;
		private String FParentId;
		private Int32 FSortCode;
		private String FKnowledgePath;
		private Int32 FIfLeafnode;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabRescenKnowledgeInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabRescenKnowledgeInfo(String FKnowledgeId_0) {
			this.FKnowledgeId = FKnowledgeId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabRescenKnowledgeInfo(String FKnowledgeId_0, String FKnowledgeName_1,
				String FKnowledgeDesc_2, String FParentId_3, Int32 FSortCode_4,
				String FKnowledgePath_5, Int32 FIfLeafnode_6) {
			this.FKnowledgeId = FKnowledgeId_0;
			this.FKnowledgeName = FKnowledgeName_1;
			this.FKnowledgeDesc = FKnowledgeDesc_2;
			this.FParentId = FParentId_3;
			this.FSortCode = FSortCode_4;
			this.FKnowledgePath = FKnowledgePath_5;
			this.FIfLeafnode = FIfLeafnode_6;
		}
	
		// Property accessors
	
		public String GetFKnowledgeId() {
			return this.FKnowledgeId;
		}
	
		public void SetFKnowledgeId(String FKnowledgeId_0) {
			this.FKnowledgeId = FKnowledgeId_0;
		}
	
		public String GetFKnowledgeName() {
			return this.FKnowledgeName;
		}
	
		public void SetFKnowledgeName(String FKnowledgeName_0) {
			this.FKnowledgeName = FKnowledgeName_0;
		}
	
		public String GetFKnowledgeDesc() {
			return this.FKnowledgeDesc;
		}
	
		public void SetFKnowledgeDesc(String FKnowledgeDesc_0) {
			this.FKnowledgeDesc = FKnowledgeDesc_0;
		}
	
		public String GetFParentId() {
			return this.FParentId;
		}
	
		public void SetFParentId(String FParentId_0) {
			this.FParentId = FParentId_0;
		}
	
		public Int32 GetFSortCode() {
			return this.FSortCode;
		}
	
		public void SetFSortCode(Int32 FSortCode_0) {
			this.FSortCode = FSortCode_0;
		}
	
		public String GetFKnowledgePath() {
			return this.FKnowledgePath;
		}
	
		public void SetFKnowledgePath(String FKnowledgePath_0) {
			this.FKnowledgePath = FKnowledgePath_0;
		}
	
		public Int32 GetFIfLeafnode() {
			return FIfLeafnode;
		}
	
		public void SetFIfLeafnode(Int32 fIfLeafnode) {
			FIfLeafnode = fIfLeafnode;
		}
	
	}}
