// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// 任务处理结果的dto
	/// </summary>
	///
	[Serializable]
	/* @SuppressWarnings("serial")*/
	public class TabSysJoblogInfo {
	
		private String FJoblogId;
		private DateTime FStartTime;
		private DateTime FEndTime;
		private String FSysuserId;
		private DateTime FCreateTime;
		private String FSubject;
		private String FJobClass;
		private Int32 FIfSuccess;
		private String FJobMessages;
		private String FResultFile;
		private Int32 FJobType;
		private String FJobParam;
	
		public TabSysJoblogInfo() {
		}
	
		public TabSysJoblogInfo(String fJoblogId) {
			FJoblogId = fJoblogId;
		}
	
		
		/// <param name="fJoblogId"></param>
		/// <param name="fStartTime"></param>
		/// <param name="fEndTime"></param>
		/// <param name="fSysuserId"></param>
		/// <param name="fCreateTime"></param>
		/// <param name="fSubject"></param>
		/// <param name="fJobClass"></param>
		/// <param name="fIfSuccess"></param>
		/// <param name="fJobMessages"></param>
		/// <param name="fResultFile"></param>
		public TabSysJoblogInfo(String fJoblogId, DateTime fStartTime, DateTime fEndTime,
				String fSysuserId, DateTime fCreateTime, String fSubject,
				String fJobClass, Int32 fIfSuccess, String fJobMessages,
				String fResultFile, int fJobType, String fJobParam) : base() {
			FJoblogId = fJoblogId;
			FStartTime = fStartTime;
			FEndTime = fEndTime;
			FSysuserId = fSysuserId;
			FCreateTime = fCreateTime;
			FSubject = fSubject;
			FJobClass = fJobClass;
			FIfSuccess = fIfSuccess;
			FJobMessages = fJobMessages;
			FResultFile = fResultFile;
			FJobType = fJobType;
			FJobParam = fJobParam;
		}
	
		public String GetFJoblogId() {
			return FJoblogId;
		}
	
		public void SetFJoblogId(String fJoblogId) {
			FJoblogId = fJoblogId;
		}
	
		public DateTime GetFStartTime() {
			return FStartTime;
		}
	
		public void SetFStartTime(DateTime fStartTime) {
			FStartTime = fStartTime;
		}
	
		public DateTime GetFEndTime() {
			return FEndTime;
		}
	
		public void SetFEndTime(DateTime fEndTime) {
			FEndTime = fEndTime;
		}
	
		public String GetFSysuserId() {
			return FSysuserId;
		}
	
		public void SetFSysuserId(String fSysuserId) {
			FSysuserId = fSysuserId;
		}
	
		public DateTime GetFCreateTime() {
			return FCreateTime;
		}
	
		public void SetFCreateTime(DateTime fCreateTime) {
			FCreateTime = fCreateTime;
		}
	
		public String GetFSubject() {
			return FSubject;
		}
	
		public void SetFSubject(String fSubject) {
			FSubject = fSubject;
		}
	
		public String GetFJobClass() {
			return FJobClass;
		}
	
		public void SetFJobClass(String fJobClass) {
			FJobClass = fJobClass;
		}
	
		public Int32 GetFIfSuccess() {
			return FIfSuccess;
		}
	
		public void SetFIfSuccess(Int32 fIfSuccess) {
			FIfSuccess = fIfSuccess;
		}
	
		public String GetFJobMessages() {
			return FJobMessages;
		}
	
		public void SetFJobMessages(String fJobMessages) {
			FJobMessages = fJobMessages;
		}
	
		public String GetFResultFile() {
			return FResultFile;
		}
	
		public void SetFResultFile(String fResultFile) {
			FResultFile = fResultFile;
		}
	
		public Int32 GetFJobType() {
			return FJobType;
		}
	
		public void SetFJobType(Int32 fJobType) {
			FJobType = fJobType;
		}
	
		public String GetFJobParam() {
			return FJobParam;
		}
	
		public void SetFJobParam(String fJobParam) {
			FJobParam = fJobParam;
		}
	
	}
}
