// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabSysUserlogInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	/* @SuppressWarnings("serial")*/
	public class TabSysUserlogInfo {
	
		// Fields
	
		private String FUserlogId;
		private String FUserId;
		private String FUserName;
		private String FOrgId;
		private String FOrgName;
		private String FServplatId;
		private String FServplatName;
		private String FOpertypeId;
		private String FObjectName;
		private String FOperUrl;
		private String FIpAddress;
		private String FLogDetail;
		private DateTime FOperTime;
		private String FOperResult;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabSysUserlogInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabSysUserlogInfo(String FUserlogId_0) {
			this.FUserlogId = FUserlogId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabSysUserlogInfo(String FUserlogId_0, String FUserId_1,
				String FUserName_2, String FOrgId_3, String FServplatId_4,
				String FOpertypeId_5, String FObjectName_6, String FOperUrl_7,
				String FIpAddress_8, String FLogDetail_9, DateTime FOperTime_10,
				String FOperResult_11) {
			this.FUserlogId = FUserlogId_0;
			this.FUserId = FUserId_1;
			this.FUserName = FUserName_2;
			this.FOrgId = FOrgId_3;
			this.FServplatId = FServplatId_4;
			this.FOpertypeId = FOpertypeId_5;
			this.FObjectName = FObjectName_6;
			this.FOperUrl = FOperUrl_7;
			this.FIpAddress = FIpAddress_8;
			this.FLogDetail = FLogDetail_9;
			this.FOperTime = FOperTime_10;
			this.FOperResult = FOperResult_11;
		}
	
		// Property accessors
	
		public String GetFUserlogId() {
			return this.FUserlogId;
		}
	
		public void SetFUserlogId(String FUserlogId_0) {
			this.FUserlogId = FUserlogId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public String GetFOpertypeId() {
			return this.FOpertypeId;
		}
	
		public void SetFOpertypeId(String FOpertypeId_0) {
			this.FOpertypeId = FOpertypeId_0;
		}
	
		public String GetFObjectName() {
			return this.FObjectName;
		}
	
		public void SetFObjectName(String FObjectName_0) {
			this.FObjectName = FObjectName_0;
		}
	
		public String GetFOperUrl() {
			return this.FOperUrl;
		}
	
		public void SetFOperUrl(String FOperUrl_0) {
			this.FOperUrl = FOperUrl_0;
		}
	
		public String GetFIpAddress() {
			return this.FIpAddress;
		}
	
		public void SetFIpAddress(String FIpAddress_0) {
			this.FIpAddress = FIpAddress_0;
		}
	
		public String GetFLogDetail() {
			return this.FLogDetail;
		}
	
		public void SetFLogDetail(String FLogDetail_0) {
			this.FLogDetail = FLogDetail_0;
		}
	
		public DateTime GetFOperTime() {
			return this.FOperTime;
		}
	
		public void SetFOperTime(DateTime FOperTime_0) {
			this.FOperTime = FOperTime_0;
		}
	
		public String GetFOperResult() {
			return this.FOperResult;
		}
	
		public void SetFOperResult(String FOperResult_0) {
			this.FOperResult = FOperResult_0;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
	}}
