// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabUcenterUserexamRecord entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabUcenterUserexamRecord {
	
		// Fields
	
		private String FRecordId;
		private String FUserexamId;
		private String FPlanexamId;
		private String FUserId;
		private String FOrgId;
		private String FServplatId;
		private String FOrgName;
		private String FServplatName;
		private String FUserName;
		private String FPlanId;
		private String FPlanName;
		private String FExamId;
		private String FExamName;
		private Int32 FExamType;
		private DateTime FBgexamTime;
		private DateTime FEdexamTime;
		private Int32 FExamDuration;
		private Double FPassScores;
		private Double FExamScores;
		private String FExamResult;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabUcenterUserexamRecord() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabUcenterUserexamRecord(String FRecordId_0) {
			this.FRecordId = FRecordId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabUcenterUserexamRecord(String FRecordId_0, String FUserexamId_1,
				String FPlanexamId_2, String FUserId_3, String FOrgId_4,
				String FServplatId_5, String FOrgName_6, String FServplatName_7,
				String FUserName_8, String FPlanId_9, String FPlanName_10, String FExamId_11,
				String FExamName_12, Int32 FExamType_13, DateTime FBgexamTime_14,
				DateTime FEdexamTime_15, Int32 FExamDuration_16, Double FPassScores_17,
				Double FExamScores_18, String FExamResult_19) {
			this.FRecordId = FRecordId_0;
			this.FUserexamId = FUserexamId_1;
			this.FPlanexamId = FPlanexamId_2;
			this.FUserId = FUserId_3;
			this.FOrgId = FOrgId_4;
			this.FServplatId = FServplatId_5;
			this.FOrgName = FOrgName_6;
			this.FServplatName = FServplatName_7;
			this.FUserName = FUserName_8;
			this.FPlanId = FPlanId_9;
			this.FPlanName = FPlanName_10;
			this.FExamId = FExamId_11;
			this.FExamName = FExamName_12;
			this.FExamType = FExamType_13;
			this.FBgexamTime = FBgexamTime_14;
			this.FEdexamTime = FEdexamTime_15;
			this.FExamDuration = FExamDuration_16;
			this.FPassScores = FPassScores_17;
			this.FExamScores = FExamScores_18;
			this.FExamResult = FExamResult_19;
		}
	
		// Property accessors
	
		public String GetFRecordId() {
			return this.FRecordId;
		}
	
		public void SetFRecordId(String FRecordId_0) {
			this.FRecordId = FRecordId_0;
		}
	
		public String GetFUserexamId() {
			return this.FUserexamId;
		}
	
		public void SetFUserexamId(String FUserexamId_0) {
			this.FUserexamId = FUserexamId_0;
		}
	
		public String GetFPlanexamId() {
			return this.FPlanexamId;
		}
	
		public void SetFPlanexamId(String FPlanexamId_0) {
			this.FPlanexamId = FPlanexamId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public String GetFOrgName() {
			return this.FOrgName;
		}
	
		public void SetFOrgName(String FOrgName_0) {
			this.FOrgName = FOrgName_0;
		}
	
		public String GetFServplatName() {
			return this.FServplatName;
		}
	
		public void SetFServplatName(String FServplatName_0) {
			this.FServplatName = FServplatName_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFPlanName() {
			return this.FPlanName;
		}
	
		public void SetFPlanName(String FPlanName_0) {
			this.FPlanName = FPlanName_0;
		}
	
		public String GetFExamId() {
			return this.FExamId;
		}
	
		public void SetFExamId(String FExamId_0) {
			this.FExamId = FExamId_0;
		}
	
		public String GetFExamName() {
			return this.FExamName;
		}
	
		public void SetFExamName(String FExamName_0) {
			this.FExamName = FExamName_0;
		}
	
		public Int32 GetFExamType() {
			return this.FExamType;
		}
	
		public void SetFExamType(Int32 FExamType_0) {
			this.FExamType = FExamType_0;
		}
	
		public DateTime GetFBgexamTime() {
			return this.FBgexamTime;
		}
	
		public void SetFBgexamTime(DateTime FBgexamTime_0) {
			this.FBgexamTime = FBgexamTime_0;
		}
	
		public DateTime GetFEdexamTime() {
			return this.FEdexamTime;
		}
	
		public void SetFEdexamTime(DateTime FEdexamTime_0) {
			this.FEdexamTime = FEdexamTime_0;
		}
	
		public Int32 GetFExamDuration() {
			return FExamDuration;
		}
	
		public void SetFExamDuration(Int32 fExamDuration) {
			FExamDuration = fExamDuration;
		}
	
		public Double GetFPassScores() {
			return this.FPassScores;
		}
	
		public void SetFPassScores(Double FPassScores_0) {
			this.FPassScores = FPassScores_0;
		}
	
		public Double GetFExamScores() {
			return this.FExamScores;
		}
	
		public void SetFExamScores(Double FExamScores_0) {
			this.FExamScores = FExamScores_0;
		}
	
		public String GetFExamResult() {
			return this.FExamResult;
		}
	
		public void SetFExamResult(String FExamResult_0) {
			this.FExamResult = FExamResult_0;
		}
	
	}}
