// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabUcenterPapersInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	/* @SuppressWarnings("serial")*/
	public class TabUcenterPapersInfo {
	
		// Fields
	
		private String FUserpapersId;
		private String FUserexamId;
		private String FExampaperId;
		private String FUserId;
		private String FRecordId;
		private String FUserName;
		private String FOrgId;
		private String FOrgName;
		private String FServplatId;
		private String FServplatName;
		private String FExamId;
		private String FExamName;
		private DateTime FAnswerTime;
		private String FQuestionId;
		private String FQtypeId;
		private Int32 FSortCode;
		private String FQuestionInfo;
		private Int32 FQuestionMark;
		private String FUserAnswer;
		private String FTrueAnswer;
		private String FChoiceSort;
		private Double FQuestionScore;
		private Int32 FCheckResult;
		private Double FCheckScore;
		private String FCheckComment;
		private DateTime FCheckTime;
		private String FAnswerUrl;
	
		private String userAnswerFileName;//´Ë×Ö¶Î²»´æ¿â
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabUcenterPapersInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabUcenterPapersInfo(String FUserpapersId_0) {
			this.FUserpapersId = FUserpapersId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabUcenterPapersInfo(String FUserpapersId_0, String FUserexamId_1,
				String FExampaperId_2, String FUserId_3, String FRecordId_4,
				String FUserName_5, String FOrgId_6, String FOrgName_7,
				String FServplatId_8, String FServplatName_9, String FExamId_10,
				String FExamName_11, DateTime FAnswerTime_12, String FQuestionId_13,
				String FQtypeId_14, Int32 FSortCode_15, String FQuestionInfo_16,
				Int32 FQuestionMark_17, String FUserAnswer_18, String FTrueAnswer_19,
				String FChoiceSort_20, Double FQuestionScore_21, Int32 FCheckResult_22,
				Double FCheckScore_23, String FCheckComment_24) {
			this.FUserpapersId = FUserpapersId_0;
			this.FUserexamId = FUserexamId_1;
			this.FExampaperId = FExampaperId_2;
			this.FUserId = FUserId_3;
			this.FRecordId = FRecordId_4;
			this.FUserName = FUserName_5;
			this.FOrgId = FOrgId_6;
			this.FOrgName = FOrgName_7;
			this.FServplatId = FServplatId_8;
			this.FServplatName = FServplatName_9;
			this.FExamId = FExamId_10;
			this.FExamName = FExamName_11;
			this.FAnswerTime = FAnswerTime_12;
			this.FQuestionId = FQuestionId_13;
			this.FQtypeId = FQtypeId_14;
			this.FSortCode = FSortCode_15;
			this.FQuestionInfo = FQuestionInfo_16;
			this.FQuestionMark = FQuestionMark_17;
			this.FUserAnswer = FUserAnswer_18;
			this.FTrueAnswer = FTrueAnswer_19;
			this.FChoiceSort = FChoiceSort_20;
			this.FQuestionScore = FQuestionScore_21;
			this.FCheckResult = FCheckResult_22;
			this.FCheckScore = FCheckScore_23;
			this.FCheckComment = FCheckComment_24;
		}
	
		// Property accessors
	
		public String GetFUserpapersId() {
			return this.FUserpapersId;
		}
	
		public void SetFUserpapersId(String FUserpapersId_0) {
			this.FUserpapersId = FUserpapersId_0;
		}
	
		public String GetFUserexamId() {
			return this.FUserexamId;
		}
	
		public void SetFUserexamId(String FUserexamId_0) {
			this.FUserexamId = FUserexamId_0;
		}
	
		public String GetFExampaperId() {
			return this.FExampaperId;
		}
	
		public void SetFExampaperId(String FExampaperId_0) {
			this.FExampaperId = FExampaperId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFRecordId() {
			return this.FRecordId;
		}
	
		public void SetFRecordId(String FRecordId_0) {
			this.FRecordId = FRecordId_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFOrgName() {
			return this.FOrgName;
		}
	
		public void SetFOrgName(String FOrgName_0) {
			this.FOrgName = FOrgName_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public String GetFServplatName() {
			return this.FServplatName;
		}
	
		public void SetFServplatName(String FServplatName_0) {
			this.FServplatName = FServplatName_0;
		}
	
		public String GetFExamId() {
			return this.FExamId;
		}
	
		public void SetFExamId(String FExamId_0) {
			this.FExamId = FExamId_0;
		}
	
		public String GetFExamName() {
			return this.FExamName;
		}
	
		public void SetFExamName(String FExamName_0) {
			this.FExamName = FExamName_0;
		}
	
		public DateTime GetFAnswerTime() {
			return this.FAnswerTime;
		}
	
		public void SetFAnswerTime(DateTime FAnswerTime_0) {
			this.FAnswerTime = FAnswerTime_0;
		}
	
		public String GetFQuestionId() {
			return this.FQuestionId;
		}
	
		public void SetFQuestionId(String FQuestionId_0) {
			this.FQuestionId = FQuestionId_0;
		}
	
		public String GetFQtypeId() {
			return this.FQtypeId;
		}
	
		public void SetFQtypeId(String FQtypeId_0) {
			this.FQtypeId = FQtypeId_0;
		}
	
		public Int32 GetFSortCode() {
			return this.FSortCode;
		}
	
		public void SetFSortCode(Int32 FSortCode_0) {
			this.FSortCode = FSortCode_0;
		}
	
		public String GetFQuestionInfo() {
			return this.FQuestionInfo;
		}
	
		public void SetFQuestionInfo(String FQuestionInfo_0) {
			this.FQuestionInfo = FQuestionInfo_0;
		}
	
		public Int32 GetFQuestionMark() {
			return FQuestionMark;
		}
	
		public void SetFQuestionMark(Int32 fQuestionMark) {
			FQuestionMark = fQuestionMark;
		}
	
		public String GetFUserAnswer() {
			return this.FUserAnswer;
		}
	
		public void SetFUserAnswer(String FUserAnswer_0) {
			this.FUserAnswer = FUserAnswer_0;
		}
	
		public String GetFTrueAnswer() {
			return this.FTrueAnswer;
		}
	
		public void SetFTrueAnswer(String FTrueAnswer_0) {
			this.FTrueAnswer = FTrueAnswer_0;
		}
	
		public String GetFChoiceSort() {
			return this.FChoiceSort;
		}
	
		public void SetFChoiceSort(String FChoiceSort_0) {
			this.FChoiceSort = FChoiceSort_0;
		}
	
		public Double GetFQuestionScore() {
			return this.FQuestionScore;
		}
	
		public void SetFQuestionScore(Double FQuestionScore_0) {
			this.FQuestionScore = FQuestionScore_0;
		}
	
		public Int32 GetFCheckResult() {
			return this.FCheckResult;
		}
	
		public void SetFCheckResult(Int32 FCheckResult_0) {
			this.FCheckResult = FCheckResult_0;
		}
	
		public Double GetFCheckScore() {
			return this.FCheckScore;
		}
	
		public void SetFCheckScore(Double FCheckScore_0) {
			this.FCheckScore = FCheckScore_0;
		}
	
		public String GetFCheckComment() {
			return this.FCheckComment;
		}
	
		public void SetFCheckComment(String FCheckComment_0) {
			this.FCheckComment = FCheckComment_0;
		}
	
		public DateTime GetFCheckTime() {
			return FCheckTime;
		}
	
		public void SetFCheckTime(DateTime fCheckTime) {
			FCheckTime = fCheckTime;
		}
	
		public String GetFAnswerUrl() {
			return FAnswerUrl;
		}
	
		public void SetFAnswerUrl(String fAnswerUrl) {
			FAnswerUrl = fAnswerUrl;
		}
	
		public String GetUserAnswerFileName() {
			return userAnswerFileName;
		}
	
		public void SetUserAnswerFileName(String userAnswerFileName_0) {
			this.userAnswerFileName = userAnswerFileName_0;
		}
	
	}}
