// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Exam.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabUcenterUserexamInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabUcenterUserexamInfo {
	
		// Fields
	
		private String FUserexamId;
		private String FPlanexamId;
		private String FUserId;
		private String FOrgId;
		private String FServplatId;
		private String FOrgName;
		private String FServplatName;
		private String FUserName;
		private String FPlanId;
		private String FPlanName;
		private String FExamId;
		private String FExamName;
		private Int32 FExamType;
		private DateTime FExamBegintime;
		private DateTime FExamEndtime;
		private Int32 FExamDuration;
		private DateTime FLastexamTime;
		private Double FPassScores;
		private Double FExamScores;
		private String FExamResult;
		private Int32 FActualRetest;
		private Int32 FRetestTimes;
		private Int32 FExamStatus;
		private String FRealname;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabUcenterUserexamInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabUcenterUserexamInfo(String FUserexamId_0) {
			this.FUserexamId = FUserexamId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabUcenterUserexamInfo(String FUserexamId_0, String FPlanexamId_1,
				String FUserId_2, String FOrgId_3, String FServplatId_4, String FOrgName_5,
				String FServplatName_6, String FUserName_7, String FPlanId_8,
				String FPlanName_9, String FExamId_10, String FExamName_11,
				Int32 FExamType_12, DateTime FExamBegintime_13, DateTime FExamEndtime_14,
				Int32 FExamDuration_15, DateTime FLastexamTime_16, Double FPassScores_17,
				Double FExamScores_18, String FExamResult_19, Int32 FActualRetest_20,
				Int32 FRetestTimes_21, Int32 FExamStatus_22, String FRealname_23) {
			this.FUserexamId = FUserexamId_0;
			this.FPlanexamId = FPlanexamId_1;
			this.FUserId = FUserId_2;
			this.FOrgId = FOrgId_3;
			this.FServplatId = FServplatId_4;
			this.FOrgName = FOrgName_5;
			this.FServplatName = FServplatName_6;
			this.FUserName = FUserName_7;
			this.FPlanId = FPlanId_8;
			this.FPlanName = FPlanName_9;
			this.FExamId = FExamId_10;
			this.FExamName = FExamName_11;
			this.FExamType = FExamType_12;
			this.FExamBegintime = FExamBegintime_13;
			this.FExamEndtime = FExamEndtime_14;
			this.FExamDuration = FExamDuration_15;
			this.FLastexamTime = FLastexamTime_16;
			this.FPassScores = FPassScores_17;
			this.FExamScores = FExamScores_18;
			this.FExamResult = FExamResult_19;
			this.FActualRetest = FActualRetest_20;
			this.FRetestTimes = FRetestTimes_21;
			this.FExamStatus = FExamStatus_22;
			this.FRealname = FRealname_23;
		}
	
		// Property accessors
	
		public String GetFUserexamId() {
			return this.FUserexamId;
		}
	
		public String GetFRealname() {
			return FRealname;
		}
	
		public void SetFRealname(String fRealname) {
			FRealname = fRealname;
		}
	
		public void SetFUserexamId(String FUserexamId_0) {
			this.FUserexamId = FUserexamId_0;
		}
	
		public String GetFPlanexamId() {
			return this.FPlanexamId;
		}
	
		public void SetFPlanexamId(String FPlanexamId_0) {
			this.FPlanexamId = FPlanexamId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public String GetFOrgName() {
			return this.FOrgName;
		}
	
		public void SetFOrgName(String FOrgName_0) {
			this.FOrgName = FOrgName_0;
		}
	
		public String GetFServplatName() {
			return this.FServplatName;
		}
	
		public void SetFServplatName(String FServplatName_0) {
			this.FServplatName = FServplatName_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFPlanName() {
			return this.FPlanName;
		}
	
		public void SetFPlanName(String FPlanName_0) {
			this.FPlanName = FPlanName_0;
		}
	
		public String GetFExamId() {
			return this.FExamId;
		}
	
		public void SetFExamId(String FExamId_0) {
			this.FExamId = FExamId_0;
		}
	
		public String GetFExamName() {
			return this.FExamName;
		}
	
		public void SetFExamName(String FExamName_0) {
			this.FExamName = FExamName_0;
		}
	
		public Int32 GetFExamType() {
			return this.FExamType;
		}
	
		public void SetFExamType(Int32 FExamType_0) {
			this.FExamType = FExamType_0;
		}
	
		public DateTime GetFExamBegintime() {
			return this.FExamBegintime;
		}
	
		public void SetFExamBegintime(DateTime FExamBegintime_0) {
			this.FExamBegintime = FExamBegintime_0;
		}
	
		public DateTime GetFExamEndtime() {
			return this.FExamEndtime;
		}
	
		public void SetFExamEndtime(DateTime FExamEndtime_0) {
			this.FExamEndtime = FExamEndtime_0;
		}
	
		public Int32 GetFExamDuration() {
			return this.FExamDuration;
		}
	
		public void SetFExamDuration(Int32 FExamDuration_0) {
			this.FExamDuration = FExamDuration_0;
		}
	
		public DateTime GetFLastexamTime() {
			return this.FLastexamTime;
		}
	
		public void SetFLastexamTime(DateTime FLastexamTime_0) {
			this.FLastexamTime = FLastexamTime_0;
		}
	
		public Double GetFPassScores() {
			return this.FPassScores;
		}
	
		public void SetFPassScores(Double FPassScores_0) {
			this.FPassScores = FPassScores_0;
		}
	
		public Double GetFExamScores() {
			return this.FExamScores;
		}
	
		public void SetFExamScores(Double FExamScores_0) {
			this.FExamScores = FExamScores_0;
		}
	
		public String GetFExamResult() {
			return this.FExamResult;
		}
	
		public void SetFExamResult(String FExamResult_0) {
			this.FExamResult = FExamResult_0;
		}
	
		public Int32 GetFActualRetest() {
			return this.FActualRetest;
		}
	
		public void SetFActualRetest(Int32 FActualRetest_0) {
			this.FActualRetest = FActualRetest_0;
		}
	
		public Int32 GetFRetestTimes() {
			return this.FRetestTimes;
		}
	
		public void SetFRetestTimes(Int32 FRetestTimes_0) {
			this.FRetestTimes = FRetestTimes_0;
		}
	
		public Int32 GetFExamStatus() {
			return this.FExamStatus;
		}
	
		public void SetFExamStatus(Int32 FExamStatus_0) {
			this.FExamStatus = FExamStatus_0;
		}
	
	}}
