// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Passport.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabSysOrgInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	/* @SuppressWarnings("serial")*/
	public class TabSysOrgInfo {
	
		// Fields
	
		private String FOrgId;
		private String FOrgName;
		private String FParentId;
		private Int32 FSortCode;
		private String FOrgPath;
		private String FServplatId;
		private DateTime FCreateTime;
		private Int32 FOrgStatus;
		private String FOrgDesc;
		private Int32 FOrgType;
		private Int32 FIfLeaf;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabSysOrgInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabSysOrgInfo(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public TabSysOrgInfo(String fOrgId, String fOrgName, String fParentId,
				Int32 fSortCode, String fOrgPath, String fServplatId,
				DateTime fCreateTime, Int32 fOrgStatus, String fOrgDesc,
				Int32 fOrgType, Int32 fIfLeaf) : base() {
			FOrgId = fOrgId;
			FOrgName = fOrgName;
			FParentId = fParentId;
			FSortCode = fSortCode;
			FOrgPath = fOrgPath;
			FServplatId = fServplatId;
			FCreateTime = fCreateTime;
			FOrgStatus = fOrgStatus;
			FOrgDesc = fOrgDesc;
			FOrgType = fOrgType;
			FIfLeaf = fIfLeaf;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFOrgName() {
			return this.FOrgName;
		}
	
		public void SetFOrgName(String FOrgName_0) {
			this.FOrgName = FOrgName_0;
		}
	
		public String GetFParentId() {
			return this.FParentId;
		}
	
		public void SetFParentId(String FParentId_0) {
			this.FParentId = FParentId_0;
		}
	
		public Int32 GetFSortCode() {
			return this.FSortCode;
		}
	
		public void SetFSortCode(Int32 FSortCode_0) {
			this.FSortCode = FSortCode_0;
		}
	
		public String GetFOrgPath() {
			return this.FOrgPath;
		}
	
		public void SetFOrgPath(String FOrgPath_0) {
			this.FOrgPath = FOrgPath_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public DateTime GetFCreateTime() {
			return this.FCreateTime;
		}
	
		public void SetFCreateTime(DateTime FCreateTime_0) {
			this.FCreateTime = FCreateTime_0;
		}
	
		public Int32 GetFOrgStatus() {
			return this.FOrgStatus;
		}
	
		public void SetFOrgStatus(Int32 FOrgStatus_0) {
			this.FOrgStatus = FOrgStatus_0;
		}
	
		public String GetFOrgDesc() {
			return this.FOrgDesc;
		}
	
		public void SetFOrgDesc(String FOrgDesc_0) {
			this.FOrgDesc = FOrgDesc_0;
		}
	
		public Int32 GetFOrgType() {
			return FOrgType;
		}
	
		public void SetFOrgType(Int32 fOrgType) {
			FOrgType = fOrgType;
		}
	
		public Int32 GetFIfLeaf() {
			return FIfLeaf;
		}
	
		public void SetFIfLeaf(Int32 fIfLeaf) {
			FIfLeaf = fIfLeaf;
		}
	
	}}
