// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Shop.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabRescenCourseEntity entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	/* @SuppressWarnings("serial")*/
	public class TabRescenCourseEntity {
	
		// Fields
	
		private String FEntityId;
		private String FCourseId;
		private String FSupplierId;
		private String FSupplierName;
		private String FEntityDesc;
		private String FEntityName;
		private String FCourseVersion;
		private String FCourseblogoUrl;
		private String FCourseslogoUrl;
		private String FCourseUrl;
		private String FPlayerUrl;
		private String FCourseNumber;
		private String FTerminalType;
		private Int32 FVerifyStatus;
		private DateTime FCreateTime;
		private Double FCourseHours;
		private Double FCourseSizes;
		private Double FCostPrice;
		private Int32 FOpenFlag;//是否公开
		private Double FSplitPercent;//分账比例
		private Double FSplitReturn;//分账返还数
		private Double FSplitGet;//分账收取数
		private Int32 FSplitWay;//固定数 ,百分比
		private String FValidDate;//课件有效期
	
		public Double GetFSplitPercent() {
			return FSplitPercent;
		}
	
		public void SetFSplitPercent(Double fSplitPercent) {
			FSplitPercent = fSplitPercent;
		}
	
		public Double GetFSplitReturn() {
			return FSplitReturn;
		}
	
		public void SetFSplitReturn(Double fSplitReturn) {
			FSplitReturn = fSplitReturn;
		}
	
		public Double GetFSplitGet() {
			return FSplitGet;
		}
	
		public void SetFSplitGet(Double fSplitGet) {
			FSplitGet = fSplitGet;
		}
	
		public Int32 GetFSplitWay() {
			return FSplitWay;
		}
	
		public void SetFSplitWay(Int32 fSplitWay) {
			FSplitWay = fSplitWay;
		}
	
		// Constructors
	
		public Int32 GetFOpenFlag() {
			return FOpenFlag;
		}
	
		public void SetFOpenFlag(Int32 fOpenFlag) {
			FOpenFlag = fOpenFlag;
		}
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabRescenCourseEntity() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabRescenCourseEntity(String FEntityId_0) {
			this.FEntityId = FEntityId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabRescenCourseEntity(String FEntityId_0, String FCourseId_1,
				String FSupplierId_2, String FEntityDesc_3, String FEntityName_4,
				String FCourseVersion_5, String FCourseblogoUrl_6,
				String FCourseslogoUrl_7, String FCourseUrl_8, String FCourseNumber_9,
				String FTerminalType_10, Int32 FVerifyStatus_11, DateTime FCreateTime_12,
				String FSupplierName_13, Double FCourseHours_14, Double FCourseSizes_15,
				Double FCostPrice_16, Int32 FOpenFlag_17, Double FSplitPercent_18,
				Double FSplitReturn_19, Double FSplitGet_20, Int32 FSplitWay_21,
				String FValidDate_22) {
			this.FEntityId = FEntityId_0;
			this.FCourseId = FCourseId_1;
			this.FSupplierId = FSupplierId_2;
			this.FEntityDesc = FEntityDesc_3;
			this.FEntityName = FEntityName_4;
			this.FCourseVersion = FCourseVersion_5;
			this.FCourseblogoUrl = FCourseblogoUrl_6;
			this.FCourseslogoUrl = FCourseslogoUrl_7;
			this.FCourseUrl = FCourseUrl_8;
			this.FCourseNumber = FCourseNumber_9;
			this.FTerminalType = FTerminalType_10;
			this.FVerifyStatus = FVerifyStatus_11;
			this.FCreateTime = FCreateTime_12;
			this.FSupplierName = FSupplierName_13;
			this.FCourseHours = FCourseHours_14;
			this.FCourseSizes = FCourseSizes_15;
			this.FCostPrice = FCostPrice_16;
			this.FOpenFlag = FOpenFlag_17;
			this.FSplitPercent = FSplitPercent_18;
			this.FSplitReturn = FSplitReturn_19;
			this.FSplitGet = FSplitGet_20;
			this.FSplitWay = FSplitWay_21;
			this.FValidDate = FValidDate_22;
		}
	
		// Property accessors
	
		public String GetFEntityId() {
			return this.FEntityId;
		}
	
		public void SetFEntityId(String FEntityId_0) {
			this.FEntityId = FEntityId_0;
		}
	
		public String GetFCourseId() {
			return this.FCourseId;
		}
	
		public void SetFCourseId(String FCourseId_0) {
			this.FCourseId = FCourseId_0;
		}
	
		public String GetFSupplierId() {
			return this.FSupplierId;
		}
	
		public void SetFSupplierId(String FSupplierId_0) {
			this.FSupplierId = FSupplierId_0;
		}
	
		public String GetFEntityDesc() {
			return this.FEntityDesc;
		}
	
		public void SetFEntityDesc(String FEntityDesc_0) {
			this.FEntityDesc = FEntityDesc_0;
		}
	
		public String GetFEntityName() {
			return this.FEntityName;
		}
	
		public void SetFEntityName(String FEntityName_0) {
			this.FEntityName = FEntityName_0;
		}
	
		public String GetFCourseVersion() {
			return this.FCourseVersion;
		}
	
		public void SetFCourseVersion(String FCourseVersion_0) {
			this.FCourseVersion = FCourseVersion_0;
		}
	
		public String GetFCourseblogoUrl() {
			return this.FCourseblogoUrl;
		}
	
		public void SetFCourseblogoUrl(String FCourseblogoUrl_0) {
			this.FCourseblogoUrl = FCourseblogoUrl_0;
		}
	
		public String GetFCourseslogoUrl() {
			return this.FCourseslogoUrl;
		}
	
		public void SetFCourseslogoUrl(String FCourseslogoUrl_0) {
			this.FCourseslogoUrl = FCourseslogoUrl_0;
		}
	
		public String GetFCourseUrl() {
			return this.FCourseUrl;
		}
	
		public void SetFCourseUrl(String FCourseUrl_0) {
			this.FCourseUrl = FCourseUrl_0;
		}
	
		public String GetFCourseNumber() {
			return this.FCourseNumber;
		}
	
		public void SetFCourseNumber(String FCourseNumber_0) {
			this.FCourseNumber = FCourseNumber_0;
		}
	
		public String GetFTerminalType() {
			return this.FTerminalType;
		}
	
		public void SetFTerminalType(String FTerminalType_0) {
			this.FTerminalType = FTerminalType_0;
		}
	
		public String GetFPlayerUrl() {
			return FPlayerUrl;
		}
	
		public void SetFPlayerUrl(String fPlayerUrl) {
			FPlayerUrl = fPlayerUrl;
		}
	
		public Int32 GetFVerifyStatus() {
			return FVerifyStatus;
		}
	
		public void SetFVerifyStatus(Int32 fVerifyStatus) {
			FVerifyStatus = fVerifyStatus;
		}
	
		public DateTime GetFCreateTime() {
			return FCreateTime;
		}
	
		public void SetFCreateTime(DateTime fCreateTime) {
			FCreateTime = fCreateTime;
		}
	
		public String GetFSupplierName() {
			return FSupplierName;
		}
	
		public void SetFSupplierName(String fSupplierName) {
			FSupplierName = fSupplierName;
		}
	
		public Double GetFCourseHours() {
			return FCourseHours;
		}
	
		public void SetFCourseHours(Double fCourseHours) {
			FCourseHours = fCourseHours;
		}
	
		public Double GetFCourseSizes() {
			return FCourseSizes;
		}
	
		public void SetFCourseSizes(Double fCourseSizes) {
			FCourseSizes = fCourseSizes;
		}
	
		public Double GetFCostPrice() {
			return FCostPrice;
		}
	
		public void SetFCostPrice(Double fCostPrice) {
			if (fCostPrice != null) {
                fCostPrice = Math.Round(fCostPrice, 2); 
                //DecimalFormat df = new DecimalFormat("##.00");
                //fCostPrice = ((Double )Double.Parse(df.Format(fCostPrice),ILOG.J2CsMapping.Util.NumberFormatProvider.NumberFormat));
			}
			FCostPrice = fCostPrice;
		}
	
		public String GetFValidDate() {
			return FValidDate;
		}
	
		public void SetFValidDate(String fValidDate) {
			FValidDate = fValidDate;
		}
	
	}}
