// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Shop.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabRescenCourseInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	/* @SuppressWarnings("serial")*/
	public class TabRescenCourseInfo {
	
		// Fields
	
		private String FCourseId;
		private String FCourseName;
		private String FCourseNo;
		private String FParentId;
		private Int32 FSortCode;
		private String FCoursePath;
		private String FPreviewUrl;
		private String FCoursetypeId;
		private String FCourseformatId;
		private String FSupplierId;
		private String FSysuserId;
		private DateTime FCreateTime;
		private String FTeacherId;
		private String FTeacherName;// 这是后来加的
	
		private String FLevelId;
		private Int32 FChapterNums;
		private Double FCourseScores;
		private Double FCourseHours;
		private Double FStudyDuration;
		private Double FCoursePrice;
		private String FCourseDesc;
		private Int32 FVerifyStatus;
		private Int32 FUseStatus;
		private Int32 FIsSell;
		private String FFiletypeId;
		private String FCourseobjId;
		private String FCourseformId;
		private Double FDiscountPrice;
		private Int32 FPointsNums;
		private Double FPointsPrice;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabRescenCourseInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabRescenCourseInfo(String FCourseId_0) {
			this.FCourseId = FCourseId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public String GetFCourseId() {
			return this.FCourseId;
		}
	
		public TabRescenCourseInfo(String fCourseId, String fCourseName,
				String fCourseNo, String fParentId, Int32 fSortCode,
				String fCoursePath, String fPreviewUrl, String fCoursetypeId,
				String fCourseformatId, String fSupplierId, String fSysuserId,
				DateTime fCreateTime, String fTeacherId, String fTeacherName,
				String fLevelId, Int32 fChapterNums, Double fCourseScores,
				Double fCourseHours, Double fStudyDuration, Double fCoursePrice,
				String fCourseDesc, Int32 fVerifyStatus, Int32 fUseStatus,
				Int32 fIsSell, String fFiletypeId, String fCourseobjId,
				String fCourseformId, Double fDiscountPrice, Int32 fPointsNums,
				Double fPointsPrice) : base() {
			FCourseId = fCourseId;
			FCourseName = fCourseName;
			FCourseNo = fCourseNo;
			FParentId = fParentId;
			FSortCode = fSortCode;
			FCoursePath = fCoursePath;
			FPreviewUrl = fPreviewUrl;
			FCoursetypeId = fCoursetypeId;
			FCourseformatId = fCourseformatId;
			FSupplierId = fSupplierId;
			FSysuserId = fSysuserId;
			FCreateTime = fCreateTime;
			FTeacherId = fTeacherId;
			FTeacherName = fTeacherName;
			FLevelId = fLevelId;
			FChapterNums = fChapterNums;
			FCourseScores = fCourseScores;
			FCourseHours = fCourseHours;
			FStudyDuration = fStudyDuration;
			FCoursePrice = fCoursePrice;
			FCourseDesc = fCourseDesc;
			FVerifyStatus = fVerifyStatus;
			FUseStatus = fUseStatus;
			FIsSell = fIsSell;
			FFiletypeId = fFiletypeId;
			FCourseobjId = fCourseobjId;
			FCourseformId = fCourseformId;
			FDiscountPrice = fDiscountPrice;
			FPointsNums = fPointsNums;
			FPointsPrice = fPointsPrice;
		}
	
		public void SetFCourseId(String FCourseId_0) {
			this.FCourseId = FCourseId_0;
		}
	
		public String GetFCourseName() {
			return this.FCourseName;
		}
	
		public void SetFCourseName(String FCourseName_0) {
			this.FCourseName = FCourseName_0;
		}
	
		public String GetFCourseNo() {
			return this.FCourseNo;
		}
	
		public void SetFCourseNo(String FCourseNo_0) {
			this.FCourseNo = FCourseNo_0;
		}
	
		public String GetFParentId() {
			return this.FParentId;
		}
	
		public void SetFParentId(String FParentId_0) {
			this.FParentId = FParentId_0;
		}
	
		public Int32 GetFSortCode() {
			return this.FSortCode;
		}
	
		public void SetFSortCode(Int32 FSortCode_0) {
			this.FSortCode = FSortCode_0;
		}
	
		public String GetFCoursePath() {
			return this.FCoursePath;
		}
	
		public void SetFCoursePath(String FCoursePath_0) {
			this.FCoursePath = FCoursePath_0;
		}
	
		public String GetFCoursetypeId() {
			return this.FCoursetypeId;
		}
	
		public void SetFCoursetypeId(String FCoursetypeId_0) {
			this.FCoursetypeId = FCoursetypeId_0;
		}
	
		public String GetFCourseformatId() {
			return this.FCourseformatId;
		}
	
		public void SetFCourseformatId(String FCourseformatId_0) {
			this.FCourseformatId = FCourseformatId_0;
		}
	
		public String GetFSupplierId() {
			return this.FSupplierId;
		}
	
		public void SetFSupplierId(String FSupplierId_0) {
			this.FSupplierId = FSupplierId_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public DateTime GetFCreateTime() {
			return this.FCreateTime;
		}
	
		public void SetFCreateTime(DateTime FCreateTime_0) {
			this.FCreateTime = FCreateTime_0;
		}
	
		public String GetFLevelId() {
			return this.FLevelId;
		}
	
		public void SetFLevelId(String FLevelId_0) {
			this.FLevelId = FLevelId_0;
		}
	
		public Int32 GetFChapterNums() {
			return this.FChapterNums;
		}
	
		public void SetFChapterNums(Int32 FChapterNums_0) {
			this.FChapterNums = FChapterNums_0;
		}
	
		public Double GetFStudyDuration() {
			return this.FStudyDuration;
		}
	
		public void SetFStudyDuration(Double FStudyDuration_0) {
			this.FStudyDuration = FStudyDuration_0;
		}
	
		public Double GetFCoursePrice() {
			return this.FCoursePrice;
		}
	
		public void SetFCoursePrice(Double FCoursePrice_0) {
			this.FCoursePrice = FCoursePrice_0;
		}
	
		public String GetFCourseDesc() {
			return this.FCourseDesc;
		}
	
		public void SetFCourseDesc(String FCourseDesc_0) {
			this.FCourseDesc = FCourseDesc_0;
		}
	
		public Int32 GetFVerifyStatus() {
			return this.FVerifyStatus;
		}
	
		public void SetFVerifyStatus(Int32 FVerifyStatus_0) {
			this.FVerifyStatus = FVerifyStatus_0;
		}
	
		public Int32 GetFUseStatus() {
			return this.FUseStatus;
		}
	
		public void SetFUseStatus(Int32 FUseStatus_0) {
			this.FUseStatus = FUseStatus_0;
		}
	
		public Int32 GetFIsSell() {
			return this.FIsSell;
		}
	
		public void SetFIsSell(Int32 FIsSell_0) {
			this.FIsSell = FIsSell_0;
		}
	
		public String GetFFiletypeId() {
			return FFiletypeId;
		}
	
		public void SetFFiletypeId(String fFiletypeId) {
			FFiletypeId = fFiletypeId;
		}
	
		public String GetFCourseobjId() {
			return FCourseobjId;
		}
	
		public void SetFCourseobjId(String fCourseobjId) {
			FCourseobjId = fCourseobjId;
		}
	
		public String GetFCourseformId() {
			return FCourseformId;
		}
	
		public void SetFCourseformId(String fCourseformId) {
			FCourseformId = fCourseformId;
		}
	
		public Double GetFCourseScores() {
			return FCourseScores;
		}
	
		public void SetFCourseScores(Double fCourseScores) {
			FCourseScores = fCourseScores;
		}
	
		public Double GetFCourseHours() {
			return FCourseHours;
		}
	
		public void SetFCourseHours(Double fCourseHours) {
			FCourseHours = fCourseHours;
		}
	
		public Double GetFDiscountPrice() {
			return FDiscountPrice;
		}
	
		public void SetFDiscountPrice(Double fDiscountPrice) {
			FDiscountPrice = fDiscountPrice;
		}
	
		public Int32 GetFPointsNums() {
			return FPointsNums;
		}
	
		public void SetFPointsNums(Int32 fPointsNums) {
			FPointsNums = fPointsNums;
		}
	
		public Double GetFPointsPrice() {
			return FPointsPrice;
		}
	
		public void SetFPointsPrice(Double fPointsPrice) {
			FPointsPrice = fPointsPrice;
		}
	
		public String GetFTeacherId() {
			return FTeacherId;
		}
	
		public void SetFTeacherId(String fTeacherId) {
			FTeacherId = fTeacherId;
		}
	
		public String GetFPreviewUrl() {
			return FPreviewUrl;
		}
	
		public void SetFPreviewUrl(String fPreviewUrl) {
			FPreviewUrl = fPreviewUrl;
		}
	
		public String GetFTeacherName() {
			return FTeacherName;
		}
	
		public void SetFTeacherName(String fTeacherName) {
			FTeacherName = fTeacherName;
		}
	}}
