// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Shop.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabRescenTecherInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	/* @SuppressWarnings("serial")*/
	public class TabRescenTecherInfo {
	
		// Fields
	
		private String FTeacherId;
		private String FLevelId;
		private String FTeacherName;
		private String FTeacherDesc;
		private String FTeacherFeature;
		private String FSex;
		private String FProfession;
		private String FHeadUrl;
		private String FEmail;
		private String FOfficePhone;
		private String FMobilePhone;
		private String FOfficeName;
		private String FOfficeAddress;
		private Int32 FIfHot;
		private String FServplatId;
		private String FServplatName;
		private String FServplatIds; //教师对应的平台
		private String FServplatNames;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabRescenTecherInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabRescenTecherInfo(String FTeacherId_0) {
			this.FTeacherId = FTeacherId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabRescenTecherInfo(String FTeacherId_0, String FLevelId_1,
				String FTeacherName_2, String FTeacherDesc_3, String FTeacherFeature_4,
				String FSex_5, String FProfession_6, String FHeadUrl_7, String FEmail_8,
				String FOfficePhone_9, String FMobilePhone_10, String FOfficeName_11,
				String FOfficeAddress_12, Int32 FIfHot_13, String FServplatId_14,
				String FServplatName_15) {
			this.FTeacherId = FTeacherId_0;
			this.FLevelId = FLevelId_1;
			this.FTeacherName = FTeacherName_2;
			this.FTeacherDesc = FTeacherDesc_3;
			this.FTeacherFeature = FTeacherFeature_4;
			this.FSex = FSex_5;
			this.FProfession = FProfession_6;
			this.FHeadUrl = FHeadUrl_7;
			this.FEmail = FEmail_8;
			this.FOfficePhone = FOfficePhone_9;
			this.FMobilePhone = FMobilePhone_10;
			this.FOfficeName = FOfficeName_11;
			this.FOfficeAddress = FOfficeAddress_12;
			this.FIfHot = FIfHot_13;
			this.FServplatId = FServplatId_14;
			this.FServplatName = FServplatName_15;
		}
	
		// Property accessors
	
		public String GetFTeacherId() {
			return this.FTeacherId;
		}
	
		public void SetFTeacherId(String FTeacherId_0) {
			this.FTeacherId = FTeacherId_0;
		}
	
		public String GetFLevelId() {
			return this.FLevelId;
		}
	
		public void SetFLevelId(String FLevelId_0) {
			this.FLevelId = FLevelId_0;
		}
	
		public String GetFTeacherName() {
			return this.FTeacherName;
		}
	
		public void SetFTeacherName(String FTeacherName_0) {
			this.FTeacherName = FTeacherName_0;
		}
	
		public String GetFTeacherDesc() {
			return this.FTeacherDesc;
		}
	
		public void SetFTeacherDesc(String FTeacherDesc_0) {
			this.FTeacherDesc = FTeacherDesc_0;
		}
	
		public String GetFTeacherFeature() {
			return this.FTeacherFeature;
		}
	
		public void SetFTeacherFeature(String FTeacherFeature_0) {
			this.FTeacherFeature = FTeacherFeature_0;
		}
	
		public String GetFSex() {
			return this.FSex;
		}
	
		public void SetFSex(String FSex_0) {
			this.FSex = FSex_0;
		}
	
		public String GetFProfession() {
			return this.FProfession;
		}
	
		public void SetFProfession(String FProfession_0) {
			this.FProfession = FProfession_0;
		}
	
		public String GetFHeadUrl() {
			return this.FHeadUrl;
		}
	
		public void SetFHeadUrl(String FHeadUrl_0) {
			this.FHeadUrl = FHeadUrl_0;
		}
	
		public String GetFEmail() {
			return this.FEmail;
		}
	
		public void SetFEmail(String FEmail_0) {
			this.FEmail = FEmail_0;
		}
	
		public String GetFOfficePhone() {
			return this.FOfficePhone;
		}
	
		public void SetFOfficePhone(String FOfficePhone_0) {
			this.FOfficePhone = FOfficePhone_0;
		}
	
		public String GetFMobilePhone() {
			return this.FMobilePhone;
		}
	
		public void SetFMobilePhone(String FMobilePhone_0) {
			this.FMobilePhone = FMobilePhone_0;
		}
	
		public String GetFOfficeName() {
			return this.FOfficeName;
		}
	
		public void SetFOfficeName(String FOfficeName_0) {
			this.FOfficeName = FOfficeName_0;
		}
	
		public String GetFOfficeAddress() {
			return this.FOfficeAddress;
		}
	
		public void SetFOfficeAddress(String FOfficeAddress_0) {
			this.FOfficeAddress = FOfficeAddress_0;
		}
	
		public Int32 GetFIfHot() {
			return this.FIfHot;
		}
	
		public void SetFIfHot(Int32 FIfHot_0) {
			this.FIfHot = FIfHot_0;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
		public String GetFServplatIds() {
			return FServplatIds;
		}
	
		public void SetFServplatIds(String fServplatIds) {
			FServplatIds = fServplatIds;
		}
	
		public String GetFServplatNames() {
			return FServplatNames;
		}
	
		public void SetFServplatNames(String fServplatNames) {
			FServplatNames = fServplatNames;
		}
	
	}}
