// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Shop.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/* @SuppressWarnings("serial")*/
	[Serializable]
	public class TabShopOrderDetail {
		//ok 3.16 校对
		private String FOrderdetailId; //	支付明细信息编号	varchar(64)
		private String FOrderId; //	订单信息编号	varchar(64)
		private String FGoodsId; //	商品编号	varchar(64)
		private String FGoodstypeId; //  商品分类信息ID
		private String FUserId; //	用户编号	varchar(64)
		private String FUserName; //	学员用户名	varchar(100)
		private String FServplatId; //  学员所属服务平台ID
		private DateTime FOrderTime; //	支付时间	datetime
		private String FOrderNo; //	订单编号	varchar(100)
		private Double FOrderMoney; //  f_order_money
		private String FDealNo; //	交易号	varchar(100)
		private String FPlanId; //	所属计划编号	varchar(64)
		private String FPlanNo; //  培训计划编号
		private String FSupplierId; //	课件供应商ID	varchar(64)
		private String FGoodsFilter; //	商品筛选类型ID，对于课件包可以是多个，用;分隔	varchar(500)
		private String FGoodslogoUrl; //	商品封面logo	varchar(200)
		private String FGoodsName; //	商品名称	varchar(100)
		private String FGoodsDesc; //	商品描述	varchar(200)
		private String FPaytypeId; //	支付方式ID	varchar(64)
		private String FPaytypeName; //	支付方式名称	varchar(50)
		private DateTime FPayTime;
		private Double FPayPrice; //	商品销售价格	numeric(8,2)
		private Double FPayPoints; //	商品销售积分	numeric(8,2)
		private Int32 FGoodsNums; //    int(11) DEFAULT NULL COMMENT '商品数量',
		private Double FCostPrice; // 商品运营成本
		private Int32 FOrderStatus; //	支付状态	integer
		private Double FHandingFee; //	手续费	numeric(8,2)
		private Double FSplitMoney; //	分账金额	numeric(8,2)
		private Int32 FPointsStatus; //	积分状态，默认为不允许用积分。0：不允许积分；1：允许积分	integer
		private String FOrgPath;
		private Int32 FOrderType;
		private String FAuthorizerId; //授权人ID
		private String FAuthorizerName; //授权人名称
		private String FAuthorizerOrg; //授权人所属地区
		private String FAuthorizerOrgName; //授权人所属地区名称
		private String FAuthorizerOrgPath; //授权人组织路径
		private String FOffice; //工作单位
		private String FIdcard; //身份证号
		private Double FClassHours; //学时
		private Double FClassScores;//学分
	
		private Int32 goodsState;//该商品的状态（与数据库无关）
	
		public TabShopOrderDetail() {
		}
	
		public String GetFOrderdetailId() {
			return FOrderdetailId;
		}
	
		public void SetFOrderdetailId(String fOrderdetailId) {
			FOrderdetailId = fOrderdetailId;
		}
	
		public String GetFOrderId() {
			return FOrderId;
		}
	
		public void SetFOrderId(String fOrderId) {
			FOrderId = fOrderId;
		}
	
		public String GetFGoodsId() {
			return FGoodsId;
		}
	
		public void SetFGoodsId(String fGoodsId) {
			FGoodsId = fGoodsId;
		}
	
		public String GetFGoodstypeId() {
			return FGoodstypeId;
		}
	
		public void SetFGoodstypeId(String fGoodstypeId) {
			FGoodstypeId = fGoodstypeId;
		}
	
		public String GetFUserId() {
			return FUserId;
		}
	
		public void SetFUserId(String fUserId) {
			FUserId = fUserId;
		}
	
		public String GetFUserName() {
			return FUserName;
		}
	
		public void SetFUserName(String fUserName) {
			FUserName = fUserName;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public DateTime GetFOrderTime() {
			return FOrderTime;
		}
	
		public void SetFOrderTime(DateTime fOrderTime) {
			FOrderTime = fOrderTime;
		}
	
		public String GetFOrderNo() {
			return FOrderNo;
		}
	
		public void SetFOrderNo(String fOrderNo) {
			FOrderNo = fOrderNo;
		}
	
		public Double GetFOrderMoney() {
			return FOrderMoney;
		}
	
		public void SetFOrderMoney(Double fOrderMoney) {
			FOrderMoney = fOrderMoney;
		}
	
		public String GetFDealNo() {
			return FDealNo;
		}
	
		public void SetFDealNo(String fDealNo) {
			FDealNo = fDealNo;
		}
	
		public String GetFPlanId() {
			return FPlanId;
		}
	
		public void SetFPlanId(String fPlanId) {
			FPlanId = fPlanId;
		}
	
		public String GetFPlanNo() {
			return FPlanNo;
		}
	
		public void SetFPlanNo(String fPlanNo) {
			FPlanNo = fPlanNo;
		}
	
		public String GetFSupplierId() {
			return FSupplierId;
		}
	
		public void SetFSupplierId(String fSupplierId) {
			FSupplierId = fSupplierId;
		}
	
		public String GetFGoodsFilter() {
			return FGoodsFilter;
		}
	
		public void SetFGoodsFilter(String fGoodsFilter) {
			FGoodsFilter = fGoodsFilter;
		}
	
		public String GetFGoodslogoUrl() {
			return FGoodslogoUrl;
		}
	
		public void SetFGoodslogoUrl(String fGoodslogoUrl) {
			FGoodslogoUrl = fGoodslogoUrl;
		}
	
		public String GetFGoodsName() {
			return FGoodsName;
		}
	
		public void SetFGoodsName(String fGoodsName) {
			FGoodsName = fGoodsName;
		}
	
		public String GetFGoodsDesc() {
			return FGoodsDesc;
		}
	
		public void SetFGoodsDesc(String fGoodsDesc) {
			FGoodsDesc = fGoodsDesc;
		}
	
		public String GetFPaytypeId() {
			return FPaytypeId;
		}
	
		public void SetFPaytypeId(String fPaytypeId) {
			FPaytypeId = fPaytypeId;
		}
	
		public String GetFPaytypeName() {
			return FPaytypeName;
		}
	
		public void SetFPaytypeName(String fPaytypeName) {
			FPaytypeName = fPaytypeName;
		}
	
		public DateTime GetFPayTime() {
			return FPayTime;
		}
	
		public void SetFPayTime(DateTime fPayTime) {
			FPayTime = fPayTime;
		}
	
		public Double GetFPayPrice() {
			return FPayPrice;
		}
	
		public void SetFPayPrice(Double fPayPrice) {
			FPayPrice = fPayPrice;
		}
	
		public Double GetFPayPoints() {
			return FPayPoints;
		}
	
		public void SetFPayPoints(Double fPayPoints) {
			FPayPoints = fPayPoints;
		}
	
		public Int32 GetFGoodsNums() {
			return FGoodsNums;
		}
	
		public void SetFGoodsNums(Int32 fGoodsNums) {
			FGoodsNums = fGoodsNums;
		}
	
		public Int32 GetFOrderStatus() {
			return FOrderStatus;
		}
	
		public void SetFOrderStatus(Int32 fOrderStatus) {
			FOrderStatus = fOrderStatus;
		}
	
		public Double GetFHandingFee() {
			return FHandingFee;
		}
	
		public void SetFHandingFee(Double fHandingFee) {
			FHandingFee = fHandingFee;
		}
	
		public Double GetFSplitMoney() {
			return FSplitMoney;
		}
	
		public void SetFSplitMoney(Double fSplitMoney) {
			FSplitMoney = fSplitMoney;
		}
	
		public Int32 GetFPointsStatus() {
			return FPointsStatus;
		}
	
		public void SetFPointsStatus(Int32 fPointsStatus) {
			FPointsStatus = fPointsStatus;
		}
	
		public Double GetFCostPrice() {
			return FCostPrice;
		}
	
		public void SetFCostPrice(Double fCostPrice) {
			FCostPrice = fCostPrice;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
		public Int32 GetFOrderType() {
			return FOrderType;
		}
	
		public void SetFOrderType(Int32 fOrderType) {
			FOrderType = fOrderType;
		}
	
		public String GetFAuthorizerId() {
			return FAuthorizerId;
		}
	
		public void SetFAuthorizerId(String fAuthorizerId) {
			FAuthorizerId = fAuthorizerId;
		}
	
		public String GetFAuthorizerName() {
			return FAuthorizerName;
		}
	
		public void SetFAuthorizerName(String fAuthorizerName) {
			FAuthorizerName = fAuthorizerName;
		}
	
		public String GetFAuthorizerOrg() {
			return FAuthorizerOrg;
		}
	
		public void SetFAuthorizerOrg(String fAuthorizerOrg) {
			FAuthorizerOrg = fAuthorizerOrg;
		}
	
		public String GetFAuthorizerOrgName() {
			return FAuthorizerOrgName;
		}
	
		public void SetFAuthorizerOrgName(String fAuthorizerOrgName) {
			FAuthorizerOrgName = fAuthorizerOrgName;
		}
	
		public String GetFAuthorizerOrgPath() {
			return FAuthorizerOrgPath;
		}
	
		public void SetFAuthorizerOrgPath(String fAuthorizerOrgPath) {
			FAuthorizerOrgPath = fAuthorizerOrgPath;
		}
	
		public String GetFOffice() {
			return FOffice;
		}
	
		public void SetFOffice(String fOffice) {
			FOffice = fOffice;
		}
	
		public String GetFIdcard() {
			return FIdcard;
		}
	
		public void SetFIdcard(String fIdcard) {
			FIdcard = fIdcard;
		}
	
		public Double GetFClassHours() {
			return FClassHours;
		}
	
		public void SetFClassHours(Double fClassHours) {
			FClassHours = fClassHours;
		}
	
		public Double GetFClassScores() {
			return FClassScores;
		}
	
		public void SetFClassScores(Double fClassScores) {
			FClassScores = fClassScores;
		}
	
		public Int32 GetGoodsState() {
			return goodsState;
		}
	
		public void SetGoodsState(Int32 goodsState_0) {
			this.goodsState = goodsState_0;
		}
	}
}
