// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/* @SuppressWarnings("serial")*/
	[Serializable]
	public class TabNaireNaireInfo {
	
		private String FNaireId; //问卷ID
		private String FNaireNo; //问卷编号
		private String FNaireName; //问卷名称
		private DateTime FNaireYear; //所属年份
		private String FNaireDesc; //问卷信息描述
		private DateTime FNaireBegintime; //问卷开始时间
		private DateTime FNaireEndtime; //问卷截止时间
		private Int32 FNaireType; //问卷类型(0,  1,)
		private DateTime FCreateTime; //创建时间
		private Int32 FIfNotice; //是否通知学员(0:否;1:是)
		private String FNoticeWay; //通知方式
		private String FServplatId; //所属平台ID
		private String FServplatName; //所属平台名称
		private String FOrgId; //组织机构ID
		private String FOrgName; //组织机构名称
		private String FOrgPath; //机构路径
		private String FBaseId; //专业基地ID
		private String FBaseName; //专业基地名称
		private Int32 FStatus; //问卷状态(0、未发布,1、运行,2、关闭)
									//发布人数？
	
		public TabNaireNaireInfo() : base() {
		}
	
		public TabNaireNaireInfo(String fNaireId, String fNaireNo,
				String fNaireName, DateTime fNaireYear, String fNaireDesc,
				DateTime fNaireBegintime, DateTime fNaireEndtime, Int32 fNaireType,
				DateTime fCreateTime, Int32 fIfNotice, String fNoticeWay,
				String fServplatId, String fServplatName, String fOrgId,
				String fOrgName, String fOrgPath, String fBaseId, String fBaseName,
				Int32 fStatus) : base() {
			FNaireId = fNaireId;
			FNaireNo = fNaireNo;
			FNaireName = fNaireName;
			FNaireYear = fNaireYear;
			FNaireDesc = fNaireDesc;
			FNaireBegintime = fNaireBegintime;
			FNaireEndtime = fNaireEndtime;
			FNaireType = fNaireType;
			FCreateTime = fCreateTime;
			FIfNotice = fIfNotice;
			FNoticeWay = fNoticeWay;
			FServplatId = fServplatId;
			FServplatName = fServplatName;
			FOrgId = fOrgId;
			FOrgName = fOrgName;
			FOrgPath = fOrgPath;
			FBaseId = fBaseId;
			FBaseName = fBaseName;
			FStatus = fStatus;
		}
	
		public String GetFNaireId() {
			return FNaireId;
		}
	
		public void SetFNaireId(String fNaireId) {
			FNaireId = fNaireId;
		}
	
		public String GetFNaireNo() {
			return FNaireNo;
		}
	
		public void SetFNaireNo(String fNaireNo) {
			FNaireNo = fNaireNo;
		}
	
		public String GetFNaireName() {
			return FNaireName;
		}
	
		public void SetFNaireName(String fNaireName) {
			FNaireName = fNaireName;
		}
	
		public DateTime GetFNaireYear() {
			return FNaireYear;
		}
	
		public void SetFNaireYear(DateTime fNaireYear) {
			FNaireYear = fNaireYear;
		}
	
		public String GetFNaireDesc() {
			return FNaireDesc;
		}
	
		public void SetFNaireDesc(String fNaireDesc) {
			FNaireDesc = fNaireDesc;
		}
	
		public DateTime GetFNaireBegintime() {
			return FNaireBegintime;
		}
	
		public void SetFNaireBegintime(DateTime fNaireBegintime) {
			FNaireBegintime = fNaireBegintime;
		}
	
		public DateTime GetFNaireEndtime() {
			return FNaireEndtime;
		}
	
		public void SetFNaireEndtime(DateTime fNaireEndtime) {
			FNaireEndtime = fNaireEndtime;
		}
	
		public Int32 GetFNaireType() {
			return FNaireType;
		}
	
		public void SetFNaireType(Int32 fNaireType) {
			FNaireType = fNaireType;
		}
	
		public DateTime GetFCreateTime() {
			return FCreateTime;
		}
	
		public void SetFCreateTime(DateTime fCreateTime) {
			FCreateTime = fCreateTime;
		}
	
		public Int32 GetFIfNotice() {
			return FIfNotice;
		}
	
		public void SetFIfNotice(Int32 fIfNotice) {
			FIfNotice = fIfNotice;
		}
	
		public String GetFNoticeWay() {
			return FNoticeWay;
		}
	
		public void SetFNotice_way(String fNoticeWay) {
			FNoticeWay = fNoticeWay;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public Int32 GetFStatus() {
			return FStatus;
		}
	
		public void SetFStatus(Int32 fStatus) {
			FStatus = fStatus;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
		public String GetFOrgId() {
			return FOrgId;
		}
	
		public void SetFOrgId(String fOrgId) {
			FOrgId = fOrgId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
		public String GetFBaseId() {
			return FBaseId;
		}
	
		public void SetFBaseId(String fBaseId) {
			FBaseId = fBaseId;
		}
	
		public String GetFBaseName() {
			return FBaseName;
		}
	
		public void SetFBaseName(String fBaseName) {
			FBaseName = fBaseName;
		}
	
		public void SetFNoticeWay(String fNoticeWay) {
			FNoticeWay = fNoticeWay;
		}
	
	}
}
