// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// AbstractTabPlanPlancourInfo entity provides the base persistence definition
	/// of the TabPlanPlancourInfo entity.
	/// </summary>
	///
	[Serializable]
	
	public class TabPlanPlancourInfo {
	
		// Fields
	
		private String FPlancourId;
		private String FPlanId;
		private String FCourseId;
		private String FEntityId;
		private String FCourseNumber;
		private String FCourseName;
		private String FOrgId;
		private String FServplatId;
		private String FCourseblogoUrl;
		private String FCourseslogoUrl;
		private String FCourseDesc;
		private String FTeacherName;
		private Int32 FClassType;
		private Int32 FIftest;
		private Double FClassHours;
		private Double FClassScores;
		private Double FClassFee;
		private String FCoursetypePath;
		private DateTime FAddTime; //添加时间
	
		// Constructors
	
		// Property accessors
	
		public String GetFPlancourId() {
			return this.FPlancourId;
		}
	
		public void SetFPlancourId(String FPlancourId_0) {
			this.FPlancourId = FPlancourId_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFCourseId() {
			return this.FCourseId;
		}
	
		public void SetFCourseId(String FCourseId_0) {
			this.FCourseId = FCourseId_0;
		}
	
		public String GetFEntityId() {
			return this.FEntityId;
		}
	
		public void SetFEntityId(String FEntityId_0) {
			this.FEntityId = FEntityId_0;
		}
	
		public String GetFCourseNumber() {
			return this.FCourseNumber;
		}
	
		public void SetFCourseNumber(String FCourseNumber_0) {
			this.FCourseNumber = FCourseNumber_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public Int32 GetFClassType() {
			return this.FClassType;
		}
	
		public void SetFClassType(Int32 FClassType_0) {
			this.FClassType = FClassType_0;
		}
	
		public Int32 GetFIftest() {
			return this.FIftest;
		}
	
		public void SetFIftest(Int32 FIftest_0) {
			this.FIftest = FIftest_0;
		}
	
		public Double GetFClassHours() {
			return this.FClassHours;
		}
	
		public void SetFClassHours(Double FClassHours_0) {
			this.FClassHours = FClassHours_0;
		}
	
		public Double GetFClassScores() {
			return this.FClassScores;
		}
	
		public void SetFClassScores(Double FClassScores_0) {
			this.FClassScores = FClassScores_0;
		}
	
		public Double GetFClassFee() {
			return this.FClassFee;
		}
	
		public void SetFClassFee(Double FClassFee_0) {
			this.FClassFee = FClassFee_0;
		}
	
		public String GetFCourseName() {
			return FCourseName;
		}
	
		public void SetFCourseName(String fCourseName) {
			FCourseName = fCourseName;
		}
	
		public String GetFCourseblogoUrl() {
			return FCourseblogoUrl;
		}
	
		public void SetFCourseblogoUrl(String fCourseblogoUrl) {
			FCourseblogoUrl = fCourseblogoUrl;
		}
	
		public String GetFCourseslogoUrl() {
			return FCourseslogoUrl;
		}
	
		public void SetFCourseslogoUrl(String fCourseslogoUrl) {
			FCourseslogoUrl = fCourseslogoUrl;
		}
	
		public String GetFCourseDesc() {
			return FCourseDesc;
		}
	
		public void SetFCourseDesc(String fCourseDesc) {
			FCourseDesc = fCourseDesc;
		}
	
		public String GetFTeacherName() {
			return FTeacherName;
		}
	
		public void SetFTeacherName(String fTeacherName) {
			FTeacherName = fTeacherName;
		}
	
		public DateTime GetFAddTime() {
			return FAddTime;
		}
	
		public void SetFAddTime(DateTime fAddTime) {
			FAddTime = fAddTime;
		}
	
		public String GetFCoursetypePath() {
			return FCoursetypePath;
		}
	
		public void SetFCoursetypePath(String fCoursetypePath) {
			FCoursetypePath = fCoursetypePath;
		}
	
	}}
