// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabPlanOfftrainInfo {
	
		// Fields
	
		private String FOfftrainId;
		private String FUserId;
		private String FUserName;
		private String FSysuserId;
		private String FPlanId;
		private String FOrgId;
		private String FOrgName;
		private String FServplatId;
		private String FOfftrainName;
		private String FServplatName;
		private String FEduInstitutions;
		private String FApplyInfo;
		private String FTrainTime;
		private Double FTrainHours;
		private Double FTrainScores;
		private String FTrainCertificate;
		private String FTrainResult;
		private DateTime FApplyTime;
		private Double FApplyHours;
		private String FVerifyComments;
		private DateTime FVerifyTime;
		private Int32 FVerifyStatus;
		private String FArchivesId;
	
		// Constructors
	
		// Property accessors
	
		public String GetFOfftrainId() {
			return this.FOfftrainId;
		}
	
		public void SetFOfftrainId(String FOfftrainId_0) {
			this.FOfftrainId = FOfftrainId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFOfftrainName() {
			return FOfftrainName;
		}
	
		public void SetFOfftrainName(String offtrainName) {
			FOfftrainName = offtrainName;
		}
	
		public String GetFEduInstitutions() {
			return this.FEduInstitutions;
		}
	
		public void SetFEduInstitutions(String FEduInstitutions_0) {
			this.FEduInstitutions = FEduInstitutions_0;
		}
	
		public String GetFApplyInfo() {
			return this.FApplyInfo;
		}
	
		public void SetFApplyInfo(String FApplyInfo_0) {
			this.FApplyInfo = FApplyInfo_0;
		}
	
		public Double GetFTrainHours() {
			return FTrainHours;
		}
	
		public void SetFTrainHours(Double trainHours) {
			FTrainHours = trainHours;
		}
	
		public Double GetFTrainScores() {
			return this.FTrainScores;
		}
	
		public void SetFTrainScores(Double FTrainScores_0) {
			this.FTrainScores = FTrainScores_0;
		}
	
		public String GetFTrainCertificate() {
			return this.FTrainCertificate;
		}
	
		public void SetFTrainCertificate(String FTrainCertificate_0) {
			this.FTrainCertificate = FTrainCertificate_0;
		}
	
		public DateTime GetFApplyTime() {
			return this.FApplyTime;
		}
	
		public void SetFApplyTime(DateTime FApplyTime_0) {
			this.FApplyTime = FApplyTime_0;
		}
	
		public Double GetFApplyHours() {
			return this.FApplyHours;
		}
	
		public void SetFApplyHours(Double FApplyHours_0) {
			this.FApplyHours = FApplyHours_0;
		}
	
		public String GetFVerifyComments() {
			return this.FVerifyComments;
		}
	
		public void SetFVerifyComments(String FVerifyComments_0) {
			this.FVerifyComments = FVerifyComments_0;
		}
	
		public DateTime GetFVerifyTime() {
			return this.FVerifyTime;
		}
	
		public void SetFVerifyTime(DateTime FVerifyTime_0) {
			this.FVerifyTime = FVerifyTime_0;
		}
	
		public Int32 GetFVerifyStatus() {
			return this.FVerifyStatus;
		}
	
		public void SetFVerifyStatus(Int32 FVerifyStatus_0) {
			this.FVerifyStatus = FVerifyStatus_0;
		}
	
		public String GetFUserName() {
			return FUserName;
		}
	
		public void SetFUserName(String fUserName) {
			FUserName = fUserName;
		}
	
		public String GetFOrgId() {
			return FOrgId;
		}
	
		public void SetFOrgId(String fOrgId) {
			FOrgId = fOrgId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
		public String GetFTrainTime() {
			return FTrainTime;
		}
	
		public void SetFTrainTime(String fTrainTime) {
			FTrainTime = fTrainTime;
		}
	
		public String GetFTrainResult() {
			return FTrainResult;
		}
	
		public void SetFTrainResult(String fTrainResult) {
			FTrainResult = fTrainResult;
		}
	
		public String GetFArchivesId() {
			return FArchivesId;
		}
	
		public void SetFArchivesId(String archivesId) {
			FArchivesId = archivesId;
		}
	
	}
}
