// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabPlanPlanexamInfo {
	
		// Fields
	
		private String FPlanexamId;
		private String FPlanId;
		private String FOrgId;
		private String FServplatId;
		private String FExamId;
		private String FExamName;
		private DateTime FExamBegintime;
		private DateTime FExamEndtime;
		private Int32 FExamDuration;
		private Int32 FExamType;
		private Double FTotalScore;
		private Double FPassScore;
		private String FExamNo;
		private String FExamRange;
		private Int32 FIfSubjective;
		private Int32 FRetestTimes;
		private String FNoticeWay;
		private Int32 FStatus;
	
		// Constructors
	
		// Property accessors
	
		public String GetFPlanexamId() {
			return this.FPlanexamId;
		}
	
		public void SetFPlanexamId(String FPlanexamId_0) {
			this.FPlanexamId = FPlanexamId_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public String GetFExamId() {
			return this.FExamId;
		}
	
		public void SetFExamId(String FExamId_0) {
			this.FExamId = FExamId_0;
		}
	
		public String GetFExamName() {
			return this.FExamName;
		}
	
		public void SetFExamName(String FExamName_0) {
			this.FExamName = FExamName_0;
		}
	
		public DateTime GetFExamBegintime() {
			return this.FExamBegintime;
		}
	
		public void SetFExamBegintime(DateTime FExamBegintime_0) {
			this.FExamBegintime = FExamBegintime_0;
		}
	
		public DateTime GetFExamEndtime() {
			return this.FExamEndtime;
		}
	
		public void SetFExamEndtime(DateTime FExamEndtime_0) {
			this.FExamEndtime = FExamEndtime_0;
		}
	
		public Int32 GetFExamDuration() {
			return this.FExamDuration;
		}
	
		public void SetFExamDuration(Int32 FExamDuration_0) {
			this.FExamDuration = FExamDuration_0;
		}
	
		public Int32 GetFExamType() {
			return this.FExamType;
		}
	
		public void SetFExamType(Int32 FExamType_0) {
			this.FExamType = FExamType_0;
		}
	
		public Double GetFTotalScore() {
			return this.FTotalScore;
		}
	
		public void SetFTotalScore(Double FTotalScore_0) {
			this.FTotalScore = FTotalScore_0;
		}
	
		public Double GetFPassScore() {
			return this.FPassScore;
		}
	
		public void SetFPassScore(Double FPassScore_0) {
			this.FPassScore = FPassScore_0;
		}
	
		public String GetFExamNo() {
			return this.FExamNo;
		}
	
		public void SetFExamNo(String FExamNo_0) {
			this.FExamNo = FExamNo_0;
		}
	
		public String GetFExamRange() {
			return this.FExamRange;
		}
	
		public void SetFExamRange(String FExamRange_0) {
			this.FExamRange = FExamRange_0;
		}
	
		public Int32 GetFIfSubjective() {
			return this.FIfSubjective;
		}
	
		public void SetFIfSubjective(Int32 FIfSubjective_0) {
			this.FIfSubjective = FIfSubjective_0;
		}
	
		public Int32 GetFRetestTimes() {
			return this.FRetestTimes;
		}
	
		public void SetFRetestTimes(Int32 FRetestTimes_0) {
			this.FRetestTimes = FRetestTimes_0;
		}
	
		public String GetFNoticeWay() {
			return this.FNoticeWay;
		}
	
		public void SetFNoticeWay(String FNoticeWay_0) {
			this.FNoticeWay = FNoticeWay_0;
		}
	
		public Int32 GetFStatus() {
			return this.FStatus;
		}
	
		public void SetFStatus(Int32 FStatus_0) {
			this.FStatus = FStatus_0;
		}
	
	}}
