// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabPlanTrainplanFilter {
	
		private String FFilterId;
		private String FPlanId;
		private String FOrgId;
		private String FServplatId;
		private Int32 FFilterType;
		private String FFilterSql;
		private String FFilterDesc;
	
		public String GetFFilterId() {
			return FFilterId;
		}
	
		public void SetFFilterId(String fFilterId) {
			FFilterId = fFilterId;
		}
	
		public String GetFPlanId() {
			return FPlanId;
		}
	
		public void SetFPlanId(String fPlanId) {
			FPlanId = fPlanId;
		}
	
		public String GetFOrgId() {
			return FOrgId;
		}
	
		public void SetFOrgId(String fOrgId) {
			FOrgId = fOrgId;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public Int32 GetFFilterType() {
			return FFilterType;
		}
	
		public void SetFFilterType(Int32 fFilterType) {
			FFilterType = fFilterType;
		}
	
		public String GetFFilterSql() {
			return FFilterSql;
		}
	
		public void SetFFilterSql(String fFilterSql) {
			FFilterSql = fFilterSql;
		}
	
		public String GetFFilterDesc() {
			return FFilterDesc;
		}
	
		public void SetFFilterDesc(String fFilterDesc) {
			FFilterDesc = fFilterDesc;
		}
	
	}
}
