// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// AbstractTabPlanActcardDetail entity provides the base persistence definition
	/// of the TabPlanActcardDetail entity.
	/// </summary>
	///
	[Serializable]
	
	public class TabPlanActcardDetail {
	
		// Fields
	
		private String FDetailId;
		private String FActcardNo;
		private String FActcardPwd;
		private DateTime FActTime;
		private String FUserId;
		private String FUserName;
		private String FRealName;
		private String FServplatId;
		private String FServplatName;
		private Int32 FPlanType;
		private String FPlanId;
		private String FPlanNo;
		private String FPlanName;
		private String FBatchId;
		private String FBatchNo;
		private Int32 FActcardStatus;
		private String FOrgId;
		private String FOrgName;
		private String FOrgPath;
		private String FSaleStatus;
		private String FSaleTime;
		private String FSaleAdmin;
		private String FIfUpdate;
	
		// Constructors
	
		// Property accessors
	
		public String GetFDetailId() {
			return this.FDetailId;
		}
	
		public void SetFDetailId(String FDetailId_0) {
			this.FDetailId = FDetailId_0;
		}
	
		public String GetFActcardNo() {
			return this.FActcardNo;
		}
	
		public void SetFActcardNo(String FActcardNo_0) {
			this.FActcardNo = FActcardNo_0;
		}
	
		public String GetFActcardPwd() {
			return this.FActcardPwd;
		}
	
		public void SetFActcardPwd(String FActcardPwd_0) {
			this.FActcardPwd = FActcardPwd_0;
		}
	
		public DateTime GetFActTime() {
			return this.FActTime;
		}
	
		public void SetFActTime(DateTime FActTime_0) {
			this.FActTime = FActTime_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFBatchId() {
			return this.FBatchId;
		}
	
		public void SetFBatchId(String FBatchId_0) {
			this.FBatchId = FBatchId_0;
		}
	
		public Int32 GetFActcardStatus() {
			return this.FActcardStatus;
		}
	
		public void SetFActcardStatus(Int32 FActcardStatus_0) {
			this.FActcardStatus = FActcardStatus_0;
		}
	
		public String GetFUserName() {
			return FUserName;
		}
	
		public void SetFUserName(String fUserName) {
			FUserName = fUserName;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
		public Int32 GetFPlanType() {
			return FPlanType;
		}
	
		public void SetFPlanType(Int32 fPlanType) {
			FPlanType = fPlanType;
		}
	
		public String GetFPlanNo() {
			return FPlanNo;
		}
	
		public void SetFPlanNo(String fPlanNo) {
			FPlanNo = fPlanNo;
		}
	
		public String GetFPlanName() {
			return FPlanName;
		}
	
		public void SetFPlanName(String fPlanName) {
			FPlanName = fPlanName;
		}
	
		public String GetFBatchNo() {
			return FBatchNo;
		}
	
		public void SetFBatchNo(String fBatchNo) {
			FBatchNo = fBatchNo;
		}
	
		public String GetFRealName() {
			return FRealName;
		}
	
		public void SetFRealName(String fRealName) {
			FRealName = fRealName;
		}
	
		public String GetFOrgId() {
			return FOrgId;
		}
	
		public void SetFOrgId(String fOrgId) {
			FOrgId = fOrgId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
		public String GetFSaleStatus() {
			return FSaleStatus;
		}
	
		public void SetFSaleStatus(String fSaleStatus) {
			FSaleStatus = fSaleStatus;
		}
	
		public String GetFSaleTime() {
			return FSaleTime;
		}
	
		public void SetFSaleTime(String fSaleTime) {
			FSaleTime = fSaleTime;
		}
	
		public String GetFSaleAdmin() {
			return FSaleAdmin;
		}
	
		public void SetFSaleAdmin(String fSaleAdmin) {
			FSaleAdmin = fSaleAdmin;
		}
	
		public String GetFIfUpdate() {
			return FIfUpdate;
		}
	
		public void SetFIfUpdate(String fIfUpdate) {
			FIfUpdate = fIfUpdate;
		}
	
	}}
