// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.Data.SqlTypes;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// AbstractTabPlanPlanuserInfo entity provides the base persistence definition
	/// of the TabPlanPlanuserInfo entity.
	/// </summary>
	///
	[Serializable]
	
	public class TabPlanPlanuserInfo {
	
		// Fields
	
		private String FPlanuserId;
		private String FPlanId;
		private String FUserId;
		private String FUserName;
		private String FRealName;
		private String FSex;
		private String FDegreeId;
		private String FPosition;
		private DateTime FBirthday;
		private String FProfId;
		private String FOrgId;
		private String FOrgName;
		private String FServplatId;
		private Int32 FPlanType;
		private Int32 FJoinType;
		private Double FTotalHours;
		private Double FFinishHours;
		private Int32 FMustCourses;
		private Int32 FFinishCourses;
		private Int32 FUserStatus;
		private Int32 FPlanStatus;
	
		private String FPlanName;
		private DateTime FStartTime;
		private SqlDateTime FEndTime;
		private String FPlanDesc;
		private String FPlanlogoUrl;
		private Int32 FPayWay;
		private Int32 FAssessWay;
		private Double FAssessValue;
		private String FBelongsplanId;
	
		private DateTime FAddTime;
		private String FOrgPath;
	
		// Constructors
	
		// Property accessors
	
		public String GetFPlanuserId() {
			return this.FPlanuserId;
		}
	
		public void SetFPlanuserId(String FPlanuserId_0) {
			this.FPlanuserId = FPlanuserId_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public Int32 GetFPlanType() {
			return this.FPlanType;
		}
	
		public void SetFPlanType(Int32 FPlanType_0) {
			this.FPlanType = FPlanType_0;
		}
	
		public Int32 GetFJoinType() {
			return this.FJoinType;
		}
	
		public void SetFJoinType(Int32 FJoinType_0) {
			this.FJoinType = FJoinType_0;
		}
	
		public Double GetFTotalHours() {
			return this.FTotalHours;
		}
	
		public void SetFTotalHours(Double FTotalHours_0) {
			this.FTotalHours = FTotalHours_0;
		}
	
		public Double GetFFinishHours() {
			return this.FFinishHours;
		}
	
		public void SetFFinishHours(Double FFinishHours_0) {
			this.FFinishHours = FFinishHours_0;
		}
	
		public Int32 GetFMustCourses() {
			return this.FMustCourses;
		}
	
		public void SetFMustCourses(Int32 FMustCourses_0) {
			this.FMustCourses = FMustCourses_0;
		}
	
		public Int32 GetFFinishCourses() {
			return this.FFinishCourses;
		}
	
		public void SetFFinishCourses(Int32 FFinishCourses_0) {
			this.FFinishCourses = FFinishCourses_0;
		}
	
		public Int32 GetFPlanStatus() {
			return this.FPlanStatus;
		}
	
		public void SetFPlanStatus(Int32 FPlanStatus_0) {
			this.FPlanStatus = FPlanStatus_0;
		}
	
		public Int32 GetFUserStatus() {
			return FUserStatus;
		}
	
		public void SetFUserStatus(Int32 fUserStatus) {
			FUserStatus = fUserStatus;
		}
	
		public String GetFRealName() {
			return FRealName;
		}
	
		public void SetFRealName(String fRealName) {
			FRealName = fRealName;
		}
	
		public String GetFSex() {
			return FSex;
		}
	
		public void SetFSex(String fSex) {
			FSex = fSex;
		}
	
		public String GetFDegreeId() {
			return FDegreeId;
		}
	
		public void SetFDegreeId(String fDegreeId) {
			FDegreeId = fDegreeId;
		}
	
		public String GetFPosition() {
			return FPosition;
		}
	
		public void SetFPosition(String fPosition) {
			FPosition = fPosition;
		}
	
		public DateTime GetFBirthday() {
			return FBirthday;
		}
	
		public void SetFBirthday(DateTime fBirthday) {
			FBirthday = fBirthday;
		}
	
		public String GetFProfId() {
			return FProfId;
		}
	
		public void SetFProfId(String fProfId) {
			FProfId = fProfId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFPlanName() {
			return FPlanName;
		}
	
		public void SetFPlanName(String fPlanName) {
			FPlanName = fPlanName;
		}
	
		public DateTime GetFStartTime() {
			return FStartTime;
		}
	
		public void SetFStartTime(DateTime fStartTime) {
			FStartTime = fStartTime;
		}
	
		public SqlDateTime GetFEndTime() {
			return FEndTime;
		}
	
		public void SetFEndTime(SqlDateTime fEndTime) {
			FEndTime = fEndTime;
		}
	
		public String GetFPlanDesc() {
			return FPlanDesc;
		}
	
		public void SetFPlanDesc(String fPlanDesc) {
			FPlanDesc = fPlanDesc;
		}
	
		public String GetFPlanlogoUrl() {
			return FPlanlogoUrl;
		}
	
		public void SetFPlanlogoUrl(String fPlanlogoUrl) {
			FPlanlogoUrl = fPlanlogoUrl;
		}
	
		public Int32 GetFPayWay() {
			return FPayWay;
		}
	
		public void SetFPayWay(Int32 fPayWay) {
			FPayWay = fPayWay;
		}
	
		public Int32 GetFAssessWay() {
			return FAssessWay;
		}
	
		public void SetFAssessWay(Int32 fAssessWay) {
			FAssessWay = fAssessWay;
		}
	
		public Double GetFAssessValue() {
			return FAssessValue;
		}
	
		public void SetFAssessValue(Double fAssessValue) {
			FAssessValue = fAssessValue;
		}
	
		public String GetFBelongsplanId() {
			return FBelongsplanId;
		}
	
		public void SetFBelongsplanId(String fBelongsplanId) {
			FBelongsplanId = fBelongsplanId;
		}
	
		public DateTime GetFAddTime() {
			return FAddTime;
		}
	
		public void SetFAddTime(DateTime fAddTime) {
			FAddTime = fAddTime;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
	}}
