// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.Data.SqlTypes;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabPlanTrainplanInfo {
		// Fields
	
		private String FPlanId;
		private String FPlanName;
		private String FPlanNo;
		private String FParentplanId;
		private String FPubuserId;
		private String FAcceptuserId;
		private SqlDateTime FStartTime;
		private SqlDateTime FEndTime;
		private String FPlanYear;
		private String FPlanDesc;
		private String FPlanlogoUrl;
		private String FSysuserId;
		private String FBaseId;
		private String FOrgId;
		private String FOrgName;
		private String FServplatId;
		private String FServplatName;
		private SqlDateTime FCreateTime;
		private Int32 FPlanType;
		private String FBelongsplanId;
		private Int32 FAssessWay;
		private Double FAssessValue;
		private Int32 FOfflineStatus;
		private Int32 FPrintStatus;
		private Int32 FPayWay;
		private Int32 FActivateNums;
		private Int32 FJoinWay;
		private Int32 FIfTest;
		private Int32 FTrainWay;
		private Int32 FBelongFlag;
		private Int64 FTrainNums;
		private Int32 FClassNums;
		private Int32 FMustCourses;
		private Double FTotalClasshours;
		private Double FTrainFee;
		private Double FDiscountFee;
		private Int32 FPlanStatus;
		private Int32 FVerifyStatus;
		private Int32 FPlanLevel;
		private Int32 FAssessType;// f_assess_way
		private Double FMinMust;// f_min_must
		private Int32 FIfTuijian;
	
		private String FOrgPath;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabPlanTrainplanInfo() {
		}
	
		// Property accessors
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFPlanName() {
			return this.FPlanName;
		}
	
		public void SetFPlanName(String FPlanName_0) {
			this.FPlanName = FPlanName_0;
		}
	
		public String GetFPlanNo() {
			return this.FPlanNo;
		}
	
		public void SetFPlanNo(String FPlanNo_0) {
			this.FPlanNo = FPlanNo_0;
		}
	
		public SqlDateTime GetFStartTime() {
			return this.FStartTime;
		}
	
		public void SetFStartTime(SqlDateTime FStartTime_0) {
			this.FStartTime = FStartTime_0;
		}
	
		public SqlDateTime GetFEndTime() {
			return this.FEndTime;
		}
	
		public void SetFEndTime(SqlDateTime FEndTime_0) {
			this.FEndTime = FEndTime_0;
		}
	
		public String GetFPlanYear() {
			return this.FPlanYear;
		}
	
		public void SetFPlanYear(String FPlanYear_0) {
			this.FPlanYear = FPlanYear_0;
		}
	
		public String GetFPlanDesc() {
			return this.FPlanDesc;
		}
	
		public void SetFPlanDesc(String FPlanDesc_0) {
			this.FPlanDesc = FPlanDesc_0;
		}
	
		public String GetFPlanlogoUrl() {
			return this.FPlanlogoUrl;
		}
	
		public void SetFPlanlogoUrl(String FPlanlogoUrl_0) {
			this.FPlanlogoUrl = FPlanlogoUrl_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public String GetFBaseId() {
			return this.FBaseId;
		}
	
		public void SetFBaseId(String FBaseId_0) {
			this.FBaseId = FBaseId_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public SqlDateTime GetFCreateTime() {
			return this.FCreateTime;
		}
	
		public void SetFCreateTime(SqlDateTime FCreateTime_0) {
			this.FCreateTime = FCreateTime_0;
		}
	
		public Int32 GetFPlanType() {
			return this.FPlanType;
		}
	
		public void SetFPlanType(Int32 FPlanType_0) {
			this.FPlanType = FPlanType_0;
		}
	
		public String GetFParentplanId() {
			return this.FParentplanId;
		}
	
		public void SetFParentplanId(String FParentplanId_0) {
			this.FParentplanId = FParentplanId_0;
		}
	
		public Int32 GetFAssessWay() {
			return this.FAssessWay;
		}
	
		public void SetFAssessWay(Int32 FAssessWay_0) {
			this.FAssessWay = FAssessWay_0;
		}
	
		public Double GetFAssessValue() {
			return this.FAssessValue;
		}
	
		public void SetFAssessValue(Double FAssessValue_0) {
			this.FAssessValue = FAssessValue_0;
		}
	
		public Int32 GetFOfflineStatus() {
			return this.FOfflineStatus;
		}
	
		public void SetFOfflineStatus(Int32 FOfflineStatus_0) {
			this.FOfflineStatus = FOfflineStatus_0;
		}
	
		public Int32 GetFPrintStatus() {
			return this.FPrintStatus;
		}
	
		public void SetFPrintStatus(Int32 FPrintStatus_0) {
			this.FPrintStatus = FPrintStatus_0;
		}
	
		public Int32 GetFPayWay() {
			return this.FPayWay;
		}
	
		public void SetFPayWay(Int32 FPayWay_0) {
			this.FPayWay = FPayWay_0;
		}
	
		public Int32 GetFActivateNums() {
			return this.FActivateNums;
		}
	
		public void SetFActivateNums(Int32 FActivateNums_0) {
			this.FActivateNums = FActivateNums_0;
		}
	
		public Int32 GetFJoinWay() {
			return this.FJoinWay;
		}
	
		public void SetFJoinWay(Int32 FJoinWay_0) {
			this.FJoinWay = FJoinWay_0;
		}
	
		public Int32 GetFIfTest() {
			return this.FIfTest;
		}
	
		public void SetFIfTest(Int32 FIfTest_0) {
			this.FIfTest = FIfTest_0;
		}
	
		public Int32 GetFTrainWay() {
			return this.FTrainWay;
		}
	
		public void SetFTrainWay(Int32 FTrainWay_0) {
			this.FTrainWay = FTrainWay_0;
		}
	
		public Int32 GetFClassNums() {
			return this.FClassNums;
		}
	
		public void SetFClassNums(Int32 FClassNums_0) {
			this.FClassNums = FClassNums_0;
		}
	
		public Double GetFTotalClasshours() {
			return this.FTotalClasshours;
		}
	
		public void SetFTotalClasshours(Double FTotalClasshours_0) {
			this.FTotalClasshours = FTotalClasshours_0;
		}
	
		public Double GetFTrainFee() {
			return this.FTrainFee;
		}
	
		public void SetFTrainFee(Double FTrainFee_0) {
			this.FTrainFee = FTrainFee_0;
		}
	
		public Double GetFDiscountFee() {
			return this.FDiscountFee;
		}
	
		public void SetFDiscountFee(Double FDiscountFee_0) {
			this.FDiscountFee = FDiscountFee_0;
		}
	
		public Int32 GetFVerifyStatus() {
			return this.FVerifyStatus;
		}
	
		public void SetFVerifyStatus(Int32 FVerifyStatus_0) {
			this.FVerifyStatus = FVerifyStatus_0;
		}
	
		public String GetFPubuserId() {
			return FPubuserId;
		}
	
		public void SetFPubuserId(String fPubuserId) {
			FPubuserId = fPubuserId;
		}
	
		public String GetFAcceptuserId() {
			return FAcceptuserId;
		}
	
		public void SetFAcceptuserId(String fAcceptuserId) {
			FAcceptuserId = fAcceptuserId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
		public String GetFBelongsplanId() {
			return FBelongsplanId;
		}
	
		public void SetFBelongsplanId(String fBelongsplanId) {
			FBelongsplanId = fBelongsplanId;
		}
	
		public Int32 GetFBelongFlag() {
			return FBelongFlag;
		}
	
		public void SetFBelongFlag(Int32 fBelongFlag) {
			FBelongFlag = fBelongFlag;
		}
	
		public Int64 GetFTrainNums() {
			return FTrainNums;
		}
	
		public void SetFTrainNums(Int64 fTrainNums) {
			FTrainNums = fTrainNums;
		}
	
		public Int32 GetFMustCourses() {
			return FMustCourses;
		}
	
		public void SetFMustCourses(Int32 fMustCourses) {
			FMustCourses = fMustCourses;
		}
	
		public Int32 GetFPlanStatus() {
			return FPlanStatus;
		}
	
		public void SetFPlanStatus(Int32 fPlanStatus) {
			FPlanStatus = fPlanStatus;
		}
	
		public Int32 GetFPlanLevel() {
			return FPlanLevel;
		}
	
		public void SetFPlanLevel(Int32 fPlanLevel) {
			FPlanLevel = fPlanLevel;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
		public Int32 GetFAssessType() {
			return FAssessType;
		}
	
		public void SetFAssessType(Int32 fAssessType) {
			FAssessType = fAssessType;
		}
	
		public Double GetFMinMust() {
			return FMinMust;
		}
	
		public void SetFMinMust(Double fMinMust) {
			FMinMust = fMinMust;
		}
	
		public Int32 GetFIfTuijian() {
			return FIfTuijian;
		}
	
		public void SetFIfTuijian(Int32 fIfTuijian) {
			FIfTuijian = fIfTuijian;
		}
	
	}
}
