// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.Data.SqlTypes;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabRescenCourseInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabRescenCourseInfo {
	
		// Fields
	
		private String FCourseId;
		private String FCourseName;
		private String FCourseNo;
		private String FParentId;
		private Int32 FSortCode;
		private String FCoursePath;
		private String FCoursetypeId;
		private Int32 FCourseformatId;
		private String FSupplierId;
		private String FSysuserId;
		private SqlDateTime FCreateTime;
		private String FTecherName;
		private String FLevelId;
		private Int32 FChapterNums;
		private Int32 FCourseScores;
		private Int32 FCourseHours;
		private Double FStudyDuration;
		private Double FCoursePrice;
		private String FCourseDesc;
		private Int32 FVerifyStatus;
		private Int32 FUseStatus;
		private Int32 FIsSell;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabRescenCourseInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabRescenCourseInfo(String FCourseId_0) {
			this.FCourseId = FCourseId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabRescenCourseInfo(String FCourseId_0, String FCourseName_1,
				String FCourseNo_2, String FParentId_3, Int32 FSortCode_4,
				String FCoursePath_5, String FCoursetypeId_6, Int32 FCourseformatId_7,
				String FSupplierId_8, String FSysuserId_9, SqlDateTime FCreateTime_10,
				String FTecherName_11, String FLevelId_12, Int32 FChapterNums_13,
				Int32 FCourseScores_14, Int32 FCourseHours_15, Double FStudyDuration_16,
				Double FCoursePrice_17, String FCourseDesc_18, Int32 FVerifyStatus_19,
				Int32 FUseStatus_20, Int32 FIsSell_21) {
			this.FCourseId = FCourseId_0;
			this.FCourseName = FCourseName_1;
			this.FCourseNo = FCourseNo_2;
			this.FParentId = FParentId_3;
			this.FSortCode = FSortCode_4;
			this.FCoursePath = FCoursePath_5;
			this.FCoursetypeId = FCoursetypeId_6;
			this.FCourseformatId = FCourseformatId_7;
			this.FSupplierId = FSupplierId_8;
			this.FSysuserId = FSysuserId_9;
			this.FCreateTime = FCreateTime_10;
			this.FTecherName = FTecherName_11;
			this.FLevelId = FLevelId_12;
			this.FChapterNums = FChapterNums_13;
			this.FCourseScores = FCourseScores_14;
			this.FCourseHours = FCourseHours_15;
			this.FStudyDuration = FStudyDuration_16;
			this.FCoursePrice = FCoursePrice_17;
			this.FCourseDesc = FCourseDesc_18;
			this.FVerifyStatus = FVerifyStatus_19;
			this.FUseStatus = FUseStatus_20;
			this.FIsSell = FIsSell_21;
		}
	
		// Property accessors
	
		public String GetFCourseId() {
			return this.FCourseId;
		}
	
		public void SetFCourseId(String FCourseId_0) {
			this.FCourseId = FCourseId_0;
		}
	
		public String GetFCourseName() {
			return this.FCourseName;
		}
	
		public void SetFCourseName(String FCourseName_0) {
			this.FCourseName = FCourseName_0;
		}
	
		public String GetFCourseNo() {
			return this.FCourseNo;
		}
	
		public void SetFCourseNo(String FCourseNo_0) {
			this.FCourseNo = FCourseNo_0;
		}
	
		public String GetFParentId() {
			return this.FParentId;
		}
	
		public void SetFParentId(String FParentId_0) {
			this.FParentId = FParentId_0;
		}
	
		public Int32 GetFSortCode() {
			return this.FSortCode;
		}
	
		public void SetFSortCode(Int32 FSortCode_0) {
			this.FSortCode = FSortCode_0;
		}
	
		public String GetFCoursePath() {
			return this.FCoursePath;
		}
	
		public void SetFCoursePath(String FCoursePath_0) {
			this.FCoursePath = FCoursePath_0;
		}
	
		public String GetFCoursetypeId() {
			return this.FCoursetypeId;
		}
	
		public void SetFCoursetypeId(String FCoursetypeId_0) {
			this.FCoursetypeId = FCoursetypeId_0;
		}
	
		public Int32 GetFCourseformatId() {
			return this.FCourseformatId;
		}
	
		public void SetFCourseformatId(Int32 FCourseformatId_0) {
			this.FCourseformatId = FCourseformatId_0;
		}
	
		public String GetFSupplierId() {
			return this.FSupplierId;
		}
	
		public void SetFSupplierId(String FSupplierId_0) {
			this.FSupplierId = FSupplierId_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public SqlDateTime GetFCreateTime() {
			return this.FCreateTime;
		}
	
		public void SetFCreateTime(SqlDateTime FCreateTime_0) {
			this.FCreateTime = FCreateTime_0;
		}
	
		public String GetFTecherName() {
			return this.FTecherName;
		}
	
		public void SetFTecherName(String FTecherName_0) {
			this.FTecherName = FTecherName_0;
		}
	
		public String GetFLevelId() {
			return this.FLevelId;
		}
	
		public void SetFLevelId(String FLevelId_0) {
			this.FLevelId = FLevelId_0;
		}
	
		public Int32 GetFChapterNums() {
			return this.FChapterNums;
		}
	
		public void SetFChapterNums(Int32 FChapterNums_0) {
			this.FChapterNums = FChapterNums_0;
		}
	
		public Int32 GetFCourseScores() {
			return this.FCourseScores;
		}
	
		public void SetFCourseScores(Int32 FCourseScores_0) {
			this.FCourseScores = FCourseScores_0;
		}
	
		public Int32 GetFCourseHours() {
			return this.FCourseHours;
		}
	
		public void SetFCourseHours(Int32 FCourseHours_0) {
			this.FCourseHours = FCourseHours_0;
		}
	
		public Double GetFStudyDuration() {
			return this.FStudyDuration;
		}
	
		public void SetFStudyDuration(Double FStudyDuration_0) {
			this.FStudyDuration = FStudyDuration_0;
		}
	
		public Double GetFCoursePrice() {
			return this.FCoursePrice;
		}
	
		public void SetFCoursePrice(Double FCoursePrice_0) {
			this.FCoursePrice = FCoursePrice_0;
		}
	
		public String GetFCourseDesc() {
			return this.FCourseDesc;
		}
	
		public void SetFCourseDesc(String FCourseDesc_0) {
			this.FCourseDesc = FCourseDesc_0;
		}
	
		public Int32 GetFVerifyStatus() {
			return this.FVerifyStatus;
		}
	
		public void SetFVerifyStatus(Int32 FVerifyStatus_0) {
			this.FVerifyStatus = FVerifyStatus_0;
		}
	
		public Int32 GetFUseStatus() {
			return this.FUseStatus;
		}
	
		public void SetFUseStatus(Int32 FUseStatus_0) {
			this.FUseStatus = FUseStatus_0;
		}
	
		public Int32 GetFIsSell() {
			return this.FIsSell;
		}
	
		public void SetFIsSell(Int32 FIsSell_0) {
			this.FIsSell = FIsSell_0;
		}
	
	}
}
