// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// AbstractTabRescenCourseEntity entity provides the base persistence definition
	/// of the TabRescenCourseEntity entity.
	/// </summary>
	///
	[Serializable]
	
	public class TabRescenCourseEntity {
	
		// Fields
	
		private String FEntityId;
		private String FCourseId;
		private String FSupplierId;
		private String FEntityDesc;
		private String FEntityName;
		private String FCourseVersion;
		private String FCourseblogoUrl;
		private String FCourseslogoUrl;
		private String FCourseUrl;
		private String FCourseNumber;
		private String FTerminalType;
	
		// Constructors
	
		// Property accessors
	
		public String GetFEntityId() {
			return this.FEntityId;
		}
	
		public void SetFEntityId(String FEntityId_0) {
			this.FEntityId = FEntityId_0;
		}
	
		public String GetFCourseId() {
			return this.FCourseId;
		}
	
		public void SetFCourseId(String FCourseId_0) {
			this.FCourseId = FCourseId_0;
		}
	
		public String GetFSupplierId() {
			return this.FSupplierId;
		}
	
		public void SetFSupplierId(String FSupplierId_0) {
			this.FSupplierId = FSupplierId_0;
		}
	
		public String GetFEntityDesc() {
			return this.FEntityDesc;
		}
	
		public void SetFEntityDesc(String FEntityDesc_0) {
			this.FEntityDesc = FEntityDesc_0;
		}
	
		public String GetFEntityName() {
			return this.FEntityName;
		}
	
		public void SetFEntityName(String FEntityName_0) {
			this.FEntityName = FEntityName_0;
		}
	
		public String GetFCourseVersion() {
			return this.FCourseVersion;
		}
	
		public void SetFCourseVersion(String FCourseVersion_0) {
			this.FCourseVersion = FCourseVersion_0;
		}
	
		public String GetFCourseblogoUrl() {
			return this.FCourseblogoUrl;
		}
	
		public void SetFCourseblogoUrl(String FCourseblogoUrl_0) {
			this.FCourseblogoUrl = FCourseblogoUrl_0;
		}
	
		public String GetFCourseslogoUrl() {
			return this.FCourseslogoUrl;
		}
	
		public void SetFCourseslogoUrl(String FCourseslogoUrl_0) {
			this.FCourseslogoUrl = FCourseslogoUrl_0;
		}
	
		public String GetFCourseUrl() {
			return this.FCourseUrl;
		}
	
		public void SetFCourseUrl(String FCourseUrl_0) {
			this.FCourseUrl = FCourseUrl_0;
		}
	
		public String GetFCourseNumber() {
			return this.FCourseNumber;
		}
	
		public void SetFCourseNumber(String FCourseNumber_0) {
			this.FCourseNumber = FCourseNumber_0;
		}
	
		public String GetFTerminalType() {
			return this.FTerminalType;
		}
	
		public void SetFTerminalType(String FTerminalType_0) {
			this.FTerminalType = FTerminalType_0;
		}
	
	}}
