// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabSysCourseSupplier {
	
		// Fields
	
		private String FSupplierId;
		private String FSupplierName;
		private DateTime FCreateTime;
		private String FSysuserId;
		private String FLogoUrl;
		private Int32 FSplitWay;
		private Double FSplitGet;
		private Double FSplitReturn;
		private String FSplitPercent;
		private String FPayAcc;
		private String FAdminUser;
		private Int32 FSupplierStatus;
		private String FSupplierDesc;
	
		// Constructors
	
		// Property accessors
	
		public String GetFSupplierId() {
			return this.FSupplierId;
		}
	
		public void SetFSupplierId(String FSupplierId_0) {
			this.FSupplierId = FSupplierId_0;
		}
	
		public String GetFSupplierName() {
			return this.FSupplierName;
		}
	
		public void SetFSupplierName(String FSupplierName_0) {
			this.FSupplierName = FSupplierName_0;
		}
	
		public DateTime GetFCreateTime() {
			return this.FCreateTime;
		}
	
		public void SetFCreateTime(DateTime FCreateTime_0) {
			this.FCreateTime = FCreateTime_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public String GetFLogoUrl() {
			return this.FLogoUrl;
		}
	
		public void SetFLogoUrl(String FLogoUrl_0) {
			this.FLogoUrl = FLogoUrl_0;
		}
	
		public Int32 GetFSplitWay() {
			return this.FSplitWay;
		}
	
		public void SetFSplitWay(Int32 FSplitWay_0) {
			this.FSplitWay = FSplitWay_0;
		}
	
		public Double GetFSplitGet() {
			return this.FSplitGet;
		}
	
		public void SetFSplitGet(Double FSplitGet_0) {
			this.FSplitGet = FSplitGet_0;
		}
	
		public Double GetFSplitReturn() {
			return this.FSplitReturn;
		}
	
		public void SetFSplitReturn(Double FSplitReturn_0) {
			this.FSplitReturn = FSplitReturn_0;
		}
	
		public String GetFSplitPercent() {
			return this.FSplitPercent;
		}
	
		public void SetFSplitPercent(String FSplitPercent_0) {
			this.FSplitPercent = FSplitPercent_0;
		}
	
		public String GetFPayAcc() {
			return this.FPayAcc;
		}
	
		public void SetFPayAcc(String FPayAcc_0) {
			this.FPayAcc = FPayAcc_0;
		}
	
		public String GetFAdminUser() {
			return this.FAdminUser;
		}
	
		public void SetFAdminUser(String FAdminUser_0) {
			this.FAdminUser = FAdminUser_0;
		}
	
		public Int32 GetFSupplierStatus() {
			return this.FSupplierStatus;
		}
	
		public void SetFSupplierStatus(Int32 FSupplierStatus_0) {
			this.FSupplierStatus = FSupplierStatus_0;
		}
	
		public String GetFSupplierDesc() {
			return this.FSupplierDesc;
		}
	
		public void SetFSupplierDesc(String FSupplierDesc_0) {
			this.FSupplierDesc = FSupplierDesc_0;
		}
	
	}
}
