// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabSysTokenInfo {
	
		public String FTokenInfo;
	
		public DateTime FTimeStamp;
	
		public TabSysTokenInfo(String fTokenInfo) {
			this.FTokenInfo = fTokenInfo;
		}
	
		public String GetFTokenInfo() {
			return FTokenInfo;
		}
	
		public void SetFTokenInfo(String fTokenInfo) {
			FTokenInfo = fTokenInfo;
		}
	
		public DateTime GetFTimeStamp() {
			return FTimeStamp;
		}
	
		public void SetFTimeStamp(DateTime fTimeStamp) {
			FTimeStamp = fTimeStamp;
		}
	
	}
}
