// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabScormCmiItemInfo {
	
		// Fields
	
		private String FId;
		private String FCourseNumber;
		private String FPreRequisites;
		private String FDataFromLms;
		private String FScoId;
		private String FCourseId;
		private String FEntityId;
		private String FLaunch;
		private String FMasteryScore;
		private String FMaxtimeAllowed;
		private String FSequence;
		private String FTheLevel;
		private String FTimeLimitAction;
		private String FTitle;
		private String FTheType;
		private String FParameterString;
	
		// Constructors
	
		// Property accessors
	
		public String GetFId() {
			return this.FId;
		}
	
		public void SetFId(String FId_0) {
			this.FId = FId_0;
		}
	
		public String GetFCourseNumber() {
			return this.FCourseNumber;
		}
	
		public void SetFCourseNumber(String FCourseNumber_0) {
			this.FCourseNumber = FCourseNumber_0;
		}
	
		public String GetFPreRequisites() {
			return this.FPreRequisites;
		}
	
		public void SetFPreRequisites(String FPreRequisites_0) {
			this.FPreRequisites = FPreRequisites_0;
		}
	
		public String GetFDataFromLms() {
			return this.FDataFromLms;
		}
	
		public void SetFDataFromLms(String FDataFromLms_0) {
			this.FDataFromLms = FDataFromLms_0;
		}
	
		public String GetFScoId() {
			return this.FScoId;
		}
	
		public void SetFScoId(String FScoId_0) {
			this.FScoId = FScoId_0;
		}
	
		public String GetFCourseId() {
			return this.FCourseId;
		}
	
		public void SetFCourseId(String FCourseId_0) {
			this.FCourseId = FCourseId_0;
		}
	
		public String GetFEntityId() {
			return this.FEntityId;
		}
	
		public void SetFEntityId(String FEntityId_0) {
			this.FEntityId = FEntityId_0;
		}
	
		public String GetFLaunch() {
			return this.FLaunch;
		}
	
		public void SetFLaunch(String FLaunch_0) {
			this.FLaunch = FLaunch_0;
		}
	
		public String GetFMasteryScore() {
			return this.FMasteryScore;
		}
	
		public void SetFMasteryScore(String FMasteryScore_0) {
			this.FMasteryScore = FMasteryScore_0;
		}
	
		public String GetFMaxtimeAllowed() {
			return this.FMaxtimeAllowed;
		}
	
		public void SetFMaxtimeAllowed(String FMaxtimeAllowed_0) {
			this.FMaxtimeAllowed = FMaxtimeAllowed_0;
		}
	
		public String GetFSequence() {
			return this.FSequence;
		}
	
		public void SetFSequence(String FSequence_0) {
			this.FSequence = FSequence_0;
		}
	
		public String GetFTheLevel() {
			return this.FTheLevel;
		}
	
		public void SetFTheLevel(String FTheLevel_0) {
			this.FTheLevel = FTheLevel_0;
		}
	
		public String GetFTimeLimitAction() {
			return this.FTimeLimitAction;
		}
	
		public void SetFTimeLimitAction(String FTimeLimitAction_0) {
			this.FTimeLimitAction = FTimeLimitAction_0;
		}
	
		public String GetFTitle() {
			return this.FTitle;
		}
	
		public void SetFTitle(String FTitle_0) {
			this.FTitle = FTitle_0;
		}
	
		public String GetFTheType() {
			return this.FTheType;
		}
	
		public void SetFTheType(String FTheType_0) {
			this.FTheType = FTheType_0;
		}
	
		public String GetFParameterString() {
			return this.FParameterString;
		}
	
		public void SetFParameterString(String FParameterString_0) {
			this.FParameterString = FParameterString_0;
		}
	
	}
}
