// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabSysPagethemeInfo entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	public class TabSysPagethemeInfo {
	
		// Fields
	
		private String FThemeId;
		private String FThemeName;
		private String FModuleUrl;
		private String FThumbUrl;
		private String FSysuserId;
		private DateTime FUploadTime;
		private String FThemeDesc;
		private String FCssName;
	
		private Int32 FIfDefault;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
		public TabSysPagethemeInfo() {
		}
	
		/// <summary>
		/// minimal constructor 
		/// </summary>
		///
		public TabSysPagethemeInfo(String FThemeId_0) {
			this.FThemeId = FThemeId_0;
		}
	
		/// <summary>
		/// full constructor 
		/// </summary>
		///
		public TabSysPagethemeInfo(String FThemeId_0, String FThemeName_1,
				String FModuleUrl_2, String FThumbUrl_3, String FSysuserId_4,
				DateTime FUploadTime_5, String FThemeDesc_6, String FCssName_7,
				Int32 FIfDefault_8) {
			this.FThemeId = FThemeId_0;
			this.FThemeName = FThemeName_1;
			this.FModuleUrl = FModuleUrl_2;
			this.FThumbUrl = FThumbUrl_3;
			this.FSysuserId = FSysuserId_4;
			this.FUploadTime = FUploadTime_5;
			this.FThemeDesc = FThemeDesc_6;
			this.FCssName = FCssName_7;
			this.FIfDefault = FIfDefault_8;
		}
	
		// Property accessors
	
		public String GetFThemeId() {
			return this.FThemeId;
		}
	
		public void SetFThemeId(String FThemeId_0) {
			this.FThemeId = FThemeId_0;
		}
	
		public String GetFThemeName() {
			return this.FThemeName;
		}
	
		public void SetFThemeName(String FThemeName_0) {
			this.FThemeName = FThemeName_0;
		}
	
		public String GetFModuleUrl() {
			return this.FModuleUrl;
		}
	
		public void SetFModuleUrl(String FModuleUrl_0) {
			this.FModuleUrl = FModuleUrl_0;
		}
	
		public String GetFThumbUrl() {
			return this.FThumbUrl;
		}
	
		public void SetFThumbUrl(String FThumbUrl_0) {
			this.FThumbUrl = FThumbUrl_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public DateTime GetFUploadTime() {
			return this.FUploadTime;
		}
	
		public void SetFUploadTime(DateTime FUploadTime_0) {
			this.FUploadTime = FUploadTime_0;
		}
	
		public String GetFThemeDesc() {
			return this.FThemeDesc;
		}
	
		public void SetFThemeDesc(String FThemeDesc_0) {
			this.FThemeDesc = FThemeDesc_0;
		}
	
		public String GetFCssName() {
			return FCssName;
		}
	
		public void SetFCssName(String fCssName) {
			FCssName = fCssName;
		}
	
		public Int32 GetFIfDefault() {
			return FIfDefault;
		}
	
		public void SetFIfDefault(Int32 fIfDefault) {
			FIfDefault = fIfDefault;
		}
	
	}}
