// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/* @SuppressWarnings("serial")*/
	[Serializable]
	public class TabSysInstitutionInfo {
	
		private String FInstitutionId; //培训机构ID
		private String FInstitutionName; //培训机构名称
		private String FInstitutionDesc; //培训机构描述
		private String FInstitutionLogo; //培训机构Logo
		private String FInstitutionUrl; //培训机构网址
		private String FConnWay; //培训机构联系方式
		private Int32 FSortCode; //排序号
	
		public TabSysInstitutionInfo() : base() {
		}
	
		public TabSysInstitutionInfo(String fInstitutionId,
				String fInstitutionName, String fInstitutionDesc,
				String fInstitutionLogo, String fInstitutionUrl, String fConnWay,
				Int32 fSortCode) : base() {
			FInstitutionId = fInstitutionId;
			FInstitutionName = fInstitutionName;
			FInstitutionDesc = fInstitutionDesc;
			FInstitutionLogo = fInstitutionLogo;
			FInstitutionUrl = fInstitutionUrl;
			FConnWay = fConnWay;
			FSortCode = fSortCode;
		}
	
		public String GetFInstitutionId() {
			return FInstitutionId;
		}
	
		public void SetFInstitutionId(String fInstitutionId) {
			FInstitutionId = fInstitutionId;
		}
	
		public String GetFInstitutionName() {
			return FInstitutionName;
		}
	
		public void SetFInstitutionName(String fInstitutionName) {
			FInstitutionName = fInstitutionName;
		}
	
		public String GetFInstitutionDesc() {
			return FInstitutionDesc;
		}
	
		public void SetFInstitutionDesc(String fInstitutionDesc) {
			FInstitutionDesc = fInstitutionDesc;
		}
	
		public String GetFInstitutionLogo() {
			return FInstitutionLogo;
		}
	
		public void SetFInstitutionLogo(String fInstitutionLogo) {
			FInstitutionLogo = fInstitutionLogo;
		}
	
		public String GetFInstitutionUrl() {
			return FInstitutionUrl;
		}
	
		public void SetFInstitutionUrl(String fInstitutionUrl) {
			FInstitutionUrl = fInstitutionUrl;
		}
	
		public String GetFConnWay() {
			return FConnWay;
		}
	
		public void SetFConnWay(String fConnWay) {
			FConnWay = fConnWay;
		}
	
		public Int32 GetFSortCode() {
			return FSortCode;
		}
	
		public void SetFSortCode(Int32 fSortCode) {
			FSortCode = fSortCode;
		}
	
	}}
