// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabUcenterUserexamInfo {
	
		// Fields
	
		private String FUserexamId;
		private String FPlanexamId;
		private String FUserId;
		private String FOrgId;
		private String FOrgPath;
		private String FServplatId;
		private String FOrgName;
		private String FServplatName;
		private String FUserName;
		private String FRealname;
		private String FPlanId;
		private String FPlanName;
		private String FExamId;
		private String FExamName;
		private Int32 FExamType;
		private DateTime FExamBegintime;
		private DateTime FExamEndtime;
		private Int32 FExamDuration;
		private DateTime FLastexamTime;
		private Double FPassScores;
		private Double FExamScores;
		private String FExamResult;
		private Int32 FActualRetest;
		private Int32 FRetestTimes;
		private Int32 FExamStatus;
		private String FOffice;
		private String FIdcard;
	
		private Int32 messageFlag; //用作数据传输
		private String timeMsg; //用作数据传输
	
		public TabUcenterUserexamInfo() {
		}
	
		// Constructors
		public TabUcenterUserexamInfo(String fUserexamId, String fPlanexamId,
				String fUserId, String fOrgId, String fOrgPath, String fServplatId,
				String fOrgName, String fServplatName, String fUserName,
				String fRealname, String fPlanId, String fPlanName, String fExamId,
				String fExamName, Int32 fExamType, DateTime fExamBegintime,
				DateTime fExamEndtime, Int32 fExamDuration, DateTime fLastexamTime,
				Double fPassScores, Double fExamScores, String fExamResult,
				Int32 fActualRetest, Int32 fRetestTimes, Int32 fExamStatus,
				String fOffice, String fIdcard) : base() {
			FUserexamId = fUserexamId;
			FPlanexamId = fPlanexamId;
			FUserId = fUserId;
			FOrgId = fOrgId;
			FOrgPath = fOrgPath;
			FServplatId = fServplatId;
			FOrgName = fOrgName;
			FServplatName = fServplatName;
			FUserName = fUserName;
			FRealname = fRealname;
			FPlanId = fPlanId;
			FPlanName = fPlanName;
			FExamId = fExamId;
			FExamName = fExamName;
			FExamType = fExamType;
			FExamBegintime = fExamBegintime;
			FExamEndtime = fExamEndtime;
			FExamDuration = fExamDuration;
			FLastexamTime = fLastexamTime;
			FPassScores = fPassScores;
			FExamScores = fExamScores;
			FExamResult = fExamResult;
			FActualRetest = fActualRetest;
			FRetestTimes = fRetestTimes;
			FExamStatus = fExamStatus;
			FOffice = fOffice;
			FIdcard = fIdcard;
		}
	
		// Property accessors
	
		public String GetFUserexamId() {
			return this.FUserexamId;
		}
	
		public void SetFUserexamId(String FUserexamId_0) {
			this.FUserexamId = FUserexamId_0;
		}
	
		public String GetFPlanexamId() {
			return this.FPlanexamId;
		}
	
		public void SetFPlanexamId(String FPlanexamId_0) {
			this.FPlanexamId = FPlanexamId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public String GetFOrgName() {
			return this.FOrgName;
		}
	
		public void SetFOrgName(String FOrgName_0) {
			this.FOrgName = FOrgName_0;
		}
	
		public String GetFServplatName() {
			return this.FServplatName;
		}
	
		public void SetFServplatName(String FServplatName_0) {
			this.FServplatName = FServplatName_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFExamId() {
			return this.FExamId;
		}
	
		public void SetFExamId(String FExamId_0) {
			this.FExamId = FExamId_0;
		}
	
		public String GetFExamName() {
			return this.FExamName;
		}
	
		public void SetFExamName(String FExamName_0) {
			this.FExamName = FExamName_0;
		}
	
		public Int32 GetFExamType() {
			return this.FExamType;
		}
	
		public void SetFExamType(Int32 FExamType_0) {
			this.FExamType = FExamType_0;
		}
	
		public Int32 GetFExamDuration() {
			return this.FExamDuration;
		}
	
		public void SetFExamDuration(Int32 FExamDuration_0) {
			this.FExamDuration = FExamDuration_0;
		}
	
		public DateTime GetFExamBegintime() {
			return FExamBegintime;
		}
	
		public void SetFExamBegintime(DateTime fExamBegintime) {
			FExamBegintime = fExamBegintime;
		}
	
		public DateTime GetFExamEndtime() {
			return FExamEndtime;
		}
	
		public void SetFExamEndtime(DateTime fExamEndtime) {
			FExamEndtime = fExamEndtime;
		}
	
		public Double GetFPassScores() {
			return this.FPassScores;
		}
	
		public void SetFPassScores(Double FPassScores_0) {
			this.FPassScores = FPassScores_0;
		}
	
		public Double GetFExamScores() {
			return this.FExamScores;
		}
	
		public void SetFExamScores(Double FExamScores_0) {
			this.FExamScores = FExamScores_0;
		}
	
		public Int32 GetFRetestTimes() {
			return this.FRetestTimes;
		}
	
		public void SetFRetestTimes(Int32 FRetestTimes_0) {
			this.FRetestTimes = FRetestTimes_0;
		}
	
		public Int32 GetFExamStatus() {
			return this.FExamStatus;
		}
	
		public void SetFExamStatus(Int32 FExamStatus_0) {
			this.FExamStatus = FExamStatus_0;
		}
	
		public String GetFExamResult() {
			return FExamResult;
		}
	
		public void SetFExamResult(String fExamResult) {
			FExamResult = fExamResult;
		}
	
		public Int32 GetFActualRetest() {
			return FActualRetest;
		}
	
		public void SetFActualRetest(Int32 fActualRetest) {
			FActualRetest = fActualRetest;
		}
	
		public String GetFRealname() {
			return FRealname;
		}
	
		public void SetFRealname(String fRealname) {
			FRealname = fRealname;
		}
	
		public String GetFPlanName() {
			return FPlanName;
		}
	
		public void SetFPlanName(String fPlanName) {
			FPlanName = fPlanName;
		}
	
		public DateTime GetFLastexamTime() {
			return FLastexamTime;
		}
	
		public void SetFLastexamTime(DateTime fLastexamTime) {
			FLastexamTime = fLastexamTime;
		}
	
		public String GetFOffice() {
			return FOffice;
		}
	
		public void SetFOffice(String fOffice) {
			FOffice = fOffice;
		}
	
		public String GetFIdcard() {
			return FIdcard;
		}
	
		public void SetFIdcard(String fIdcard) {
			FIdcard = fIdcard;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
		public Int32 GetMessageFlag() {
			return messageFlag;
		}
	
		public void SetMessageFlag(Int32 messageFlag_0) {
			this.messageFlag = messageFlag_0;
		}
	
		public String GetTimeMsg() {
			return timeMsg;
		}
	
		public void SetTimeMsg(String timeMsg_0) {
			this.timeMsg = timeMsg_0;
		}
	
	}
}
