// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabUcenterNoticeBase entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	/* @SuppressWarnings("serial")*/
	public class TabUcenterNoticeBase {
	
		private String FNoticebaseId; //公告信息编号
		private String FNoticeId; //公告信息编号
		private String FPuborgPath; //组织机构路径
		private String FNoticeBaseid; //通知专业基地
	
		public TabUcenterNoticeBase() : base() {
		}
	
		public TabUcenterNoticeBase(String fNoticebaseId, String fNoticeId,
				String fPuborgPath, String fNoticeBaseid2) : base() {
			FNoticebaseId = fNoticebaseId;
			FNoticeId = fNoticeId;
			FPuborgPath = fPuborgPath;
			FNoticeBaseid = fNoticeBaseid2;
		}
	
		public String GetFNoticebaseId() {
			return FNoticebaseId;
		}
	
		public void SetFNoticebaseId(String fNoticebaseId) {
			FNoticebaseId = fNoticebaseId;
		}
	
		public String GetFNoticeId() {
			return FNoticeId;
		}
	
		public void SetFNoticeId(String fNoticeId) {
			FNoticeId = fNoticeId;
		}
	
		public String GetFPuborgPath() {
			return FPuborgPath;
		}
	
		public void SetFPuborgPath(String fPuborgPath) {
			FPuborgPath = fPuborgPath;
		}
	
		public String GetFNoticeBaseid() {
			return FNoticeBaseid;
		}
	
		public void SetFNoticeBaseid(String fNoticeBaseid) {
			FNoticeBaseid = fNoticeBaseid;
		}
	
	}}
