// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// TabUcenterNoticeOrg entity. @author MyEclipse Persistence Tools
	/// </summary>
	///
	[Serializable]
	
	/* @SuppressWarnings("serial")*/
	public class TabUcenterNoticeOrg {
	
		private String FNoticeorgId; //公告信息通知组织机构信息id
		private String FNoticeId; //公告信息编号
		private String FPubOrgid; //发布者组织机构ID
		private String FPuborgPath; //发布者组织机构路径
		private String FNoticeOrgid; //通知到的组织机构ID
		private String FNoticeOrgpath; //通知到的组织机构path
	
		public TabUcenterNoticeOrg() : base() {
		}
	
		public TabUcenterNoticeOrg(String fNoticeorgId, String fNoticeId,
				String fPubOrgid, String fPuborgPath, String fNoticeOrgid2,
				String fNoticeOrgpath) : base() {
			FNoticeorgId = fNoticeorgId;
			FNoticeId = fNoticeId;
			FPubOrgid = fPubOrgid;
			FPuborgPath = fPuborgPath;
			FNoticeOrgid = fNoticeOrgid2;
			FNoticeOrgpath = fNoticeOrgpath;
		}
	
		public String GetFNoticeorgId() {
			return FNoticeorgId;
		}
	
		public void SetFNoticeorgId(String fNoticeorgId) {
			FNoticeorgId = fNoticeorgId;
		}
	
		public String GetFNoticeId() {
			return FNoticeId;
		}
	
		public void SetFNoticeId(String fNoticeId) {
			FNoticeId = fNoticeId;
		}
	
		public String GetFPubOrgid() {
			return FPubOrgid;
		}
	
		public void SetFPubOrgid(String fPubOrgid) {
			FPubOrgid = fPubOrgid;
		}
	
		public String GetFPuborgPath() {
			return FPuborgPath;
		}
	
		public void SetFPuborgPath(String fPuborgPath) {
			FPuborgPath = fPuborgPath;
		}
	
		public String GetFNoticeOrgid() {
			return FNoticeOrgid;
		}
	
		public void SetFNoticeOrgid(String fNoticeOrgid) {
			FNoticeOrgid = fNoticeOrgid;
		}
	
		public String GetFNoticeOrgpath() {
			return FNoticeOrgpath;
		}
	
		public void SetFNoticeOrgpath(String fNoticeOrgpath) {
			FNoticeOrgpath = fNoticeOrgpath;
		}
	
	}}
