// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabUcenterNoticeView {
	
		// Fields
	
		private String FViewId;
		private String FNoticeId;
		private String FUserId;
		private String FUserName;
		private String FPlanId;
		private String FPlanNo;
		private String FServplatId;
		private Int32 FNoticeType;
		private String FNoticeTitle;
		private String FNoticeContent;
		private DateTime FNoticeTime;
		private Int32 FViewStatus;
		private DateTime FViewTime;
		private String FPubName;
	
		// Constructors
	
		/// <summary>
		/// default constructor 
		/// </summary>
		///
	
		// Property accessors
	
		public String GetFViewId() {
			return this.FViewId;
		}
	
		public void SetFViewId(String FViewId_0) {
			this.FViewId = FViewId_0;
		}
	
		public String GetFNoticeId() {
			return this.FNoticeId;
		}
	
		public void SetFNoticeId(String FNoticeId_0) {
			this.FNoticeId = FNoticeId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public Int32 GetFNoticeType() {
			return this.FNoticeType;
		}
	
		public void SetFNoticeType(Int32 FNoticeType_0) {
			this.FNoticeType = FNoticeType_0;
		}
	
		public String GetFNoticeTitle() {
			return this.FNoticeTitle;
		}
	
		public void SetFNoticeTitle(String FNoticeTitle_0) {
			this.FNoticeTitle = FNoticeTitle_0;
		}
	
		public String GetFNoticeContent() {
			return this.FNoticeContent;
		}
	
		public void SetFNoticeContent(String FNoticeContent_0) {
			this.FNoticeContent = FNoticeContent_0;
		}
	
		public DateTime GetFNoticeTime() {
			return this.FNoticeTime;
		}
	
		public void SetFNoticeTime(DateTime FNoticeTime_0) {
			this.FNoticeTime = FNoticeTime_0;
		}
	
		public Int32 GetFViewStatus() {
			return this.FViewStatus;
		}
	
		public void SetFViewStatus(Int32 FViewStatus_0) {
			this.FViewStatus = FViewStatus_0;
		}
	
		public DateTime GetFViewTime() {
			return this.FViewTime;
		}
	
		public void SetFViewTime(DateTime FViewTime_0) {
			this.FViewTime = FViewTime_0;
		}
	
		public String GetFPubName() {
			return FPubName;
		}
	
		public void SetFPubName(String fPubName) {
			FPubName = fPubName;
		}
	
		public String GetFPlanNo() {
			return FPlanNo;
		}
	
		public void SetFPlanNo(String fPlanNo) {
			FPlanNo = fPlanNo;
		}
	
	}
}
