// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabUcenterNoticeInfo {
	
		// Fields
		private String FNoticeId;
		private String FPlanId;
		private String FPlanNo;
		private String FSysuserId;
		private String FServplatId;
		private Int32 FNoticeType;
		private String FNoticeTitle;
		private String FNoticeContent;
		private DateTime FNoticeTime;
		private Int32 FNoticeStatus;
		private String FPubName;
		private Int32 FNoticeWay; //通知途径，1：组织机构；2：专业基地
		private String FNoticeOrgid; //通知的组织机构ID
		private String FNoticeOrgname; //通知的组织机构名称
		private String FNoticeBaseid; //通知的培训机构ID
		private String FNoticeBasename; //通知的培训机构名称
		private String FOrgId; //组织机构ID
		private String FOrgName; //组织机构名称
		private String FOrgPath; //组织机构路径
	
		// Constructors
	
		// Property accessors
	
		public String GetFNoticeId() {
			return this.FNoticeId;
		}
	
		public void SetFNoticeId(String FNoticeId_0) {
			this.FNoticeId = FNoticeId_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFSysuserId() {
			return this.FSysuserId;
		}
	
		public void SetFSysuserId(String FSysuserId_0) {
			this.FSysuserId = FSysuserId_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public Int32 GetFNoticeType() {
			return this.FNoticeType;
		}
	
		public void SetFNoticeType(Int32 FNoticeType_0) {
			this.FNoticeType = FNoticeType_0;
		}
	
		public String GetFNoticeTitle() {
			return this.FNoticeTitle;
		}
	
		public void SetFNoticeTitle(String FNoticeTitle_0) {
			this.FNoticeTitle = FNoticeTitle_0;
		}
	
		public String GetFNoticeContent() {
			return this.FNoticeContent;
		}
	
		public void SetFNoticeContent(String FNoticeContent_0) {
			this.FNoticeContent = FNoticeContent_0;
		}
	
		public DateTime GetFNoticeTime() {
			return this.FNoticeTime;
		}
	
		public void SetFNoticeTime(DateTime FNoticeTime_0) {
			this.FNoticeTime = FNoticeTime_0;
		}
	
		public Int32 GetFNoticeStatus() {
			return this.FNoticeStatus;
		}
	
		public void SetFNoticeStatus(Int32 FNoticeStatus_0) {
			this.FNoticeStatus = FNoticeStatus_0;
		}
	
		public String GetFPlanNo() {
			return FPlanNo;
		}
	
		public void SetFPlanNo(String fPlanNo) {
			FPlanNo = fPlanNo;
		}
	
		public String GetFPubName() {
			return FPubName;
		}
	
		public void SetFPubName(String fPubName) {
			FPubName = fPubName;
		}
	
		public Int32 GetFNoticeWay() {
			return FNoticeWay;
		}
	
		public void SetFNoticeWay(Int32 fNoticeWay) {
			FNoticeWay = fNoticeWay;
		}
	
		public String GetFNoticeOrgid() {
			return FNoticeOrgid;
		}
	
		public void SetFNoticeOrgid(String fNoticeOrgid) {
			FNoticeOrgid = fNoticeOrgid;
		}
	
		public String GetFNoticeOrgname() {
			return FNoticeOrgname;
		}
	
		public void SetFNoticeOrgname(String fNoticeOrgname) {
			FNoticeOrgname = fNoticeOrgname;
		}
	
		public String GetFNoticeBaseid() {
			return FNoticeBaseid;
		}
	
		public void SetFNoticeBaseid(String fNoticeBaseid) {
			FNoticeBaseid = fNoticeBaseid;
		}
	
		public String GetFNoticeBasename() {
			return FNoticeBasename;
		}
	
		public void SetFNoticeBasename(String fNoticeBasename) {
			FNoticeBasename = fNoticeBasename;
		}
	
		public String GetFOrgId() {
			return FOrgId;
		}
	
		public void SetFOrgId(String fOrgId) {
			FOrgId = fOrgId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
	}}
