// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabUcenterArchivesInfo {
	
		// Fields
	
		private String FArchivesId;
		private String FPlanId;
		private String FUserId;
		private String FUserName;
		private String FIdcard;
		private String FRealname;
		private String FSex;
		private String FOrgId;
		private String FOrgName;
		private String FDegreeName;
		private String FOffice;
		private String FPosition;
		private String FPositionLevel;
		private String FPlanName;
		private String FPlanYear;
		private String FPlanNo;
		private String FPlanDesc;
		private String FPlanlogoUrl;
		private Int32 FPlanType;
		private String FBelongsplanId;
		private Int32 FJoinType;
		private DateTime FStartTime;
		private DateTime FEndTime;
		private String FServplatId;
		private String FServplatName;
		private Double FAssessHours;
		private Double FAssessScores;
		private Double FGetHours;
		private Double FGetScores;
		private String FTrainCertificate;
		private Int32 FUserStatus;
		private Int32 FTrainStatus;
		private Int32 FTrainResult;
		private String FBaseName;
		private Int32 FAccessWay;
		private Int32 FIfSeal;
		private DateTime FAddTime;
		private String FOrgPath;
		private String FBaseId;
		private Int32 FAssessType;//f_assess_way
		private Double FMinMust;//f_min_must
	
		public Int32 GetFJoinType() {
			return FJoinType;
		}
	
		public void SetFJoinType(Int32 fJoinType) {
			FJoinType = fJoinType;
		}
	
		// Constructors
	
		// Property accessors
	
		public String GetFArchivesId() {
			return this.FArchivesId;
		}
	
		public void SetFArchivesId(String FArchivesId_0) {
			this.FArchivesId = FArchivesId_0;
		}
	
		public String GetFPlanId() {
			return this.FPlanId;
		}
	
		public void SetFPlanId(String FPlanId_0) {
			this.FPlanId = FPlanId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFIdcard() {
			return this.FIdcard;
		}
	
		public void SetFIdcard(String FIdcard_0) {
			this.FIdcard = FIdcard_0;
		}
	
		public String GetFRealname() {
			return this.FRealname;
		}
	
		public void SetFRealname(String FRealname_0) {
			this.FRealname = FRealname_0;
		}
	
		public String GetFSex() {
			return this.FSex;
		}
	
		public void SetFSex(String FSex_0) {
			this.FSex = FSex_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFOrgName() {
			return this.FOrgName;
		}
	
		public void SetFOrgName(String FOrgName_0) {
			this.FOrgName = FOrgName_0;
		}
	
		public String GetFDegreeName() {
			return this.FDegreeName;
		}
	
		public void SetFDegreeName(String FDegreeName_0) {
			this.FDegreeName = FDegreeName_0;
		}
	
		public String GetFPosition() {
			return this.FPosition;
		}
	
		public void SetFPosition(String FPosition_0) {
			this.FPosition = FPosition_0;
		}
	
		public String GetFPositionLevel() {
			return this.FPositionLevel;
		}
	
		public void SetFPositionLevel(String FPositionLevel_0) {
			this.FPositionLevel = FPositionLevel_0;
		}
	
		public String GetFPlanName() {
			return this.FPlanName;
		}
	
		public void SetFPlanName(String FPlanName_0) {
			this.FPlanName = FPlanName_0;
		}
	
		public String GetFPlanNo() {
			return this.FPlanNo;
		}
	
		public void SetFPlanNo(String FPlanNo_0) {
			this.FPlanNo = FPlanNo_0;
		}
	
		public String GetFPlanDesc() {
			return this.FPlanDesc;
		}
	
		public void SetFPlanDesc(String FPlanDesc_0) {
			this.FPlanDesc = FPlanDesc_0;
		}
	
		public String GetFPlanlogoUrl() {
			return this.FPlanlogoUrl;
		}
	
		public void SetFPlanlogoUrl(String FPlanlogoUrl_0) {
			this.FPlanlogoUrl = FPlanlogoUrl_0;
		}
	
		public DateTime GetFStartTime() {
			return this.FStartTime;
		}
	
		public void SetFStartTime(DateTime FStartTime_0) {
			this.FStartTime = FStartTime_0;
		}
	
		public DateTime GetFEndTime() {
			return this.FEndTime;
		}
	
		public void SetFEndTime(DateTime FEndTime_0) {
			this.FEndTime = FEndTime_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public String GetFServplatName() {
			return this.FServplatName;
		}
	
		public void SetFServplatName(String FServplatName_0) {
			this.FServplatName = FServplatName_0;
		}
	
		public Double GetFAssessHours() {
			return this.FAssessHours;
		}
	
		public void SetFAssessHours(Double FAssessHours_0) {
			this.FAssessHours = FAssessHours_0;
		}
	
		public Double GetFAssessScores() {
			return this.FAssessScores;
		}
	
		public void SetFAssessScores(Double FAssessScores_0) {
			this.FAssessScores = FAssessScores_0;
		}
	
		public Double GetFGetHours() {
			return this.FGetHours;
		}
	
		public void SetFGetHours(Double FGetHours_0) {
			this.FGetHours = FGetHours_0;
		}
	
		public Double GetFGetScores() {
			return this.FGetScores;
		}
	
		public void SetFGetScores(Double FGetScores_0) {
			this.FGetScores = FGetScores_0;
		}
	
		public String GetFTrainCertificate() {
			return this.FTrainCertificate;
		}
	
		public void SetFTrainCertificate(String FTrainCertificate_0) {
			this.FTrainCertificate = FTrainCertificate_0;
		}
	
		public Int32 GetFTrainStatus() {
			return this.FTrainStatus;
		}
	
		public void SetFTrainStatus(Int32 FTrainStatus_0) {
			this.FTrainStatus = FTrainStatus_0;
		}
	
		public Int32 GetFTrainResult() {
			return this.FTrainResult;
		}
	
		public void SetFTrainResult(Int32 FTrainResult_0) {
			this.FTrainResult = FTrainResult_0;
		}
	
		public String GetFOffice() {
			return FOffice;
		}
	
		public void SetFOffice(String fOffice) {
			FOffice = fOffice;
		}
	
		public String GetFPlanYear() {
			return FPlanYear;
		}
	
		public void SetFPlanYear(String fPlanYear) {
			FPlanYear = fPlanYear;
		}
	
		public Int32 GetFPlanType() {
			return FPlanType;
		}
	
		public void SetFPlanType(Int32 fPlanType) {
			FPlanType = fPlanType;
		}
	
		public String GetFBelongsplanId() {
			return FBelongsplanId;
		}
	
		public void SetFBelongsplanId(String fBelongsplanId) {
			FBelongsplanId = fBelongsplanId;
		}
	
		public Int32 GetFUserStatus() {
			return FUserStatus;
		}
	
		public void SetFUserStatus(Int32 fUserStatus) {
			FUserStatus = fUserStatus;
		}
	
		public DateTime GetFAddTime() {
			return FAddTime;
		}
	
		public void SetFAddTime(DateTime fAddTime) {
			FAddTime = fAddTime;
		}
	
		public Int32 GetFIfSeal() {
			return FIfSeal;
		}
	
		public void SetFIfSeal(Int32 fIfSeal) {
			FIfSeal = fIfSeal;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
		public Int32 GetFAccessWay() {
			return FAccessWay;
		}
	
		public void SetFAccessWay(Int32 fAccessWay) {
			FAccessWay = fAccessWay;
		}
	
		public String GetFBaseId() {
			return FBaseId;
		}
	
		public void SetFBaseId(String fBaseId) {
			FBaseId = fBaseId;
		}
	
		public String GetFBaseName() {
			return FBaseName;
		}
	
		public void SetFBaseName(String fBaseName) {
			FBaseName = fBaseName;
		}
	
		public Int32 GetFAssessType() {
			return FAssessType;
		}
	
		public void SetFAssessType(Int32 fAssessType) {
			FAssessType = fAssessType;
		}
	
		public Double GetFMinMust() {
			return FMinMust;
		}
	
		public void SetFMinMust(Double fMinMust) {
			FMinMust = fMinMust;
		}
	
	}}
