// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabUcenterMailView {
	
		// Fields
	
		private String FViewId;
		private String FUserId;
		private String FUserName;
		private String FSendName;
		private String FMailId;
		private String FMailTitle;
		private String FMailContent;
		private String FReplyMailid;
		private DateTime FMailTime;
		private Int32 FMailType;
		private Int32 FViewStatus;
		private DateTime FViewTime;
	
		// Constructors
	
		// Property accessors
	
		public String GetFViewId() {
			return this.FViewId;
		}
	
		public void SetFViewId(String FViewId_0) {
			this.FViewId = FViewId_0;
		}
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFSendName() {
			return this.FSendName;
		}
	
		public void SetFSendName(String FSendName_0) {
			this.FSendName = FSendName_0;
		}
	
		public String GetFMailId() {
			return this.FMailId;
		}
	
		public void SetFMailId(String FMailId_0) {
			this.FMailId = FMailId_0;
		}
	
		public String GetFMailTitle() {
			return this.FMailTitle;
		}
	
		public void SetFMailTitle(String FMailTitle_0) {
			this.FMailTitle = FMailTitle_0;
		}
	
		public String GetFMailContent() {
			return this.FMailContent;
		}
	
		public void SetFMailContent(String FMailContent_0) {
			this.FMailContent = FMailContent_0;
		}
	
		public String GetFReplyMailid() {
			return this.FReplyMailid;
		}
	
		public void SetFReplyMailid(String FReplyMailid_0) {
			this.FReplyMailid = FReplyMailid_0;
		}
	
		public DateTime GetFMailTime() {
			return this.FMailTime;
		}
	
		public void SetFMailTime(DateTime FMailTime_0) {
			this.FMailTime = FMailTime_0;
		}
	
		public Int32 GetFMailType() {
			return this.FMailType;
		}
	
		public void SetFMailType(Int32 FMailType_0) {
			this.FMailType = FMailType_0;
		}
	
		public Int32 GetFViewStatus() {
			return this.FViewStatus;
		}
	
		public void SetFViewStatus(Int32 FViewStatus_0) {
			this.FViewStatus = FViewStatus_0;
		}
	
		public DateTime GetFViewTime() {
			return this.FViewTime;
		}
	
		public void SetFViewTime(DateTime FViewTime_0) {
			this.FViewTime = FViewTime_0;
		}
	
	}}
