// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
    using System.Collections.Generic;
	
	/* @SuppressWarnings("serial")*/
	[Serializable]
	public class TabUserPlanDetail {
	
		private TabPlanPlanuserInfo tabPlanPlanuserInfo;
		private TabUcenterArchivesInfo tabUcenterArchivesInfo;
		private IList<TabUcenterStudentCourse> studentCourseList;
		private IList<TabPlanPlancourInfo> plancourInfoList;
	
		public TabUserPlanDetail() {
		} 
	
		public TabUserPlanDetail(TabPlanPlanuserInfo tabPlanPlanuserInfo_0,
				TabUcenterArchivesInfo tabUcenterArchivesInfo_1,
				IList<TabUcenterStudentCourse> studentCourseList_2,
				IList<TabPlanPlancourInfo> plancourInfoList_3) {
			this.tabPlanPlanuserInfo = tabPlanPlanuserInfo_0;
			this.tabUcenterArchivesInfo = tabUcenterArchivesInfo_1;
			this.studentCourseList = studentCourseList_2;
			this.plancourInfoList = plancourInfoList_3;
		}
	
		public TabPlanPlanuserInfo GetTabPlanPlanuserInfo() {
			return tabPlanPlanuserInfo;
		}
	
		public void SetTabPlanPlanuserInfo(TabPlanPlanuserInfo tabPlanPlanuserInfo_0) {
			this.tabPlanPlanuserInfo = tabPlanPlanuserInfo_0;
		}
	
		public TabUcenterArchivesInfo GetTabUcenterArchivesInfo() {
			return tabUcenterArchivesInfo;
		}
	
		public void SetTabUcenterArchivesInfo(
				TabUcenterArchivesInfo tabUcenterArchivesInfo_0) {
			this.tabUcenterArchivesInfo = tabUcenterArchivesInfo_0;
		}
	
		public IList<TabUcenterStudentCourse> GetStudentCourseList() {
			return studentCourseList;
		}
	
		public void SetStudentCourseList(
				IList<TabUcenterStudentCourse> studentCourseList_0) {
			this.studentCourseList = studentCourseList_0;
		}
	
		public IList<TabPlanPlancourInfo> GetPlancourInfoList() {
			return plancourInfoList;
		}
	
		public void SetPlancourInfoList(IList<TabPlanPlancourInfo> plancourInfoList_0) {
			this.plancourInfoList = plancourInfoList_0;
		}
	}
}
