// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabUcenterMailInfo {
		// Fields
	
		private String FMailId;
		private String FMailTitle;
		private String FSendUserid;
		private String FUserName;
		private String FReceiveUserid;
		private String FReceiveName;
		private String FMailContent;
		private String FReplyMailid;
		private DateTime FMailTime;
		private Int32 FMailType;
		private Int32 FMailStatus;
	
		// Constructors
	
		// Property accessors
	
		public String GetFMailId() {
			return this.FMailId;
		}
	
		public void SetFMailId(String FMailId_0) {
			this.FMailId = FMailId_0;
		}
	
		public String GetFMailTitle() {
			return this.FMailTitle;
		}
	
		public void SetFMailTitle(String FMailTitle_0) {
			this.FMailTitle = FMailTitle_0;
		}
	
		public String GetFSendUserid() {
			return this.FSendUserid;
		}
	
		public void SetFSendUserid(String FSendUserid_0) {
			this.FSendUserid = FSendUserid_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFReceiveUserid() {
			return this.FReceiveUserid;
		}
	
		public void SetFReceiveUserid(String FReceiveUserid_0) {
			this.FReceiveUserid = FReceiveUserid_0;
		}
	
		public String GetFReceiveName() {
			return this.FReceiveName;
		}
	
		public void SetFReceiveName(String FReceiveName_0) {
			this.FReceiveName = FReceiveName_0;
		}
	
		public String GetFMailContent() {
			return this.FMailContent;
		}
	
		public void SetFMailContent(String FMailContent_0) {
			this.FMailContent = FMailContent_0;
		}
	
		public String GetFReplyMailid() {
			return this.FReplyMailid;
		}
	
		public void SetFReplyMailid(String FReplyMailid_0) {
			this.FReplyMailid = FReplyMailid_0;
		}
	
		public DateTime GetFMailTime() {
			return this.FMailTime;
		}
	
		public void SetFMailTime(DateTime FMailTime_0) {
			this.FMailTime = FMailTime_0;
		}
	
		public Int32 GetFMailType() {
			return this.FMailType;
		}
	
		public void SetFMailType(Int32 FMailType_0) {
			this.FMailType = FMailType_0;
		}
	
		public Int32 GetFMailStatus() {
			return this.FMailStatus;
		}
	
		public void SetFMailStatus(Int32 FMailStatus_0) {
			this.FMailStatus = FMailStatus_0;
		}
	
	}
}
