// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 上午10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabUcenterArchivesOnline {
	
		private String FOnlineId;
		private String FArchivesId;
		private String FPlanId;
		private String FUserId;
		private String FUserName;
		private String FRealName;
		private String FOffice;
		private String FOrgId;
		private String FOrgName;
		private String FServplatId;
		private String FServplatName;
		private String FCourseId;
		private String FEntityId;
		private String FCourseNumber;
		private String FCourseName;
		private Int32 FCourseType;
		private Double FCourseHours;
		private Double FCourseScores;
		private Int32 FIfTest;
		private String FStudyProgress;
		private String FTestScores;
		private Double FGetHours;
		private Double FGetScores;
		private DateTime FAddTime;
		private Double FCoursePrice; //课程价格  2013-1-17  zl
		private DateTime FFinishTime; //课程看完时间 2013-1-17  zl
	
		private String FBaseId;
	
		private String FOrgPath;
	
		//非数据库字段
		private Double passScores;
	
		private int filterType;
	
		public String GetFOnlineId() {
			return FOnlineId;
		}
	
		public void SetFOnlineId(String fOnlineId) {
			FOnlineId = fOnlineId;
		}
	
		public String GetFArchivesId() {
			return FArchivesId;
		}
	
		public void SetFArchivesId(String fArchivesId) {
			FArchivesId = fArchivesId;
		}
	
		public String GetFPlanId() {
			return FPlanId;
		}
	
		public void SetFPlanId(String fPlanId) {
			FPlanId = fPlanId;
		}
	
		public String GetFUserId() {
			return FUserId;
		}
	
		public void SetFUserId(String fUserId) {
			FUserId = fUserId;
		}
	
		public String GetFUserName() {
			return FUserName;
		}
	
		public void SetFUserName(String fUserName) {
			FUserName = fUserName;
		}
	
		public String GetFOrgId() {
			return FOrgId;
		}
	
		public void SetFOrgId(String fOrgId) {
			FOrgId = fOrgId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
		public String GetFCourseId() {
			return FCourseId;
		}
	
		public void SetFCourseId(String fCourseId) {
			FCourseId = fCourseId;
		}
	
		public String GetFEntityId() {
			return FEntityId;
		}
	
		public void SetFEntityId(String fEntityId) {
			FEntityId = fEntityId;
		}
	
		public String GetFCourseNumber() {
			return FCourseNumber;
		}
	
		public void SetFCourseNumber(String fCourseNumber) {
			FCourseNumber = fCourseNumber;
		}
	
		public String GetFCourseName() {
			return FCourseName;
		}
	
		public void SetFCourseName(String fCourseName) {
			FCourseName = fCourseName;
		}
	
		public Int32 GetFCourseType() {
			return FCourseType;
		}
	
		public void SetFCourseType(Int32 fCourseType) {
			FCourseType = fCourseType;
		}
	
		public Double GetFCourseHours() {
			return FCourseHours;
		}
	
		public void SetFCourseHours(Double fCourseHours) {
			FCourseHours = fCourseHours;
		}
	
		public Double GetFCourseScores() {
			return FCourseScores;
		}
	
		public void SetFCourseScores(Double fCourseScores) {
			FCourseScores = fCourseScores;
		}
	
		public Int32 GetFIfTest() {
			return FIfTest;
		}
	
		public void SetFIfTest(Int32 fIfTest) {
			FIfTest = fIfTest;
		}
	
		public String GetFStudyProgress() {
			return FStudyProgress;
		}
	
		public void SetFStudyProgress(String fStudyProgress) {
			FStudyProgress = fStudyProgress;
		}
	
		public String GetFTestScores() {
			return FTestScores;
		}
	
		public void SetFTestScores(String fTestScores) {
			FTestScores = fTestScores;
		}
	
		public Double GetFGetHours() {
			return FGetHours;
		}
	
		public void SetFGetHours(Double fGetHours) {
			FGetHours = fGetHours;
		}
	
		public Double GetFGetScores() {
			return FGetScores;
		}
	
		public void SetFGetScores(Double fGetScores) {
			FGetScores = fGetScores;
		}
	
		public String GetFRealName() {
			return FRealName;
		}
	
		public void SetFRealName(String fRealName) {
			FRealName = fRealName;
		}
	
		public String GetFOffice() {
			return FOffice;
		}
	
		public void SetFOffice(String fOffice) {
			FOffice = fOffice;
		}
	
		public DateTime GetFAddTime() {
			return FAddTime;
		}
	
		public void SetFAddTime(DateTime fAddTime) {
			FAddTime = fAddTime;
		}
	
		public Double GetPassScores() {
			return passScores;
		}
	
		public void SetPassScores(Double passScores_0) {
			this.passScores = passScores_0;
		}
	
		public int GetFilterType() {
			return filterType;
		}
	
		public void SetFilterType(int filterType_0) {
			this.filterType = filterType_0;
		}
	
		public String GetFOrgPath() {
			return FOrgPath;
		}
	
		public void SetFOrgPath(String fOrgPath) {
			FOrgPath = fOrgPath;
		}
	
		public String GetFBaseId() {
			return FBaseId;
		}
	
		public void SetFBaseId(String fBaseId) {
			FBaseId = fBaseId;
		}
	
		public Double GetFCoursePrice() {
			return FCoursePrice;
		}
	
		public void SetFCoursePrice(Double fCoursePrice) {
			FCoursePrice = fCoursePrice;
		}
	
		public DateTime GetFFinishTime() {
			return FFinishTime;
		}
	
		public void SetFFinishTime(DateTime fFinishTime) {
			FFinishTime = fFinishTime;
		}
	
	}
}
