// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	/// <summary>
	/// AbstractTabUserUserInfo entity provides the base persistence definition of
	/// the TabUserUserInfo entity.
	/// </summary>
	///
	[Serializable]
	
	public class TabUserUserInfo {
	
		// Fields
	
		private String FUserId;
		private String FUserName;
		private String FPassword;
		private String FRoutingId;
		private String FParentId;
		private String FIdcard;
		private String FUserlogoUrl;
		private String FRealname;
		private String FSex;
		private DateTime FBirthday;
		private String FServplatId;
		private String FOrgId;
		private String FOffice;
		private String FPosition;
		private String FPolevelId;
		private String FBaseId;
		private String FPoliticalId;
		private String FDegreeId;
		private String FNatioinId;
		private String FIdentityId;
		private String FProfId;
		private String FMobile;
		private String FOfficePhone;
		private String FEmail;
		private Int32 FIfStudent;
		private Int32 FIdType;
		private DateTime FCreateTime;
		private Int32 FStatus;
	
		// Constructors
	
		// Property accessors
	
		public String GetFUserId() {
			return this.FUserId;
		}
	
		public void SetFUserId(String FUserId_0) {
			this.FUserId = FUserId_0;
		}
	
		public String GetFUserName() {
			return this.FUserName;
		}
	
		public void SetFUserName(String FUserName_0) {
			this.FUserName = FUserName_0;
		}
	
		public String GetFPassword() {
			return this.FPassword;
		}
	
		public void SetFPassword(String FPassword_0) {
			this.FPassword = FPassword_0;
		}
	
		public String GetFParentId() {
			return this.FParentId;
		}
	
		public void SetFParentId(String FParentId_0) {
			this.FParentId = FParentId_0;
		}
	
		public String GetFIdcard() {
			return this.FIdcard;
		}
	
		public void SetFIdcard(String FIdcard_0) {
			this.FIdcard = FIdcard_0;
		}
	
		public String GetFRealname() {
			return this.FRealname;
		}
	
		public void SetFRealname(String FRealname_0) {
			this.FRealname = FRealname_0;
		}
	
		public String GetFSex() {
			return this.FSex;
		}
	
		public void SetFSex(String FSex_0) {
			this.FSex = FSex_0;
		}
	
		public DateTime GetFBirthday() {
			return this.FBirthday;
		}
	
		public void SetFBirthday(DateTime FBirthday_0) {
			this.FBirthday = FBirthday_0;
		}
	
		public String GetFServplatId() {
			return this.FServplatId;
		}
	
		public void SetFServplatId(String FServplatId_0) {
			this.FServplatId = FServplatId_0;
		}
	
		public String GetFOrgId() {
			return this.FOrgId;
		}
	
		public void SetFOrgId(String FOrgId_0) {
			this.FOrgId = FOrgId_0;
		}
	
		public String GetFOffice() {
			return this.FOffice;
		}
	
		public void SetFOffice(String FOffice_0) {
			this.FOffice = FOffice_0;
		}
	
		public String GetFPosition() {
			return this.FPosition;
		}
	
		public void SetFPosition(String FPosition_0) {
			this.FPosition = FPosition_0;
		}
	
		public String GetFPolevelId() {
			return this.FPolevelId;
		}
	
		public void SetFPolevelId(String FPolevelId_0) {
			this.FPolevelId = FPolevelId_0;
		}
	
		public String GetFBaseId() {
			return this.FBaseId;
		}
	
		public void SetFBaseId(String FBaseId_0) {
			this.FBaseId = FBaseId_0;
		}
	
		public String GetFPoliticalId() {
			return this.FPoliticalId;
		}
	
		public void SetFPoliticalId(String FPoliticalId_0) {
			this.FPoliticalId = FPoliticalId_0;
		}
	
		public String GetFDegreeId() {
			return this.FDegreeId;
		}
	
		public void SetFDegreeId(String FDegreeId_0) {
			this.FDegreeId = FDegreeId_0;
		}
	
		public String GetFNatioinId() {
			return this.FNatioinId;
		}
	
		public void SetFNatioinId(String FNatioinId_0) {
			this.FNatioinId = FNatioinId_0;
		}
	
		public String GetFIdentityId() {
			return this.FIdentityId;
		}
	
		public void SetFIdentityId(String FIdentityId_0) {
			this.FIdentityId = FIdentityId_0;
		}
	
		public String GetFProfId() {
			return this.FProfId;
		}
	
		public void SetFProfId(String FProfId_0) {
			this.FProfId = FProfId_0;
		}
	
		public String GetFMobile() {
			return this.FMobile;
		}
	
		public void SetFMobile(String FMobile_0) {
			this.FMobile = FMobile_0;
		}
	
		public String GetFOfficePhone() {
			return this.FOfficePhone;
		}
	
		public void SetFOfficePhone(String FOfficePhone_0) {
			this.FOfficePhone = FOfficePhone_0;
		}
	
		public String GetFEmail() {
			return this.FEmail;
		}
	
		public void SetFEmail(String FEmail_0) {
			this.FEmail = FEmail_0;
		}
	
		public DateTime GetFCreateTime() {
			return this.FCreateTime;
		}
	
		public void SetFCreateTime(DateTime FCreateTime_0) {
			this.FCreateTime = FCreateTime_0;
		}
	
		public Int32 GetFStatus() {
			return this.FStatus;
		}
	
		public void SetFStatus(Int32 FStatus_0) {
			this.FStatus = FStatus_0;
		}
	
		public String GetFRoutingId() {
			return FRoutingId;
		}
	
		public void SetFRoutingId(String fRoutingId) {
			FRoutingId = fRoutingId;
		}
	
		public String GetFUserlogoUrl() {
			return FUserlogoUrl;
		}
	
		public void SetFUserlogoUrl(String fUserlogoUrl) {
			FUserlogoUrl = fUserlogoUrl;
		}
	
		public Int32 GetFIfStudent() {
			return FIfStudent;
		}
	
		public void SetFIfStudent(Int32 fIfStudent) {
			FIfStudent = fIfStudent;
		}
	
		public Int32 GetFIdType() {
			return FIdType;
		}
	
		public void SetFIdType(Int32 fIdType) {
			FIdType = fIdType;
		}
	
	}}
