// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 14-1-24 ÉÏÎç10:49    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Com.Chinahrt.Student.Dto {
	
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using System.Runtime.Serialization;
	
	[Serializable]
	public class TabUcenterArchivesOffline {
	
		private String FOfflineId;
		private String FArchivesId;
		private String FPlanId;
		private String FUserId;
		private String FUserName;
		private String FRealname;
		private String FOrgId;
		private String FOrgName;
		private String FServplatId;
		private String FServplatName;
		private String FBaseId;
		private String FOfftrainName;
		private String FOfftrainDesc;
		private String FEduInstitutions;
		private String FTrainTime;
		private Double FTrainHours;
		private Double FTrainScores;
		private DateTime FApplyTime;
		private Double FApplyHours;
		private Double FApplyScores;
		private String FTrainCertificate;
		private String FOfftrainResult;
		private String FCourseId;
		private String FEntityId;
		private String FCourseNumber;
		private String FCourseName;
		private Int32 FVerifyStatus;
		private String FVerifyReason;
		private DateTime FVerifyTime;
		private DateTime FTimeStamp;
	
		public String GetFOfflineId() {
			return FOfflineId;
		}
	
		public void SetFOfflineId(String fOfflineId) {
			FOfflineId = fOfflineId;
		}
	
		public String GetFArchivesId() {
			return FArchivesId;
		}
	
		public void SetFArchivesId(String fArchivesId) {
			FArchivesId = fArchivesId;
		}
	
		public String GetFPlanId() {
			return FPlanId;
		}
	
		public void SetFPlanId(String fPlanId) {
			FPlanId = fPlanId;
		}
	
		public String GetFUserId() {
			return FUserId;
		}
	
		public void SetFUserId(String fUserId) {
			FUserId = fUserId;
		}
	
		public String GetFUserName() {
			return FUserName;
		}
	
		public void SetFUserName(String fUserName) {
			FUserName = fUserName;
		}
	
		public String GetFOrgId() {
			return FOrgId;
		}
	
		public void SetFOrgId(String fOrgId) {
			FOrgId = fOrgId;
		}
	
		public String GetFOrgName() {
			return FOrgName;
		}
	
		public void SetFOrgName(String fOrgName) {
			FOrgName = fOrgName;
		}
	
		public String GetFServplatId() {
			return FServplatId;
		}
	
		public void SetFServplatId(String fServplatId) {
			FServplatId = fServplatId;
		}
	
		public String GetFServplatName() {
			return FServplatName;
		}
	
		public void SetFServplatName(String fServplatName) {
			FServplatName = fServplatName;
		}
	
		public String GetFOfftrainName() {
			return FOfftrainName;
		}
	
		public void SetFOfftrainName(String fOfftrainName) {
			FOfftrainName = fOfftrainName;
		}
	
		public String GetFOfftrainDesc() {
			return FOfftrainDesc;
		}
	
		public void SetFOfftrainDesc(String fOfftrainDesc) {
			FOfftrainDesc = fOfftrainDesc;
		}
	
		public String GetFEduInstitutions() {
			return FEduInstitutions;
		}
	
		public void SetFEduInstitutions(String fEduInstitutions) {
			FEduInstitutions = fEduInstitutions;
		}
	
		public String GetFTrainTime() {
			return FTrainTime;
		}
	
		public void SetFTrainTime(String fTrainTime) {
			FTrainTime = fTrainTime;
		}
	
		public Double GetFTrainHours() {
			return FTrainHours;
		}
	
		public void SetFTrainHours(Double fTrainHours) {
			FTrainHours = fTrainHours;
		}
	
		public Double GetFTrainScores() {
			return FTrainScores;
		}
	
		public void SetFTrainScores(Double fTrainScores) {
			FTrainScores = fTrainScores;
		}
	
		public DateTime GetFApplyTime() {
			return FApplyTime;
		}
	
		public void SetFApplyTime(DateTime fApplyTime) {
			FApplyTime = fApplyTime;
		}
	
		public Double GetFApplyHours() {
			return FApplyHours;
		}
	
		public void SetFApplyHours(Double fApplyHours) {
			FApplyHours = fApplyHours;
		}
	
		public Double GetFApplyScores() {
			return FApplyScores;
		}
	
		public void SetFApplyScores(Double fApplyScores) {
			FApplyScores = fApplyScores;
		}
	
		public String GetFTrainCertificate() {
			return FTrainCertificate;
		}
	
		public void SetFTrainCertificate(String fTrainCertificate) {
			FTrainCertificate = fTrainCertificate;
		}
	
		public String GetFOfftrainResult() {
			return FOfftrainResult;
		}
	
		public void SetFOfftrainResult(String fOfftrainResult) {
			FOfftrainResult = fOfftrainResult;
		}
	
		public String GetFCourseId() {
			return FCourseId;
		}
	
		public void SetFCourseId(String fCourseId) {
			FCourseId = fCourseId;
		}
	
		public String GetFEntityId() {
			return FEntityId;
		}
	
		public void SetFEntityId(String fEntityId) {
			FEntityId = fEntityId;
		}
	
		public String GetFCourseNumber() {
			return FCourseNumber;
		}
	
		public void SetFCourseNumber(String fCourseNumber) {
			FCourseNumber = fCourseNumber;
		}
	
		public String GetFCourseName() {
			return FCourseName;
		}
	
		public void SetFCourseName(String fCourseName) {
			FCourseName = fCourseName;
		}
	
		public Int32 GetFVerifyStatus() {
			return FVerifyStatus;
		}
	
		public void SetFVerifyStatus(Int32 fVerifyStatus) {
			FVerifyStatus = fVerifyStatus;
		}
	
		public String GetFVerifyReason() {
			return FVerifyReason;
		}
	
		public void SetFVerifyReason(String fVerifyReason) {
			FVerifyReason = fVerifyReason;
		}
	
		public DateTime GetFVerifyTime() {
			return FVerifyTime;
		}
	
		public void SetFVerifyTime(DateTime fVerifyTime) {
			FVerifyTime = fVerifyTime;
		}
	
		public String GetFBaseId() {
			return FBaseId;
		}
	
		public void SetFBaseId(String fBaseId) {
			FBaseId = fBaseId;
		}
	
		public DateTime GetFTimeStamp() {
			return FTimeStamp;
		}
	
		public void SetFTimeStamp(DateTime fTimeStamp) {
			FTimeStamp = fTimeStamp;
		}
	
		public String GetFRealname() {
			return FRealname;
		}
	
		public void SetFRealname(String fRealname) {
			FRealname = fRealname;
		}
	}
}
